### ISSUE TITLE
[feat] **Piecewise** Rectified Flow

### ISSUE THREAD

**Issue by kabachuha** [hpcaitech/Open-Sora#109]
As you know from SD3's paper they used Rectified Flow to make the training and the sampling process faster. However, in the past month a new modification of Rectified Flow named PiecewiseRectifiedFlow was released

Project page: https://piecewise-rectified-flow.github.io/
Github: https://github.com/magic-research/piecewise-rectified-flow/tree/main

Claims to be faster than the normal Rectified Flow (used in https://github.com/PKU-YuanGroup/Open-Sora-Plan/issues/43)

I believe it will be a huge quality/speed win compared to the vanilla diffusion pipeline that is used at this moment here

**Comment by zhengzangw** [comment]
Thanks for your suggestion. Next version will have rectified flow.
