### ISSUE TITLE
training one's own dataset 

### ISSUE THREAD

**Issue by Duyz232** [hpcaitech/Open-Sora#111]
Does this project support training one's own dataset from scratch

**Comment by JThh** [comment]
Yes, please refer to the training guide on providing your own datasets: https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#training.

**Comment by zhengzangw** [comment]
and here for dataset format
https://github.com/hpcaitech/Open-Sora/blob/main/tools/datasets/README.md
