### ISSUE TITLE
[feat] ControlNet-Transformer and SparseCtrl

### ISSUE THREAD

**Issue by kabachuha** [hpcaitech/Open-Sora#113]
ControlNet is a pretty musthave feature for diffusion models, so it will be nice to have it implemented

For example, PixArt-alpha has a ControlNet-Transformer (modified from the Unet-one) module allowing it to take various conditionings

Additionally, the authors of AnimateDiff have released the SparseCtrl ControlNet modification specially for text2video enabling it to take the conditions sparsely at given frames instead of requiring to duplicate/interpolate them to all the frames

https://github.com/guoyww/AnimateDiff#202312-animatediff-v3-and-sparsectrl

**Comment by zhengzangw** [comment]
We will pay more effort to control when the base is good enough.
