### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by oceanogeology** [hpcaitech/Open-Sora#116]
> /data/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/text_encoder/t5.py(145)__init__()
-> self.model = T5EncoderModel.from_pretrained(path, **t5_model_kwargs).eval()
(Pdb) n
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
> /data/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/text_encoder/t5.py(145)__init__()
-> self.model = T5EncoderModel.from_pretrained(path, **t5_model_kwargs).eval()

**Comment by 520zhou** [comment]
I have the same problem.

**Comment by 520zhou** [comment]
#116 请问你有没有遇到这个问题。apex安装报错是怎么解决的？我的cuda是12.0

**Comment by oceanogeology** [comment]
cuda 12.1 gcc8.3.1 torch2.2.1然后再apex源码编译，就好了。
git clone https://github.com/NVIDIA/apex
cd apex
# if pip >= 23.1 (ref: https://pip.pypa.io/en/stable/news/#v23-1) which supports multiple `--config-settings` with the same key... 
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./

不过出现了新的bug：
  File "/data/anaconda3/envs/opensora/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 51, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

**Comment by oceanogeology** [comment]
将configs/opensora/inference/16x512x512.py里的enable_flashattn=False。

**Comment by KLL535** [comment]
same issue
