### ISSUE TITLE
error of from mmengine.runner import set_random_seed

### ISSUE THREAD

**Issue by killnice66** [hpcaitech/Open-Sora#117]
![image](https://github.com/hpcaitech/Open-Sora/assets/74774674/f3470971-ad51-4d5e-8886-2ed4fb48fe63)
![image](https://github.com/hpcaitech/Open-Sora/assets/74774674/331c9ac4-ae9d-4c4d-a5dc-46144654e168)
here are the code I run from cli： torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path ./checkpoint/OpenSora-v1-HQ-16x512x512.pth

**Comment by zhengzangw** [comment]
Please try the latest version.

**Comment by Tianyu9748** [comment]
I also encounter an issue from mmengine.runner.
I tried the latest code. 
I cannot execute "from mmengine.runner import set_random_seed" in inference.py, but I can successfully import set_random_seed with an interactive python shell.

I have checked the python path, which is the same when I performed the previous 2 tests.
Has anyone encountered this issue before?
