### ISSUE TITLE
Missing keys: ['pos_embed', 'pos_embed_temporal']

### ISSUE THREAD

**Issue by happy-jing** [hpcaitech/Open-Sora#120]
[03/18/24 05:16:36] INFO     colossalai - colossalai - INFO:
                             /home/aiscuser/.conda/envs/opensora/lib/python3.10/site-packages/colossalai/initialize.py:6
                             7 launch
                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized, world size: 1
./pretrained_models/t5_ckpts/t5-v1_1-xxl
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:24<00:00, 12.07s/it]
Missing keys: ['pos_embed', 'pos_embed_temporal']
Unexpected keys: []

**Comment by happy-jing** [comment]
> What is the cuda version of your machine? I also encountered the same problem.

12.0

**Comment by QQQTAO** [comment]
> > What is the cuda version of your machine? I also encountered the same problem.
> 
> 12.0

I did not debug and ran it directly using the command. Have you debugged it?

**Comment by happy-jing** [comment]
> > > What is the cuda version of your machine? I also encountered the same problem.
> > 
> > 
> > 12.0
> 
> I did not debug and ran it directly using the command. Have you debugged it?

No. I ran it directly using the command too. I have no idea how to debug

**Comment by Jianrong-Lu** [comment]
The same Q. It drives me crazy! What a difficult project to reproduce!

**Comment by Jianrong-Lu** [comment]
> The same Q. It drives me crazy! What a difficult project to reproduce!

这个不是bug，代码里有输出Missing keys: ['pos_embed', 'pos_embed_temporal']的语句

**Comment by whk6688** [comment]
The same

**Comment by Michi-3000** [comment]
Have anyone solved this problem?

**Comment by whk6688** [comment]
> Have anyone solved this problem?

别看中文的介绍，他写错了。  看英文的

**Comment by jinhuaca** [comment]
Both the pos_emd are not learnable. Hence it is expected that they are not in the saved checkpoints.

**Comment by zhengzangw** [comment]
> [03/18/24 05:16:36] INFO colossalai - colossalai - INFO: /home/aiscuser/.conda/envs/opensora/lib/python3.10/site-packages/colossalai/initialize.py:6 7 launch INFO colossalai - colossalai - INFO: Distributed environment is initialized, world size: 1 ./pretrained_models/t5_ckpts/t5-v1_1-xxl Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:24<00:00, 12.07s/it] Missing keys: ['pos_embed', 'pos_embed_temporal'] Unexpected keys: []

No worry. This is not an error and is expected. So just ignore this.
