### ISSUE TITLE
Can it be installed under windows?

### ISSUE THREAD

**Issue by Datou** [hpcaitech/Open-Sora#121]
When I got to the last step of the installation, I got an error message saying that WSL is required.
![image](https://github.com/hpcaitech/Open-Sora/assets/15013/ea549dda-6cc8-4732-8414-07f01a315410)

**Comment by Yanjia0** [comment]
I think Colossal-AI currently only supports Linux environment, i you are using Windows and you do not have a server, maybe you can try to use Colab or something. Or just to fix this bug, try to use [WSL]( https://learn.microsoft.com/en-us/training/modules/wsl-introduction/)

**Comment by Datou** [comment]
> I think Colossal-AI currently only supports Linux environment, i you are using Windows and you do not have a server, maybe you can try to use Colab or something. Or just to fix this bug, try to use [WSL](https://learn.microsoft.com/en-us/training/modules/wsl-introduction/)

Thank you very much. I'll try installing it in WSL.

Is there any plan to make it compatible with Windows in the future? Many users are only familiar with Windows systems.

**Comment by Vikash3456** [comment]
This error message suggests that the package you're trying to install requires the Windows Subsystem for Linux (WSL) and is not supported directly on Windows. To resolve this, you'll need to install WSL on your Windows machine and run the installation within the WSL environment.

Additionally, if you're looking to contribute to the project or report this issue, you can do so on its GitHub repository. Providing details about your environment and the error message you encountered will help the developers address the issue more effectively.

**Comment by zhengzangw** [comment]
Switch to #205 for discussion.
