### ISSUE TITLE
[feat] Transformer quantization (bitsandbytes, AutoGPTQ and such)

### ISSUE THREAD

**Issue by kabachuha** [hpcaitech/Open-Sora#128]
As many lovers of local LLMs know, their raw (fp16) weights are hard to set up on a consumer PC. Luckily, there are some techniques enabling to quantize the weights to 4bits and even lower, making the models more accessible/being able to handle longer context with lower VRAM and faster speed.

Example project for transformers quantizing: https://github.com/AutoGPTQ/AutoGPTQ, huggingface's transformers support bitsandbytes quantization out of the box.

**Comment by zhengzangw** [comment]
This is cool. We will investigate it when we think our base model is good.
