### ISSUE TITLE
PixArt Sigma

### ISSUE THREAD

**Issue by ShawnFumo** [hpcaitech/Open-Sora#129]
Hey, just a suggestion: PixArt just released their Sigma paper, in which they upgraded their DiT model to 4k image resolution, improved prompt following, etc. They said they'll try their best to get the code and weights public before April 1st. Before you put too much more GPU time on training, it might be worth checking in with them (they have their own Discord) to see if using Sigma as a base would be helpful for the Open-Sora project.

https://pixart-alpha.github.io/PixArt-sigma-project/

**Comment by Sze-qq** [comment]
Hey ShawnFumo, thank you very much for your suggestion. We will definitely look into it!

**Comment by zhengzangw** [comment]
We will try to use it in our next version.
