### ISSUE TITLE
当我配置环境时出现如下问题，请问如何解决？

### ISSUE THREAD

**Issue by 1030zero** [hpcaitech/Open-Sora#136]
<img width="517" alt="pro" src="https://github.com/hpcaitech/Open-Sora/assets/142073348/f8d536da-8aa9-4c90-849f-39f5e69b41fe">

**Comment by LYK-love** [comment]
https://github.com/hpcaitech/Open-Sora/issues/134

**Comment by zhengzangw** [comment]
It takes a while to start the training, especially on multiple nodes.
