### ISSUE TITLE
能不能搞个好复用的东西，这样也好推广啊

### ISSUE THREAD

**Issue by cklogic** [hpcaitech/Open-Sora#137]
装完一堆环境之后，跑代码，发现还要去HG下模型，去HG下模型可以啊，您倒是写明了需要下载什么模型，放在什么路径，我不需要您在线下载，都知道什么原因。

**Comment by kamjin1996** [comment]
鉴定为就是个博眼球的东西

**Comment by zhengzangw** [comment]
Sorry for the unclear instructions for downloading the model weights. We have updated the README [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference).

To further ease your usage, we add auto-downloading to our code. Just run the following command, and the weight will be auto-downloaded.

```
torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path OpenSora-v1-HQ-16x512x512.pth --prompt-path ./assets/texts/t2v_samples.txt
```

**Comment by 1030zero** [comment]
> 抱歉，下载模型权限重的说明不明确。[我们已在此处](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference)更新了自述文件。
> 
> 为了进一步方便您的使用，我们在代码中添加了自动下载功能。只需运行以下命令，即可重新自动下载。
> 
> ```
> torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path OpenSora-v1-HQ-16x512x512.pth --prompt-path ./assets/texts/t2v_samples.txt
> ```

请问可以提供一个colab的页面么

**Comment by zhengzangw** [comment]
The huggingface demo is here: https://huggingface.co/spaces/hpcai-tech/open-sora
