### ISSUE TITLE
[bug] The client socket has failed to connect.

### ISSUE THREAD

**Issue by whysirier** [hpcaitech/Open-Sora#140]
![企业微信截图_20240319153059](https://github.com/hpcaitech/Open-Sora/assets/142364107/22e81f7d-ad11-4f4c-b162-4043eb3e4424)

**Comment by JThh** [comment]
Can you check with `telnet yanjiuzongyuan 54437` to see if the port is available?

**Comment by JThh** [comment]
Your command might have been obsolete due to our iterations. Use this instead: `# text to video
python scripts/inference.py configs/opensora-v1-1/inference/sample.py --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854`.
