### ISSUE TITLE
请问能否写清楚如何利用自己的输入做模型推理，没看明白doc

### ISSUE THREAD

**Issue by whysirier** [hpcaitech/Open-Sora#141]

**Comment by Sze-qq** [comment]
谢谢您的建议，我们稍后更新一下ReadMe :)

**Comment by ifredom** [comment]
> 谢谢您的建议，我们稍后更新一下ReadMe :)

Thanks to the scientists for their work. I am looking forward to giving the documentation, how should I deploy and use it as an ordinary developer?
I hope my 16g GPU can reason.

**Comment by zhengzangw** [comment]
Hi, we have updated the [readme](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference).

To change sampling prompts, modify the txt file passed to `--prompt-path`
