### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by xujin1184104394** [hpcaitech/Open-Sora#143]
报错，apex按照说明安装的，但是还是报了奇怪的错误
![image](https://github.com/hpcaitech/Open-Sora/assets/32417689/d45952f0-2c9a-4b4e-bc7b-105243bb535f)

**Comment by xujin1184104394** [comment]
补充：![image](https://github.com/hpcaitech/Open-Sora/assets/32417689/c125ddec-707b-48b0-bbcb-64203fbaedfb)

**Comment by AlphaNext** [comment]
> 看起来是apex的锅。我找到了解决办法，在apex库的issues中翻到了，[NVIDIA/apex#1737](https://github.com/NVIDIA/apex/issues/1737) 我的ubuntu系统是22.04，所以apex切换一个“22.04-dev”的分支，再安装就行了。

用22.04-dev分支还是报错，```enable_layernorm_kernel=False```也不管用。

另外直接```# text to video
python scripts/inference.py configs/opensora-v1-1/inference/sample.py \
    --ckpt-path CKPT_PATH --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854```
出现如下错误：
```
RuntimeError: Could not find 'LOCAL_RANK' in the torch environment, visit https://www.colossalai.org/ for more information on launching with torch
```

**Comment by lvalics** [comment]
A  configs/opensora-v1-1/inference/sample.py (python)  enable_layernorm_kernel=False                                                                                                       Row 7    Col 1
num_frames = 16
frame_interval = 3
fps = 24
image_size = (240, 426)
multi_resolution = "STDiT2"
enable_layernorm_kernel=False

python scripts/inference.py configs/opensora-v1-1/inference/sample.py --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854

Still ModuleNotFoundError: No module named 'fused_layer_norm_cuda' and also Apex is installed. :-(

**Comment by XavierCHEN34** [comment]
刚刚clone的，好像还是有这个错误

**Comment by yuvraj108c** [comment]
Yes, there is still this error
