### ISSUE TITLE
about recaption

### ISSUE THREAD

**Issue by qy-NJU** [hpcaitech/Open-Sora#145]
使用你提供的代码在2张A800上打caption，会出现超显存的情况，想问下你是怎么设置才能实现3s一个视频的

**Comment by ersanliqiao** [comment]
请问你跑出效果了吗

**Comment by ersanliqiao** [comment]
跑的是llava-v1.6-vicuna-7b还是34b?

**Comment by qy-NJU** [comment]
没呢，我现在把batch size设置成16能跑，不过要10s一个sample

--------------原始邮件--------------
发件人："ersan666 ***@***.***&gt;;
发送时间：2024年3月20日(星期三) 晚上8:26
收件人："hpcaitech/Open-Sora" ***@***.***&gt;;
抄送："钱烨 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [hpcaitech/Open-Sora] about recaption (Issue #145)
-----------------------------------

 

 
请问你跑出效果了吗

**Comment by ersanliqiao** [comment]
效果能出来吗，我跑llava-v1.6-vicuna-7b都是空结果，你跑的34b?

**Comment by ersanliqiao** [comment]
flash-attn装了吗

**Comment by ersanliqiao** [comment]
加我qq，771009283

**Comment by qy-NJU** [comment]
你的bs设置的32吗？

--------------原始邮件--------------
发件人："ersan666 ***@***.***&gt;;
发送时间：2024年3月20日(星期三) 晚上8:38
收件人："hpcaitech/Open-Sora" ***@***.***&gt;;
抄送："钱烨 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [hpcaitech/Open-Sora] about recaption (Issue #145)
-----------------------------------

 

 
你可能算错了，我跑20个视频，大概每个5s多，平均

**Comment by ersanliqiao** [comment]
没有，设置不了那么大，只有4，A100

**Comment by ersanliqiao** [comment]
4已经跑满显存了，你可以看看

**Comment by zhengzangw** [comment]
> 使用你提供的代码在2张A800上打caption，会出现超显存的情况，想问下你是怎么设置才能实现3s一个视频的

如果你的 A800 显存是 40G 的话，那确实可能会超。
