### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError

### ISSUE THREAD

**Issue by jiahao68** [hpcaitech/Open-Sora#146]
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './pretrained_models/t5_ckpts/t5-v1_1-xxl'. Use `repo_type` argument if needed.
I have set the folder "pretrained_models" into Open-Sora, why it happened?

**Comment by coolbei** [comment]
same problem

**Comment by yusijin02** [comment]
same problem

**Comment by zhengzangw** [comment]
Try pull the latest version. Now we use:

`from_pretrained="DeepFloyd/t5-v1_1-xxl"`
