### ISSUE TITLE
ValueError: mutable default <class 'colossalai.legacy.tensor.distspec._DistSpec'> for field dist_attr is not allowed: use default_factory

### ISSUE THREAD

**Issue by zhangbo2008** [hpcaitech/Open-Sora#148]
ValueError: mutable default <class 'colossalai.legacy.tensor.distspec._DistSpec'> for field dist_attr is not allowed: use default_factory

**Comment by yoghur** [comment]
> ValueError: mutable default <class 'colossalai.legacy.tensor.distspec._DistSpec'> for field dist_attr is not allowed: use default_factory

I solved this problem by using python 3.10 instead of 3.11

**Comment by ChrisYanY** [comment]
is there any other way to solve this

**Comment by yusijin02** [comment]
In this file:
```
XXXXXXXXXX/python3.12/site-packages/colossalai/legacy/tensor/tensor_spec.py
```
change:
```
from dataclasses import dataclass
```
to:
```
from dataclasses import dataclass, field
```

and, change:
```
dist_attr: Optional[_DistSpec] = _DistSpec(DistPlacementPattern.REPLICATE)
```
to:
```
dist_attr: Optional[_DistSpec] = field(default_factory=lambda: _DistSpec(DistPlacementPattern.REPLICATE))
```
