### ISSUE TITLE
Trade off between VQ-VAEs and VAEs

### ISSUE THREAD

**Issue by Red-Fairy** [hpcaitech/Open-Sora#158]
Dear authors,

Thanks for the great work!

While OpenAI's Sora itself and sota 3D VAEs (MAGVIT) uses the Vector Quantized (VQ-VAE) variant, open-sora adopts the KL-VAE. What's the rationale behind it and what could be the potential trade-off? Do you have any insight regarding this issue?

Thanks in advance!

**Comment by zhengzangw** [comment]
Currently, there is no high-quality off-the-shelf VQ-VAE. And thus we use a good KL-VAE for our training.

Besides, I did not see any report that Sora uses VQ-VAE. Could you help me check where is the information source?

**Comment by vincentWuK** [comment]
> Currently, there is no high-quality off-the-shelf VQ-VAE. And thus we use a good KL-VAE for our training.
> 
> Besides, I did not see any report that Sora uses VQ-VAE. Could you help me check where is the information source?

have you tried [VAR](https://github.com/FoundationVision/VAR)'s vqvae?
