### ISSUE TITLE
请问为什么生成的视频只有2s，这其中的主要限制是什么？

### ISSUE THREAD

**Issue by ChengChong001** [hpcaitech/Open-Sora#162]
请问为什么生成的视频只有2s，这其中的主要限制是什么？

**Comment by 1030zero** [comment]
可以提供几张效果图么，十分感谢！

**Comment by JThh** [comment]
You may adjust the `num_frames` and `fps` to control the output duration. See [here](https://github.com/hpcaitech/Open-Sora/blob/06507f744f9f7e5e8d300d9ae446bc8d351ed00c/configs/opensora/inference/64x512x512.py#L4) for an example.

**Comment by zhengzangw** [comment]
The main limitation is computing resources and data. We are now collecting more data to train a model that can generate longer videos.

**Comment by Get-David** [comment]
> You may adjust the `num_frames` and `fps` in the config file to control the output duration. See [here](https://github.com/hpcaitech/Open-Sora/blob/06507f744f9f7e5e8d300d9ae446bc8d351ed00c/configs/opensora/inference/64x512x512.py#L4) for an example.

我进行了一些尝试，但是当我修改`num_frames`时生成的视频都异常奇怪，只有大概前1～2s的视频看起来很正常。我改从哪方面进行调整呢？

**Comment by Get-David** [comment]
> The main limitation is computing resources and data. We are now collecting more data to train a model that can generate longer videos.

我想知道需要怎么调整训练方式才可以生成更长的视频，我注意到64*512*512，这是否意味着我可以生成8fps*8s的连续视频，而不是只有两秒的画面？可以说更多的细节吗，谢谢🙏

**Comment by zhengzangw** [comment]
v1.0 版本是不支持更长的视频的。可以使用 v1.1 的版本。
