### ISSUE TITLE
Wrong prompt for the last example on the gallery

### ISSUE THREAD

**Issue by wessm** [hpcaitech/Open-Sora#164]
On the gallery page (https://hpcaitech.github.io/Open-Sora/), the prompt for the last example is the same as for the sunflowers, although it should be something about "The dynamic movement of tall, wispy grass...".

**Comment by JThh** [comment]
Yes, you are right. To be clearer, it was referring to the example on the bottom-right corner with screenshot as shown below.
![Screenshot 2024-03-22 at 12 19 28](https://github.com/hpcaitech/Open-Sora/assets/59948448/392c8b3b-e2c2-449a-9e8b-34d8a1a62086)
