### ISSUE TITLE
训练时内存逐渐变大，最后被kill掉了

### ISSUE THREAD

**Issue by howardgriffin** [hpcaitech/Open-Sora#173]
训练16x512x512的，然后中途报错，错误如下：“RuntimeError: DataLoader worker (pid 3979007) is killed by signal: Killed. ”
查看内存直接爆掉了，一共1.8T的内存都爆了，咋搞？

**Comment by zhengzangw** [comment]
Try decrease the batch size to 1 and see if the problem still exists.

**Comment by langmanbusi** [comment]
同样的问题，在多卡训练时内存会持续增大，无论num_worker和batchsize设为多少都不行

**Comment by langmanbusi** [comment]
> Try decrease the batch size to 1 and see if the problem still exists.

同样的问题，在多卡训练时内存会持续增大，无论num_worker和batchsize设为多少都不行

**Comment by zhengzangw** [comment]
We did not find this problem during our setting. If this problem still exists, feel free to reopen this issue and please provide more information (such as environment and GPU used).

**Comment by chendy498** [comment]
zhe same,how much size do i need?

**Comment by zhengzangw** [comment]
Please see #480 for a detailed discussion.
