### ISSUE TITLE
where should i put model weight OpenSora-v1-16x256x256.pth?

### ISSUE THREAD

**Issue by BountyMage** [hpcaitech/Open-Sora#176]
where should i put this "model weights"? The actual file I downloaded is _OpenSora-v1-16x256x256.pth_
![image](https://github.com/hpcaitech/Open-Sora/assets/98575729/96251c4e-3c91-4251-8690-7c90dc776eba)

**Comment by yjdqk** [comment]
you can make a path by yourself  and put the weights to it .then ,just need to fix the config
