### ISSUE TITLE
谁可以给我发几张效果图啊，十分感谢！！！

### ISSUE THREAD

**Issue by 1030zero** [hpcaitech/Open-Sora#177]
配置的时候遇到了很多问题，但是又急需效果图，十分感谢！！

**Comment by minounou** [comment]
16x256x256的生成视频:

https://github.com/hpcaitech/Open-Sora/assets/163908077/859408d8-978e-4f2e-aa6d-a032aed3defe

**Comment by zhengzangw** [comment]
You can see more in our [gallery](https://hpcaitech.github.io/Open-Sora/)
