### ISSUE TITLE
使用双卡推理出现问题

### ISSUE THREAD

**Issue by tianbuwei** [hpcaitech/Open-Sora#178]
前提：并没有安装apex，但是设置了config中的enable_layernorm_kernel=False
启动命令：CUDA_VISIBLE_DEVICES=0,1 torchrun --standalone --nproc_per_node=gpu scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path /data1/tianhs/repositories/model/pretrained/hpcai-tech/Open-Sora/OpenSora-v1-HQ-16x512x512.pth --prompt-path /data1/tianhs/research/Open-Sora/assets/texts/t2v_samples.txt
报错信息：
![image](https://github.com/hpcaitech/Open-Sora/assets/88369405/12223c46-2ae9-4b58-ba58-e7b614d59ef8)

**Comment by zhengzangw** [comment]
@JThh Please try reproducing this issue.

**Comment by minounou** [comment]
您好！我现在用1块4090在16x512x512时依然有显存溢出的错误、如果您可以使用2块4090的请把配置和cli参数告诉我一下、谢谢！

**Comment by JThh** [comment]
How did you set `--nproc_per_node=gpu`? I cannot see where is the `gpu` defined and it is supposed to be a number that does not exceed 2. Other than that, I don't see any immediate issue. It is helpful to also test out other configs to see the issue persists. Allow us some time to replicate the bug, if possible.

**Comment by tianbuwei** [comment]
> How did you set `--nproc_per_node=gpu`? I cannot see where is the `gpu` defined and it is supposed to be a number that does not exceed 2. Other than that, I don't see any immediate issue. It is helpful to also test out other configs to see the issue persists. Allow us some time to replicate the bug, if possible.

您好，您的意思是没有指定特定的GPU吗？是要设置成 `--nproc_per_node=2`吗？您可以给出一个具体的双卡运行的命令吗
