### ISSUE TITLE
T5权重

### ISSUE THREAD

**Issue by fenglincong** [hpcaitech/Open-Sora#179]
![image](https://github.com/hpcaitech/Open-Sora/assets/90673560/29a729c4-7bbe-467d-afb0-05ebe213397b)
请问T5权重下载哪个呢？

**Comment by Sanfeixiao** [comment]
都下载，放到一个文件夹下面

**Comment by sbera7** [comment]
Please can you mention in which dir I have to put the T5 weights folder?

**Comment by zhengzangw** [comment]
Now we have added automatic downloading. You do not need to download by yourself.

**Comment by fenglincong** [comment]
> Now we have added automatic downloading. You do not need to download by yourself.

![image](https://github.com/hpcaitech/Open-Sora/assets/90673560/9cebc98d-d4e2-4b35-9717-cda921f42e93)

这是我前两天的t5路径，现在更新代码后又用不了，可以展示一下您这边的自动下载的话是保存到什么路径？
