### ISSUE TITLE
OSError: stabilityai/sd-vae-ft-ema does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by fenglincong** [hpcaitech/Open-Sora#181]
![image](https://github.com/hpcaitech/Open-Sora/assets/90673560/905146db-409c-4cfb-89b9-30857e89d5a6)
有人解决过这个问题吗？

**Comment by 297297297** [comment]
同问

**Comment by ShiinaMitsuki** [comment]
你好，你解决这个问题了吗

**Comment by fenglincong** [comment]
可以试试添环境变量
export HF_ENDPOINT="https://hf-mirror.com"

**Comment by ShiinaMitsuki** [comment]
> 可以试试添环境变量 export HF_ENDPOINT="https://hf-mirror.com"

感谢，原来是网络问题😂
