### ISSUE TITLE
caption_llava.py is not work

### ISSUE THREAD

**Issue by necrophagists** [hpcaitech/Open-Sora#182]
![image](https://github.com/hpcaitech/Open-Sora/assets/120618287/6a2b6237-c7c1-4f42-b918-a98aaf6ef8dd)

i change the llm to llava-v1.6-mistral-7b，but  model's output is empty。

**Comment by DwanZhang-AI** [comment]
So am I

**Comment by necrophagists** [comment]
> So am I

hi，i am already fix this problem. The code is right, the problem is the prompt['three frames'] is too long for mistral-7b (441 tokens). I changed  with a shorter prompt ("Please describe the video with one paragraph")，than it works.

**Comment by ersanliqiao** [comment]
can you give a example?

**Comment by ersanliqiao** [comment]
@necrophagists

**Comment by necrophagists** [comment]
> Please describe the video

try "Please describe the video."

**Comment by necrophagists** [comment]
> @necrophagists



> can you give a example?

try "Please describe the video"
