### ISSUE TITLE
请问把enable_flashattn设置为False会对效果有什么影响么？

### ISSUE THREAD

**Issue by dengdeng-cat** [hpcaitech/Open-Sora#183]
因为推理时报错：FlashAttention only supports Ampere GPUs or newer.
所以把enable_flashattn=False，请问这个参数有什么影响呢？会影响最终的效果么？谢谢！

**Comment by zhengzangw** [comment]
There will be no effects on performance. Just slower speed.

**Comment by dengdeng-cat** [comment]
> There will be no effects on performance. Just slower speed.

Thanks.
