### ISSUE TITLE
Can I train OpenSora using multiple 16GB V100 cards?

### ISSUE THREAD

**Issue by srdfjy** [hpcaitech/Open-Sora#187]
Hi

Can I train OpenSora using multiple 16GB V100 cards?

**Comment by zhengzangw** [comment]
Although you can by using sequence parallelism, I do not recommend you to do so. Maybe you can try something like LoRA. We will continue to work on it in the future version.

**Comment by Weixiang-Sun** [comment]
> Although you can by using sequence parallelism, I do not recommend you to do so. Maybe you can try something like LoRA. We will continue to work on it in the future version.

May I ask how much memory costs of continued training for each pre-trained model?
