### ISSUE TITLE
About the Implementation of Classifier-Free Guidance

### ISSUE THREAD

**Issue by jsttlgdkycy** [hpcaitech/Open-Sora#188]
https://github.com/hpcaitech/Open-Sora/blob/2361353844da516bc711720c0cd82989e1467769/opensora/schedulers/iddpm/__init__.py#L91
Since there are four channels in the latent space, I wonder why only the first three channels are selected to apply CFG. Is this a typo or something else?
Could someone tell me about this? I will be very appericated.

**Comment by gagan2125** [comment]
check once in,

Representation choice
Dimensionality reduction
Experimental design

if it is not solving means let me know 
i will give another solution

**Comment by jsttlgdkycy** [comment]
> check once in,
> 
> Representation choice Dimensionality reduction Experimental design
> 
> if it is not solving means let me know i will give another solution

Sorry could you please tell me where should I check these? Is there a more detailed report of this work?

**Comment by zhengzangw** [comment]
Thanks @jsttlgdkycy ! You read the code very carefully! We check the source of the code and find that both DiT and PixArt use the first 3 channels for classifier-free guidance.

https://github.com/facebookresearch/DiT/blob/ed81ce2229091fd4ecc9a223645f95cf379d582b/models.py#L258

https://github.com/PixArt-alpha/PixArt-alpha/blob/82c8559b7c11e2db47ab6d8fc0a5b5fa77f88f30/diffusion/model/nets/PixArt.py#L156

From DiT, they wrote: "For exact reproducibility reasons, we apply classifier-free guidance on only three channels by default. The standard approach to cfg applies it to all channels. This can be done by uncommenting the following line and commenting-out the line following that."

We tried on all channels and found the results make no much difference. Now by default we use all channels, and leave a `cfg_channels` to customize the channels you want to use.
