### ISSUE TITLE
OOM for 16x512x512 when bs is 8

### ISSUE THREAD

**Issue by canqin001** [hpcaitech/Open-Sora#203]
I noticed the default bs for 16x512x512 is 8 (https://github.com/hpcaitech/Open-Sora/blob/b4f47c8771b8b7d8036f5a2f6c9de5f65c2735a9/configs/opensora/train/16x512x512.py#L52) . But I can only run it with the bs as 2. I use the H100 with 80G for each GPU. Does anyone have similar problem? Thanks!

**Comment by zhengzangw** [comment]
We use H800 80G and it is ok. I think you can just decrease the batch size, for example, to 6, to run the inference.
