### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SoftologyPro** [hpcaitech/Open-Sora#205]
Cannot pip install colossalai under Windows.
Any work arounds to get Open-Sora working under Windows?

**Comment by zhengzangw** [comment]
@JThh Could you please have a check?

**Comment by JThh** [comment]
Would you please try installing `anaconda` on your Windows powershell? Try following [this guide](https://conda.io/projects/conda/en/latest/user-guide/install/windows.html).

After having it installed, you may create an environment using `conda create -n opensora python=3.11`, and in the project home folder, run `pip install -r requirements.txt`.

**Comment by liye007** [comment]
acturally it shows that  (Anaconda+windows)
raise RuntimeError("Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).")
  RuntimeError: Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).

**Comment by liye007** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，已经收到您的邮件，我会及时查看，谢谢

**Comment by nieyankai** [comment]
I've got the same error, is it mean that I have to use a linux vm

**Comment by liye007** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，已经收到您的邮件，我会及时查看，谢谢

**Comment by liye007** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，已经收到您的邮件，我会及时查看，谢谢

**Comment by tin2tin** [comment]
In 1.2, same problem on Win.

**Comment by zhengzangw** [comment]
> I've got the same error, is it mean that I have to use a linux VM

We do not have a plan to test on Windows. You request a contributor to do that for you, or you have to use it on linux.
