### ISSUE TITLE
please provide dockerfile and image and related script for reproduce.

### ISSUE THREAD

**Issue by ChengHSUHSU** [hpcaitech/Open-Sora#207]
Hi,

Everyone dev environment is different, it is very difficult to reproduce the project.
please provide dockerfile and image and related script for reproduce.

thanks

**Comment by zhengzangw** [comment]
We are working on it. There are some efforts from the community https://github.com/hpcaitech/Open-Sora/pull/159. You can have a look first.

**Comment by ChengHSUHSU** [comment]
thanks, it is workable
