### ISSUE TITLE
t5 path

### ISSUE THREAD

**Issue by JeffDing** [hpcaitech/Open-Sora#209]
if i use t5 model's absolute path in ```configs/opensora/inference/16x256x256.py``` 

it maybe have a error
```
from_pretrained in self.available_modelsAssertionError[2024-03-23 09:53:13,321] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0
```
bug if i use 'DeepFloyd/t5-v1_1-xxl' it will be download model then run nomaly

now i change ```opensora/models/text_encoder/t5.py``` file
```
#assert from_pretrained in self.available_models 
from_pretrained = "/root/Open-Sora/opensora/models/text_encoder/t5-v1_1-xxl"
```
It can be run with absolute path，is it have bug?

**Comment by zhengzangw** [comment]
To ease the usage of our model, we change the T5 to be automatically downloaded. You do not need to download the T5 weight first.

**Comment by wd1511** [comment]
in inference.py
from opensora.models.vae.vae import VideoAutoencoderKL
vae = VideoAutoencoderKL(from_pretrained=cfg.vae.from_pretrained)
