### ISSUE TITLE
Does the environment necessarily need to use CUDA version 12.1?

### ISSUE THREAD

**Issue by wd1511** [hpcaitech/Open-Sora#214]
The GPU driver version is 520.61.05 (supports up to CUDA 11.8). Can I configure the corresponding versions of torch and xformers? With the current configuration of torch=2.1.1+cu118 and xformers=0.0.22, and I get errors with xformers. 
![截屏2024-03-25 14 28 58](https://github.com/hpcaitech/Open-Sora/assets/26810029/ecd4552d-81c7-4f68-87f0-836b6872373f)
Is there any other solution besides updating the CUDA？
Additionally, is Apex optional or mandatory to install?

**Comment by geng-m** [comment]
as far as i known:
1. cuda-verison>=12.1
2. apex is mandatory

**Comment by agata28** [comment]
Tak

**Comment by wd1511** [comment]
> as far as i known:
> 
> 1. cuda-verison>=12.1
> 2. apex is mandatory

**Comment by tzayuan** [comment]
is xformers optional or mandatory for inference?

**Comment by Jiyang-Zheng** [comment]
Same problem here, can't update CUDA version due to lack of admin access, any solution to this issue?
