### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by wy91092** [hpcaitech/Open-Sora#215]
torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x256x256.py --ckpt-path ./pretrained_models/t5_ckpts/t5-v1_1-xxl --prompt-path ./assets/texts/t2v_samples.txt

show below error: 
![image](https://github.com/hpcaitech/Open-Sora/assets/6504892/f7688260-4ed8-4cc1-91aa-2bf5c7d3b65b)

![image](https://github.com/hpcaitech/Open-Sora/assets/6504892/8ec3733d-e60b-465d-86d7-1a5028e101c1)

**Comment by wy91092** [comment]
i add env in the scripts/inference.py , it still show error, does anyone encountered this?
![image](https://github.com/hpcaitech/Open-Sora/assets/6504892/4ce3e94c-bd7a-486b-9578-4b0abe380d4c)

**Comment by welloncn** [comment]
me too
![image](https://github.com/hpcaitech/Open-Sora/assets/4989505/ee115d24-32e2-4387-99eb-c9a678cfacd9)

**Comment by welloncn** [comment]
Have you solved it？

**Comment by idreamerhx** [comment]
on rtx3090  *1     run  demo.py caused oom    by    inference.py works   .

torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x256x256.py  --ckpt-path ckpt/OpenSora-v1-16x256x256.pth


speed:  4.33it/s

# gpu    pwr  gtemp  mtemp     sm    mem    enc    dec    jpg    ofa   mclk   pclk  pviol  tviol     fb   bar1  sbecc  dbecc    pci  rxpci  txpci
# Idx      W      C      C      %      %      %      %      %      %    MHz    MHz      %   bool     MB     MB   errs   errs   errs   MB/s   MB/s
    0    417     62      -    100     41      0      0      0      0   9501   1920      0      0  21432      7      -      -      0     24      7
    0    419     62      -    100     41      0      0      0      0   9501   1920      0      0  21432      7      -      -      0     25      7
    0    418     62      -    100     41      0      0      0      0   9501   1920      0      0  21432      7      -      -      0     24      7
