### ISSUE TITLE
内存不足

### ISSUE THREAD

**Issue by maxxxxyang** [hpcaitech/Open-Sora#216]
![image](https://github.com/hpcaitech/Open-Sora/assets/5063303/5790df01-3fef-40e6-861d-705f787cc6b3)
不好意思请问下 我用4张32G v100并行 但程序只用到了其中1张卡，导致内存不足，如何能够多卡并行推理呢

这是我的命令
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/64x512x512.py --ckpt-path ./OpenSora-v1-HQ-16x512x512.pth

**Comment by minounou** [comment]
same question: I have 2 nvidia-4090 and I set "CUDA_VISIBLE_DEVICES=0,1 torchrun ...", but it seems only the first 4090 is used, and I goto mem-error for 16x512x512 (16x256x256 is fine), if there is any solution for running inference on multiple GPUs please let us know Thanks!

**Comment by Pruokai** [comment]
修改--nproc_per_node参数
