### ISSUE TITLE
指定T5路径

### ISSUE THREAD

**Issue by fenglincong** [hpcaitech/Open-Sora#218]
T5模型是手动下载的，如何指定所在路径？

**Comment by Yanjia0** [comment]
可以看看这个回答[issue209](https://github.com/hpcaitech/Open-Sora/issues/209)

**Comment by yusijin02** [comment]
https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/configs/opensora/inference/16x256x256.py#L19-L23
改成
```
text_encoder = dict(
    type="t5",
    from_pretrained="path/to/your/model",
    model_max_length=120,
    local_cache=True,
)
```
注意，如果你的模型下载路径为`/home/xxx/model/t5-v1_1-xxl`, 在这里应该传入：`from_pretrained="/home/xxx/mode"`

**Comment by Get-David** [comment]
我遇到了同样的问题，但是我下载好以后路径变为
`
(base) zdw@ai-gpu-server149:/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37$ ls
`
config.json                       pytorch_model-00002-of-00002.bin  special_tokens_map.json  tokenizer_config.json
pytorch_model-00001-of-00002.bin  pytorch_model.bin.index.json      spiece.model
模型前面一定要是t5-v1_1-xxl这种格式吗？

**Comment by Get-David** [comment]
> https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/configs/opensora/inference/16x256x256.py#L19-L23
> 
> 
> 改成
> ```
> text_encoder = dict(
>     type="t5",
>     from_pretrained="path/to/your/model",
>     model_max_length=120,
>     local_cache=True,
> )
> ```
> 
> 注意，如果你的模型下载路径为, 在这里应该传入：`/home/xxx/model/t5-v1_1-xxl``from_pretrained="/home/xxx/model"`

我遇到了同样的问题，但是我下载好以后路径变为
`(base) david@ai-gpu:/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37$ ls`
config.json pytorch_model-00002-of-00002.bin special_tokens_map.json tokenizer_config.json
pytorch_model-00001-of-00002.bin pytorch_model.bin.index.json spiece.model
模型文件上一级一定是t5-v1_1-xxl这种命名吗？

**Comment by yusijin02** [comment]
> > https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/configs/opensora/inference/16x256x256.py#L19-L23
> > 
> > 改成
> > ```
> > text_encoder = dict(
> >     type="t5",
> >     from_pretrained="path/to/your/model",
> >     model_max_length=120,
> >     local_cache=True,
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注意，如果你的模型下载路径为, 在这里应该传入：`` /home/xxx/model/t5-v1_1-xxl``from_pretrained="/home/xxx/model" ``
> 
> 我遇到了同样的问题，但是我下载好以后路径变为 `(base) david@ai-gpu:/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37$ ls` config.json pytorch_model-00002-of-00002.bin special_tokens_map.json tokenizer_config.json pytorch_model-00001-of-00002.bin pytorch_model.bin.index.json spiece.model 模型文件上一级一定是t5-v1_1-xxl这种命名吗？

我觉得应该是的, 你可以手动将 `/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37` 移动到 `/data/huggingface/t5-v1_1-xxl` 目录下, 并删除 `/data/huggingface/t5-v1_1-xxl/snapshots` 目录, 或者将 `/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37` 目录重命名为 `t5-v1_1-xxl`.

总之, 代码中传入参数 `from_pretrained` 的目录下应当存在一个 `t5-v1_1-xxl` 子目录, 它会在 `t5-v1_1-xxl` 子目录中加载模型参数.

**Comment by Get-David** [comment]
> > > https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/configs/opensora/inference/16x256x256.py#L19-L23
> > > 
> > > 改成
> > > ```
> > > text_encoder = dict(
> > >     type="t5",
> > >     from_pretrained="path/to/your/model",
> > >     model_max_length=120,
> > >     local_cache=True,
> > > )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 注意，如果你的模型下载路径为, 在这里应该传入：` /home/xxx/model/t5-v1_1-xxl`from_pretrained="/home/xxx/model" ``
> > 
> > 
> > 我遇到了同样的问题，但是我下载好以后路径变为 `(base) david@ai-gpu:/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37$ ls` config.json pytorch_model-00002-of-00002.bin special_tokens_map.json tokenizer_config.json pytorch_model-00001-of-00002.bin pytorch_model.bin.index.json spiece.model 模型文件上一级一定是t5-v1_1-xxl这种命名吗？
> 
> 我觉得应该是的, 你可以手动将 `/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37` 移动到 `/data/huggingface/t5-v1_1-xxl` 目录下, 并删除 `/data/huggingface/t5-v1_1-xxl/snapshots` 目录, 或者将 `/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37` 目录重命名为 `t5-v1_1-xxl`.
> 
> 总之, 代码中传入参数 `from_pretrained` 的目录下应当存在一个 `t5-v1_1-xxl` 子目录, 它会在 `t5-v1_1-xxl` 子目录中加载模型参数.

这是我的模型文件路径
`
/home/xxx/Open-Sora/pre_training/t5-v1_1-xxl
`
例如
`
/home/xxx/Open-Sora/pre_training/t5-v1_1-xxl/pytorch_model-00001-of-00002.bin
`
配置文件是改成
`
text_encoder = dict(
    type="t5",
    from_pretrained="/home/zdw/Open-Sora/pre_training",
    model_max_length=120,
)`
依旧提示我
`OSError: Error no file named config.json found in directory /home/xxx/Open-Sora/pre_training.`

**Comment by Get-David** [comment]
> > > > https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/configs/opensora/inference/16x256x256.py#L19-L23
> > > > 
> > > > 改成
> > > > ```
> > > > text_encoder = dict(
> > > >     type="t5",
> > > >     from_pretrained="path/to/your/model",
> > > >     model_max_length=120,
> > > >     local_cache=True,
> > > > )
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 注意，如果你的模型下载路径为, 在这里应该传入：` /home/xxx/model/t5-v1_1-xxl`from_pretrained="/home/xxx/model" ``
> > > 
> > > 
> > > 我遇到了同样的问题，但是我下载好以后路径变为 `(base) david@ai-gpu:/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37$ ls` config.json pytorch_model-00002-of-00002.bin special_tokens_map.json tokenizer_config.json pytorch_model-00001-of-00002.bin pytorch_model.bin.index.json spiece.model 模型文件上一级一定是t5-v1_1-xxl这种命名吗？
> > 
> > 
> > 我觉得应该是的, 你可以手动将 `/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37` 移动到 `/data/huggingface/t5-v1_1-xxl` 目录下, 并删除 `/data/huggingface/t5-v1_1-xxl/snapshots` 目录, 或者将 `/data/huggingface/t5-v1_1-xxl/snapshots/c9c62f81d37` 目录重命名为 `t5-v1_1-xxl`.
> > 总之, 代码中传入参数 `from_pretrained` 的目录下应当存在一个 `t5-v1_1-xxl` 子目录, 它会在 `t5-v1_1-xxl` 子目录中加载模型参数.
> 
> 这是我的模型文件路径 `/home/xxx/Open-Sora/pre_training/t5-v1_1-xxl` 例如 `/home/xxx/Open-Sora/pre_training/t5-v1_1-xxl/pytorch_model-00001-of-00002.bin` 配置文件是改成
> 
> ```python
> text_encoder = dict(
>     type="t5",
>     from_pretrained="/home/xxx/Open-Sora/pre_training",
>     model_max_length=120,
> )
> ```
> 
> 依旧提示我 `OSError: Error no file named config.json found in directory /home/xxx/Open-Sora/pre_training.` 我将路径改为`/home/xxx/Open-Sora/pre_training/t5-v1_1-xxl`提示我 `AssertionError: assert from_pretrained in self.available_models`

我解决了这个问题，我注释了报错信息中的两个`assert`，并成功跑出了视频，这感觉很棒。谢谢你
