### ISSUE TITLE
OSError: Incorrect path_or_model_id: 'DeepFloyd/t5-v1_1-xxl/t5-v1_1-xxl'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

### ISSUE THREAD

**Issue by fenglincong** [hpcaitech/Open-Sora#219]
![image](https://github.com/hpcaitech/Open-Sora/assets/90673560/4ee4da2d-d992-470d-abb0-ae171b38d634)
代码是最新的，有人遇到这个问题吗？

**Comment by heming79** [comment]
pip install  huggingface-hub
export HF_ENDPOINT=https://hf-mirror.com
huggingface-cli download --resume-download DeepFloyd/t5-v1_1-xxl

**Comment by fenglincong** [comment]
> pip install huggingface-hub export HF_ENDPOINT=https://hf-mirror.com huggingface-cli download --resume-download DeepFloyd/t5-v1_1-xxl
按照这个方法下载了，在~/.cache/huggingface/hub/models--DeepFloyd--t5-v1_1-xxl目录下，但是依然报错上述错误

**Comment by yusijin02** [comment]
参考我的回答：https://github.com/hpcaitech/Open-Sora/issues/218#issuecomment-2022057971
