### ISSUE TITLE
为什么要在推理时复制一份latent进行推理，可以移除吗？

### ISSUE THREAD

**Issue by yusijin02** [hpcaitech/Open-Sora#225]
在进行推理时：
为什么要先做
https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/schedulers/iddpm/__init__.py#L66
再做
https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/schedulers/iddpm/__init__.py#L83
手动移除有什么弊端吗？

**Comment by yusijin02** [comment]
我留意到`y_null`的引入：
https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/schedulers/iddpm/__init__.py#L69
但是在样本级别的拼接为什么会影响输出样本？

**Comment by Katerina0926** [comment]
你好 请问你有成功训练并推理出预期视频吗 可以交流一下吗 QQ1335190384

**Comment by ictzyqq** [comment]
> 我留意到`y_null`的引入：
> 
> https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/schedulers/iddpm/__init__.py#L69
> 
> 
> 但是在样本级别的拼接为什么会影响输出样本？

涉及到classifier-free guidance(cfg)的相关知识，你可以参考下[链接](https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/schedulers/iddpm/__init__.py#L87)中的forward_with_cfg函数，包含了样本间输出的融合
