### ISSUE TITLE
推理过程bug

### ISSUE THREAD

**Issue by fenglincong** [hpcaitech/Open-Sora#226]
推理过程中：代码不经过stdit.py或者dit.py中的forward函数，vae.py的decoder函数，（断点停不下来，print打印不出来测试内容），这是bug吗？

**Comment by yusijin02** [comment]
你能正确输出视频吗？我用16x256x256推理经过dit的这个forward函数：
https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/models/stdit/stdit.py#L215

**Comment by fenglincong** [comment]
> 你能正确输出视频吗？我用16x256x256推理经过dit的这个forward函数：
> 
> https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/models/stdit/stdit.py#L215

我也是16x256x256，能正常生成视频，但是不经过dit的forward函数，都不知道它是咋推理的

**Comment by yusijin02** [comment]
> > 你能正确输出视频吗？我用16x256x256推理经过dit的这个forward函数：
> > https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/models/stdit/stdit.py#L215
> 
> 我也是16x256x256，能正常生成视频，但是不经过dit的forward函数，都不知道它是咋推理的

断点调试逐步进内层吧，能出视频肯定是有正常进forward了，只是不一定是你看的那个

**Comment by fenglincong** [comment]
> > > 你能正确输出视频吗？我用16x256x256推理经过dit的这个forward函数：
> > > https://github.com/hpcaitech/Open-Sora/blob/a37a189482a4cd1c7892aa06881e539cbf8078ce/opensora/models/stdit/stdit.py#L215
> > 
> > 
> > 我也是16x256x256，能正常生成视频，但是不经过dit的forward函数，都不知道它是咋推理的
> 
> 断点调试逐步进内层吧，能出视频肯定是有正常进forward了，只是不一定是你看的那个

torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py --ckpt-path ./ckpt/OpenSora-v1-HQ-16x512x512.pth --prompt-path ./assets/texts/t2v_samples.txt --batch-size 1我执行的是这个脚本，dit，stdit中所以的forward都停不下来，评论区有遇到过的吗？
![image](https://github.com/hpcaitech/Open-Sora/assets/90673560/42263ced-c58f-46f7-8c79-b37244afdfe4)
