### ISSUE TITLE
How to inference with provided weights as the auto download failed

### ISSUE THREAD

**Issue by Caixy1113** [hpcaitech/Open-Sora#230]
Hi，Im confused that how should I organize all the model weight to inference？Should I download all this model(model,vae,text_encoder) and set the "from_pretrained" as my path?
`# Define model
model = dict(
    type="STDiT-XL/2",
    space_scale=0.5,
    time_scale=1.0,
    enable_flashattn=True,
    enable_layernorm_kernel=True,
    from_pretrained="PRETRAINED_MODEL",
)
vae = dict(
    type="VideoAutoencoderKL",
    from_pretrained="stabilityai/sd-vae-ft-ema",
    micro_batch_size=4,
)
text_encoder = dict(
    type="t5",
    from_pretrained="DeepFloyd/t5-v1_1-xxl",
    model_max_length=120,
)
scheduler = dict(
    type="iddpm",
    num_sampling_steps=100,
    cfg_scale=7.0,
    cfg_channel=3, # or None
)`

**Comment by yusijin02** [comment]
You don't need to modify the configuration, the weights will be automatically downloaded. 
Of course, you can also manually download the model weights an change the parameters in `from_pretrained` to your path. Note that that there seems to be some issues when changing `text_encoder` to a local absolute path. Refer to my answer for seeking a solution: https://github.com/hpcaitech/Open-Sora/issues/218#issuecomment-2022057971
