### ISSUE TITLE
运行 demo.py 脚本时遇到了错误。错误信息如下： 

### ISSUE THREAD

**Issue by FlowersWithoutMoon** [hpcaitech/Open-Sora#236]
完整信息见TXT

[(opensora)运行错误.txt](https://github.com/hpcaitech/Open-Sora/files/14797333/opensora.txt)
1threadblock_1_1RegularTileIterator_3_01Shape___00_01Element___00_0bc37beaa523707a55987f4ffcc372fcd.html: Filename too long
  fatal: Unable to checkout 'bbe579a9e3beb6ea6626d9227ec32d0dae119a49' in submodule path 'third_party/flash-attention/csrc/cutlass'
  fatal: Failed to recurse into submodule path 'third_party/flash-attention'
  error: subprocess-exited-with-error

  × git submodule update --init --recursive -q did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: git submodule update --init --recursive -q
  cwd: C:\Users\Sailner\AppData\Local\Temp\pip-install-c8_9cx6_\xformers_8013c1475f6a40849043c00c9623f0b6
error: subprocess-exited-with-error

× git submodule update --init --recursive -q did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Collecting git+https://github.com/hpcaitech/Open-Sora.git
  Cloning https://github.com/hpcaitech/Open-Sora.git to c:\users\sailner\appdata\local\temp\pip-req-build-p3vaz2_4
  Running command git clone --filter=blob:none --quiet https://github.com/hpcaitech/Open-Sora.git 'C:\Users\Sailner\AppData\Local\Temp\pip-req-build-p3vaz2_4'
  Resolved https://github.com/hpcaitech/Open-Sora.git to commit 554358a4fa4dfd1f9c0cb92b67e0b8d440103009
  Preparing metadata (setup.py) ... done
Collecting colossalai (from opensora==1.0.0)
  Using cached colossalai-0.3.6.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sailner\AppData\Local\Temp\pip-install-sms6vmsp\colossalai_114c661552014b25a3eabccc5508e90c\setup.py", line 20, in <module>
          raise RuntimeError("Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).")
      RuntimeError: Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "D:\Software\Git\dates\Open-Sora\Open-Sora\scripts\demo.py", line 254, in <module>
    main()
  File "D:\Software\Git\dates\Open-Sora\Open-Sora\scripts\demo.py", line 186, in main
    vae, text_encoder, stdit, scheduler = build_models(args.model_type, config)
  File "D:\Software\Git\dates\Open-Sora\Open-Sora\scripts\demo.py", line 106, in build_models
    from opensora.registry import MODELS, build_module
ModuleNotFoundError: No module named 'opensora'

**Comment by yusijin02** [comment]
跟着readme中的指引安装环境，特别是
```
pip install -v .
```

**Comment by 1030zero** [comment]
> 跟着readme中的引导安装环境，特别是
> 
> ```
> pip install -v .
> ```
![image](https://github.com/hpcaitech/Open-Sora/assets/142073348/af60e078-50d8-4e94-a076-7fef1675da62)
我在colab中配置环境运行demo.py出现以上错误，请问这个可以解决么？

**Comment by yusijin02** [comment]
> > 跟着readme中的引导安装环境，特别是
> > ```
> > pip install -v .
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/142073348/318192825-af60e078-50d8-4e94-a076-7fef1675da62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NTQ5NjUsIm5iZiI6MTcxMTg1NDY2NSwicGF0aCI6Ii8xNDIwNzMzNDgvMzE4MTkyODI1LWFmNjBlMDc4LTUwZDgtNGU5NC1hMDc2LTdmZWYxNjc1ZGE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQwMzExMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWE4YTEyNmMxYzc2MGQwYzIxYTkyNzlhNmFmMDY3NjI3M2UzNDdhNjIzYjViMjE2ZTE1MDE1YTljZDA3OWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aw6AYg8ko7f0kkIe2lk4iEpxEovbhTCxupIlWbG_Mxw) 我在colab中配置环境运行demo.py出现以上错误，请问这个可以解决么？

你这个是显存炸了啊, 看截图最下面那行. 要么更换更大显存的GPU, 或改为多卡; 要么使用半精、降低bs等方法降低显存要求

**Comment by ChenzRoy** [comment]
用linux系统，windows系统不支持
