### ISSUE TITLE
have any plans to release larger pre-trained models in the near future, such as 64x512x512 or 360x512x512? 

### ISSUE THREAD

**Issue by xiexiaoshinick** [hpcaitech/Open-Sora#240]
Dear Open_Sora Team,

First of all, I would like to express my sincere gratitude for your excellent open-source video generation project. Recently, I have been using the 16x512x512 and 16x256x256 pre-trained models provided by you and fine-tuned them on my own dataset, achieving outstanding results. Your project has made a significant contribution to the field of video generation, and I truly appreciate and congratulate you for your efforts.

I would like to inquire if you have any plans to release larger pre-trained models in the near future, such as 64x512x512 or 360x512x512? I believe that these higher-resolution pre-trained models would bring better performance and experience for video generation tasks. If possible, our community would be immensely grateful.

Regardless, I would like to express my admiration for your outstanding work once again and wish your project even greater success! Please continue to maintain your innovative and open spirit.

Looking forward to your reply!

**Comment by freshcoffee22** [comment]
Hi! Could you kindly share how you managed to execute this code? We are specifically looking to perform video inference and intend to utilize the pre-trained model checkpoints directly, bypassing the training phase. Any detailed guidance you could provide would be greatly appreciated. Thank you very much!
