### ISSUE TITLE
实验室安全，人人有责

### ISSUE THREAD

**Issue by wangszh1987** [hpcaitech/Open-Sora#245]
【视频开头】

（镜头缓缓推进，展示实验室环境）

旁白：“大家好，欢迎来到今天的实验室安全视频。在这个充满神秘与奇迹的实验室里，安全是我们最重要的准则。”

【第一部分：实验室基本安全规则】

（展示实验室的防护装备，如实验服、护目镜、手套等）

旁白：“首先，我们要了解实验室的基本安全规则。在进入实验室前，请确保穿戴好所有的防护装备，保护我们的眼睛、皮肤和衣物免受化学物质的伤害。”

（展示实验室的禁止事项，如禁止饮食、禁止吸烟等）

旁白：“在实验室里，请务必遵守禁止事项。禁止饮食和吸烟，以免将有害物质带入体内。同时，不要随意触碰或摆弄实验室设备，以免发生意外。”

【第二部分：化学品的正确使用和存储】

（展示化学品标签和安全数据表）

旁白：“化学品是实验室中不可或缺的一部分，但它们的危险性也不容忽视。请务必仔细阅读化学品的标签和安全数据表，了解它们的性质、用途和安全操作方法。”

（展示化学品储存柜和正确存储方法）

旁白：“化学品的存储也是至关重要的。请将化学品存放在指定的储存柜中，远离火源和热源。同时，要注意分类存放，避免不同化学品之间的化学反应。”

【第三部分：实验设备的操作规范】

（展示实验设备的操作过程）

旁白：“实验设备的操作规范同样不可忽视。在操作前，请确保了解设备的使用说明和安全操作规程。在操作过程中，要保持专注和谨慎，避免发生误操作或意外。”

【结尾部分】

（镜头拉远，展示整个实验室）

旁白：“实验室安全，人人有责。让我们共同努力，营造一个安全、和谐、高效的实验室环境。感谢大家的观看，祝大家实验顺利，安全无忧！”

**Comment by Edenzzzz** [comment]
? Please do not post spam
