### ISSUE TITLE
请问模型在本地下载好了，如何加载？

### ISSUE THREAD

**Issue by fancyicookie** [hpcaitech/Open-Sora#253]
因为从hugging上自动下载总是会因为网络问题出错，所以自主下载了传入text encoder和vae这两个模型，下载好之后代码里如何加入这两个模型？

**Comment by zhengzangw** [comment]
抱歉我们之前没考虑到用户自主下载的问题。作用一个临时解决方案，huggingface from_pretrained 能支持 cache_dir 这个参数。在 `opensora/models/vae/vae.py` 和 `opensora/models/text_encoder/t5.py` 中找到 `from_pretrained`，将其中 `cache_dir` 更换为你的本地文件夹。这个本地文件夹的组织方式应该和 huggingface 的 `.cache` 一致。具体而言：
<img width="942" alt="Screenshot 2024-04-15 at 00 26 29" src="https://github.com/hpcaitech/Open-Sora/assets/30647653/46d49bd0-acf6-4955-ba60-ca0399a8033b">

```bash
> ls models--DeepFloyd--t5-v1_1-xxl
blobs  refs  snapshots
```

**Comment by JJun-Guo** [comment]
> 抱歉我们之前没考虑到用户自主下载的问题。作用一个临时解决方案，huggingface from_pretrained 能支持 cache_dir 这个参数。在 `opensora/models/vae/vae.py` 和 `opensora/models/text_encoder/t5.py` 中找到 `from_pretrained`，将其中 `cache_dir` 更换为你的本地文件夹。这个本地文件夹的组织方式应该和 huggingface 的 `.cache` 一致。具体而言： <img alt="Screenshot 2024-04-15 at 00 26 29" width="942" src="https://private-user-images.githubusercontent.com/30647653/322287996-46d49bd0-acf6-4955-ba60-ca0399a8033b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2MTUwODYsIm5iZiI6MTczNzYxNDc4NiwicGF0aCI6Ii8zMDY0NzY1My8zMjIyODc5OTYtNDZkNDliZDAtYWNmNi00OTU1LWJhNjAtY2EwMzk5YTgwMzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIzVDA2NDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOGY1OGNmMzU1OWQ5NTA1NDk4OTBlOWZlZDI3ZmQwZTE5Y2ZiZTkwMzE4NzNlNWVmY2QxOTEyNjZjMzEzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xPz11fVcn-EYyblJwnzy8HiKHiFT6WVta5fSXMz-7jw">
> 
> > ls models--DeepFloyd--t5-v1_1-xxl
> blobs  refs  snapshots

请问在1.2版本中如何修改configs/opensora-v1-2/inference/sample.py，加载本地下载好的模型。
