### ISSUE TITLE
Better temporal representation

### ISSUE THREAD

**Issue by ElliottDyson** [hpcaitech/Open-Sora#255]
It is my belief that a temporal attention block which has a finer time resolution for most recent images and coarser time resolution for the oldest may help the model in achieving better time domain representation, longer video generation, and/or be more compute efficient.

The theory is that as more frames are generated, the older frames become more and more coarse, dropping more frames the further back in the sequence they are, so that we focus the context of the model on the most recent frames as those are most important for noticeable temporal coherency, but still maintain some temporal information no matter the length of generation in order to maintain some form of global context.
Whilst it may require reworking the architecture somewhat due to the notion of dropping older frames, I believe such a process could be highly valuable.

Something else that should help if you are not doing so already, is holding a cache of the sine and cosine embeddings that are used in RoPE for each sequence length encountered (a key may be used for accessing the correct cache), as the creation of these for each time the forward pass is called is a considerable slow down for long sequence lengths.
I have an implementation if you don't already have one and would like to use it.

On a last note, I was wondering if any experiments have been taken in transitioning feedforward and/or attention linear layers from fp16/32 to that from the 1.58bits paper (https://arxiv.org/abs/2402.17764) and as to what activation function you are currently utilising?

I would love to hear your thoughts on my ideas.

Many thanks,
-Elliott

**Comment by ElliottDyson** [comment]
My apologies, I could have (and have now) easily checked what activation function you are using an approximation of GELU using the hyperbolic tangent function. 

May I suggest the usage of Mish(), as it has the same benefits of GELU (non monatomic, derivative at 0, close to linear above 0, totally continuous), except it is also more computationally efficient, and even closer to linear above 0 than even GELU.

You may have also heard of the Swish function, but I have found Mish to be more performant, and from the paper at least, better than Swish for the datasets they used to test the LLM they used with it. I have had very good experience with the function on audio data classification tasks too, so it certainly isn't limited to language tasks (which should be expected, but I thought it was worth pointing out).

So I believe it at the very least is worth investigating. I do understand however that you are currently waiting on more funding.

**Comment by 23Rj20** [comment]
hey did you do this on windows system or linux??

**Comment by ElliottDyson** [comment]
> hey did you do this on windows system or linux??
> 
> 

Both
