### ISSUE TITLE
The generated videos are shaking and unstable.

### ISSUE THREAD

**Issue by nankepan** [hpcaitech/Open-Sora#267]
I trained a stdit model with webvid. The generated videos are shaking and unstable. Can you give me some reasons or suggestions？Is there some training tricks?

https://github.com/hpcaitech/Open-Sora/assets/82510548/57a06b2f-6dc4-4752-af4d-9f10625ba4e9

https://github.com/hpcaitech/Open-Sora/assets/82510548/5906d127-e874-442e-bdd9-fa563502d5f5

https://github.com/hpcaitech/Open-Sora/assets/82510548/49c48e82-ba2b-4748-9b26-5346ca4f0524

**Comment by liiiiiiiiil** [comment]
same problem

**Comment by zhengzangw** [comment]
Although we did not try Webvid dataset, I suppose it is because your number of training steps is too small. Could you share how many number of steps have you run?

**Comment by nankepan** [comment]
> Although we did not try Webvid dataset, I suppose it is because your number of training steps is too small. Could you share how many number of steps have you run?

Thanks for your reply! 26k iterations with 32 batchsize on 72 A100 gpus. So the total iterations is about 60m.

**Comment by zhengzangw** [comment]
It seems you use a very large batch size (32x72). A think although the passed number of data is the same, you still need enough iterations to get a good result. If you continue the training, you will see the generated video to have better quality.
