### ISSUE TITLE
checkpoint会开源吗？

### ISSUE THREAD

**Issue by whh2333** [hpcaitech/Open-Sora#27]
大佬好，请问您训练的checkpoint会开源吗？

**Comment by binmakeswell** [comment]
Hi @whh2333 目前开源的复现方案和系统优化等，权重和demo等会稍晚提供，欢迎大家持续关注和参与贡献，感谢。

**Comment by zhiyixu** [comment]
麻烦问下如果自行训练模型的话需要什么样的硬件资源？

**Comment by binmakeswell** [comment]
> 麻烦问下如果自行训练模型的话需要什么样的硬件资源？

单台8卡A800 H800就可以，只是比较慢。与选取的模型大小和数据量也强相关。

**Comment by guijuzhejiang** [comment]
> > 麻烦问下如果自行训练模型的话需要什么样的硬件资源？
> 
> 单台8卡A800 H800就可以，只是比较慢。与选取的模型大小和数据量也强相关。
看样子，24G显卡完全不行吧。选取模型是指compressor的["raw", "vqvae", "vae"]吗？

**Comment by fakerhbj** [comment]
> > 麻烦问下如果自行训练模型的话需要什么样的硬件资源？
> 
> 单台8卡A800 H800就可以，只是比较慢。与选取的模型大小和数据量也强相关。

>请问四卡A6000行吗

**Comment by zhengzangw** [comment]
We have open-sourced our checkpoints [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#model-weights).
