### ISSUE TITLE
train error with exitcode: -4

### ISSUE THREAD

**Issue by tiancaitzp** [hpcaitech/Open-Sora#271]
The base model and dataset are loaded successfully, when training start, it will get error after a few seconds. The error is as follow:

![15F53272B8CE1AE9365CCCFD4E693355](https://github.com/hpcaitech/Open-Sora/assets/51696454/fcd448a5-b74b-45bd-8ea4-1fa70f9830d1)

**Comment by JThh** [comment]
May I know your command for training? Have you changed all lines in your training codes?

**Comment by tiancaitzp** [comment]
command: torchrun --nnodes=1 --nproc_per_node=1 scripts/train.py configs/opensora/train/16x256x256.py --data-path /home/tanzhipeng/open-sora/Open-Sora/datasets/travel.csv

changes in code :
![image](https://github.com/hpcaitech/Open-Sora/assets/51696454/ac820ffd-6ea8-4938-8e5d-c2d70904988e)

**Comment by JThh** [comment]
May I know why you set `use_reentrant = True`? It might be not recommended when there are nested modules ([link](https://pytorch.org/docs/stable/checkpoint.html)).

**Comment by tiancaitzp** [comment]
When I set use_reentant = False，I got the same error.
![image](https://github.com/hpcaitech/Open-Sora/assets/51696454/e7fb3427-f0e5-4a87-90f6-78daa8b76096)
![image](https://github.com/hpcaitech/Open-Sora/assets/51696454/74540705-36fb-4be8-975a-0571f2f30613)

**Comment by JThh** [comment]
May I know your outputs of `nvidia-smi`? The error codes of `-4` are often flagged with Out-Of-Memory (OOM) issue.

**Comment by tiancaitzp** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/51696454/20f36281-a494-4735-a0ac-e95e826c1233)
![image](https://github.com/hpcaitech/Open-Sora/assets/51696454/16bb1cd0-ec1a-465d-b065-dba2d30761ce)

**Comment by tiancaitzp** [comment]
> May I know your outputs of `nvidia-smi`? The error codes of `-4` are often flagged with Out-Of-Memory (OOM) issue.

Hi, is there any update about this issue?

**Comment by FrankLeeeee** [comment]
Can you @tiancaitzp , can you try  it again with `export CUDA_LAUNCH_BLOCKING=1`? It might raise more specific errors.

**Comment by zhengzangw** [comment]
Your code modification seems correct.

**Comment by zhengzangw** [comment]
Please try OpenSora 1.2. If the problem still exists, feel free to re-open.
