### ISSUE TITLE
Thoughts on Audio2Video

### ISSUE THREAD

**Issue by fire17** [hpcaitech/Open-Sora#275]
Hi there :)
I'm sure you're familiar with the recent Emo demo which takes image+audio and turns it to a consistent video (head) amazing quality

I've just heard a demo of Udio - Braking Bad The Musical
https://youtu.be/13M-FFkXVvs?t=5m53s
If you close your eyes you can practically see the Disney movie in your head

So in the future I see a pipeline of audio+text to video, where the vid is consistent with with audio and the text describe the scene, characters, and their actions and motions

After that there will be a Boximator style editing or rerendering parts of the video using text prompt or maybe even a video reference.

**Comment by zhengzangw** [comment]
Thanks for your suggestion. Currently, audio support is not one of our priorities. We hope to reach Sora-level video generation quality first.

**Comment by fire17** [comment]
Hey yo ! 👋🏾 
How's it coming along ? 
All the best!
