### ISSUE TITLE
Thoughts on streaming

### ISSUE THREAD

**Issue by fire17** [hpcaitech/Open-Sora#276]
Hi there :)

In the future I see many pipelines, any2video, audio+text+image2video

But am wondering about the ability to instead of prerendeing everything, to optimize for realtime streaming, continueing frames, and being able to alter the prompt as the video is generating. Something like realtime SD with last frame being a reference.

Then to achieve SOTA quality, stream to an upscaler, and character/obj consistency layers.

**Comment by zhengzangw** [comment]
Thanks for your thoughts. We are working hard on what you have thought. Hope everything goes well and the new model can meet you soon.
