### ISSUE TITLE
使用HD-VG-130M数据集训练的模型效果非常不好

### ISSUE THREAD

**Issue by kawayi12318** [hpcaitech/Open-Sora#277]
https://github.com/hpcaitech/Open-Sora/assets/107163121/e5848a0a-5f2f-4c8f-b493-836ad352729e

以上是我使用少量数据集训练的模型 生成的视频 
我想知道是因为数据太少么

**Comment by zhengzangw** [comment]
根据你生成的视频效果（基本全是噪声），虽然不知道你具体的训练步数和数据量，我认为问题可能在于：
1. 你没有使用 PixArt-alpha 的图像模型进行初始化权重。使用预训练好的图像模型初始化权重，能够加速学习过程。
2. 如果你想从头训练，那可能是你训练的步数太少了。一般 10k 能够见到效果。

**Comment by kawayi12318** [comment]
> 根据你生成的视频效果（基本全是噪声），虽然不知道你具体的训练步数和数据量，我认为问题可能在于：
> 
> 1. 你没有使用 PixArt-alpha 的图像模型进行初始化权重。使用预训练好的图像模型初始化权重，能够加速学习过程。
> 2. 如果你想从头训练，那可能是你训练的步数太少了。一般 10k 能够见到效果。

我看到open-sora的global_step计算公式为：global_step = epoch * num_steps_per_epoch + step
这个num_steps_per_epoch 值会受到batch_size影响
请问你说的在10k step左右可以见到效果 是在batch_size值是多少的情况下

**Comment by songyang86** [comment]
@kawayi12318 请问怎么使用yt-dlp命令下载HD-VG-130M数据集

**Comment by kawayi12318** [comment]
> @kawayi12318 请问怎么使用yt-dlp命令下载HD-VG-130M数据集

我在谷歌云盘中下载的[HD-VG-130M](https://drive.google.com/drive/folders/154S6raNg9NpDGQRlRhhAaYcAx5xq1Ok8?usp=sharing) 使用的是 metafiles目录下的 hdvg_0.json

**Comment by songyang86** [comment]
@kawayi12318 请问怎么修改extract_all_clip这个方法，我不清楚怎么用youtube-dl下载，谢谢

**Comment by kawayi12318** [comment]
> @kawayi12318 请问怎么修改extract_all_clip这个方法，我不清楚怎么用youtube-dl下载，谢谢

@songyang86 你可以直接使用我的脚本：
[cut_videos_hdvg - 副本.txt](https://github.com/hpcaitech/Open-Sora/files/15021996/cut_videos_hdvg.-.txt)
我不会在讨论中上传python脚本 所以我更改了后缀 你在使用时需要将后缀改为**.py** 并放到**data/HD-VG-130M/**下

**Comment by songyang86** [comment]
@kawayi12318 你好，我运行的程序，报这个错误：
FileNotFoundError: [Errno 2] No such file or directory: 'yt-dlp -f "bv[ext=mp4]+ba[ext=m4a]" --embed-metadata --merge-output-format mp4 -o "/home/song/diffusion/Open-Sora-main/HDdata/download_videos/----meyKR48.mp4" https://www.youtube.com/watch?v=----meyKR48 '

**Comment by kawayi12318** [comment]
> @kawayi12318 你好，我运行你的程序，报这个错误： FileNotFoundError: [Errno 2] No such file or directory: 'yt-dlp -f "bv[ext=mp4]+ba[ext=m4a]" --embed-metadata --merge-output-format mp4 -o "/home/song/diffusion/Open-Sora-main/HDdata/download_videos/----meyKR48.mp4" https://www.youtube.com/watch?v=----meyKR48 '

你有装ffmpeg和yt-dlp吗

**Comment by songyang86** [comment]
@kawayi12318 我已经安装了，还是同样的错误
![Screenshot from 2024-04-18 17-32-55](https://github.com/hpcaitech/Open-Sora/assets/13955731/2852213d-6fe4-4b54-a562-fe0f536c68f2)

**Comment by kawayi12318** [comment]
> @kawayi12318 我已经安装了，还是同样的错误，VPN我是打开的 ![Screenshot from 2024-04-18 17-32-55](https://private-user-images.githubusercontent.com/13955731/323548551-2852213d-6fe4-4b54-a562-fe0f536c68f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzMyNjIsIm5iZiI6MTcxMzQzMjk2MiwicGF0aCI6Ii8xMzk1NTczMS8zMjM1NDg1NTEtMjg1MjIxM2QtNmZlNC00YjU0LWE1NjItZmUwZjUzNmM2OGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5MzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZmY2MjI0ZGJlZjJkYzUyOWRhNWUyMGU0MTM1YTQxYTgzYjE1MTI4NTlkMjVkNTc1NGU2Nzg1ZTdiYzA3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uLvldFN_QJmzR9-QXX3NASoHvca3JDsT6BvYweB62-U)

yt-dlp 不是youtube-dl

**Comment by kawayi12318** [comment]
> @kawayi12318 麻烦你了，我实在不知道错在哪里，谢谢 ![Screenshot from 2024-04-18 17-52-23](https://private-user-images.githubusercontent.com/13955731/323554617-d123f89b-60b4-470b-8454-16f7fa648847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzQ0ODYsIm5iZiI6MTcxMzQzNDE4NiwicGF0aCI6Ii8xMzk1NTczMS8zMjM1NTQ2MTctZDEyM2Y4OWItNjBiNC00NzBiLTg0NTQtMTZmN2ZhNjQ4ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwY2Q3NjJlODFkNWQzNjMwM2M5Yjc3ODU4YTljYjcyMDlkZDgyYjkyNTE3NTljN2Q5YzA3NTAzMzFmNDExODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOqMSsAyo-s7TQ1pMF_qoqMIhsUC8Y8AwDRPT5hUX90)

在你的data/HD-VG-130M下是不是没有download_videos这个目录啊

**Comment by kawayi12318** [comment]
> @kawayi12318 麻烦你了，我实在不知道错在哪里，谢谢 ![Screenshot from 2024-04-18 17-52-23](https://private-user-images.githubusercontent.com/13955731/323554617-d123f89b-60b4-470b-8454-16f7fa648847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzQ5NDQsIm5iZiI6MTcxMzQzNDY0NCwicGF0aCI6Ii8xMzk1NTczMS8zMjM1NTQ2MTctZDEyM2Y4OWItNjBiNC00NzBiLTg0NTQtMTZmN2ZhNjQ4ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEwMDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMzkzNTBjMDljMTM4YjIyNTExOGQ1NDM5MmRkMTlhNTI4Y2ExOWIwNTA4MGI2MDliNjhlY2EwNTg2OTcwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.63W3u4JdTAZ3msdmhvrAYWadDqL4ciRey2_ua2YqREc)

我也没看出来 你有更完整的日志记录吗？

**Comment by kawayi12318** [comment]
> @kawayi12318 麻烦你了，我实在不知道错在哪里，谢谢 ![Screenshot from 2024-04-18 17-52-23](https://private-user-images.githubusercontent.com/13955731/323554617-d123f89b-60b4-470b-8454-16f7fa648847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzUwNjYsIm5iZiI6MTcxMzQzNDc2NiwicGF0aCI6Ii8xMzk1NTczMS8zMjM1NTQ2MTctZDEyM2Y4OWItNjBiNC00NzBiLTg0NTQtMTZmN2ZhNjQ4ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEwMDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NzhmOWQ3MGI5YmVlNmUzZGRmNTdjNDNjMzBhNDQyMGZjMmY0NjRhYzQ1ZWRkOWUzZWVlZjMyYjcyZjljN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCJuHqyydWiglVQnCr-THcw8fKk96TfBzDDFsES7Cno)

我认为应该是你的ffmpeg或者yt-dlp没有安装好 你可以搜一下安装教程

**Comment by songyang86** [comment]
@kawayi12318 我的目录上有这个download文件夹，我在终端单独运行   yt-dlp -f "bv[ext=mp4]+ba[ext=m4a]" --embed-metadata --merge-output-format mp4 -o "./download_videos/----meyKR48.mp4" https://www.youtube.com/watch?v=----meyKR48  这个命令是可以正常下载视频的，很奇怪。你这个文件是在windows上还是ubuntu上运行的
![Screenshot from 2024-04-18 18-04-55](https://github.com/hpcaitech/Open-Sora/assets/13955731/b65520cf-6ba3-49d8-9661-5b20a763cc5f)

**Comment by kawayi12318** [comment]
> @kawayi12318 我的目录上有这个download文件夹，我在终端单独运行 yt-dlp -f "bv[ext=mp4]+ba[ext=m4a]" --embed-metadata --merge-output-format mp4 -o "./download_videos/----meyKR48.mp4" https://www.youtube.com/watch?v=----meyKR48 这个命令是可以正常下载视频的，很奇怪。你这个文件是在windows上还是ubuntu上运行的 ![Screenshot from 2024-04-18 18-04-55](https://private-user-images.githubusercontent.com/13955731/323559423-b65520cf-6ba3-49d8-9661-5b20a763cc5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzUyNzEsIm5iZiI6MTcxMzQzNDk3MSwicGF0aCI6Ii8xMzk1NTczMS8zMjM1NTk0MjMtYjY1NTIwY2YtNmJhMy00OWQ4LTk2NjEtNWIyMGE3NjNjYzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEwMDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NmViYTQxOTYzMDQ0YzQyNTYxYWU0ZWE0MzQ2ODc5NmNjY2IzODU3NTQ3ZGRkODRkMGNhZjRkYWIwMzUwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7sQM3DXN4VDqADBN77CIeHo2quJdYIhzD0-ALRzNw_o)


windows

**Comment by songyang86** [comment]
@kawayi12318 可以了，要把shell设置为True。非常感谢你的帮助

**Comment by kawayi12318** [comment]
> @kawayi12318 可以了，要把shell设置为True。非常感谢你的帮助


@songyang86  我在代码中有设置下载视频数量 在171-172行
 `if i >= 1000:
     break`
如果你需要下载全部的视频 你需要注释掉这两行

**Comment by songyang86** [comment]
@kawayi12318 你的这段程序有点问题：
![1](https://github.com/hpcaitech/Open-Sora/assets/13955731/6ed6a8b6-2add-48e1-a82f-bee650a50e1e)

下载程序里面的 video_id此时是----meyKR48，但实际下载的时候估计是分片下载，所以保存的视频是video_id加上一个随机编码对视频进行的命名。所以 程序的  if not os.path.exists(video_temp_path) 永远是True，导致保存的csv文件是空的
![2](https://github.com/hpcaitech/Open-Sora/assets/13955731/0d6c7b80-1d2b-498d-8846-4a989cd8072f)


不知道你下载的时候是否有这个问题？

**Comment by songyang86** [comment]
@kawayi12318 
![4](https://github.com/hpcaitech/Open-Sora/assets/13955731/df246208-23be-48bd-8a5f-79e2dc748783)

我这样改有问题吗？我目前现在下载10个video_id做测试，但最终发现download_videos文件夹里面没有合成最终的视频

**Comment by songyang86** [comment]
@kawayi12318 cnt我设置成2，程序运行完是这样的：
![5](https://github.com/hpcaitech/Open-Sora/assets/13955731/0b3ff425-0efd-4880-880a-57efde5b5e74)

**Comment by kawayi12318** [comment]
> @kawayi12318 ![4](https://private-user-images.githubusercontent.com/13955731/323854115-df246208-23be-48bd-8a5f-79e2dc748783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDg3MDUsIm5iZiI6MTcxMzUwODQwNSwicGF0aCI6Ii8xMzk1NTczMS8zMjM4NTQxMTUtZGYyNDYyMDgtMjNiZS00OGJkLThhNWYtNzllMmRjNzQ4NzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMjIwNzM4ZmYxNGQxODRjNTAyZjFjNTgzYTVhNTJkZjgyMjY0NzZlMTI1MzY0YmY4Yjc0YTYzODg3Y2ZlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRtrPM2GWiOJxEZZ_TO1v-gs_WZ3FDPPWFoDS3EyYDw)
> 
> 我这样改有问题吗？我目前现在下载10个video_id做测试，但最终发现download_videos文件夹里面没有合成最终的视频

首先 如果你需要限制下载视频的数量 你只需要更改为i >= 10 并不需要添加额外判断cut < 10 例如
![image](https://github.com/hpcaitech/Open-Sora/assets/107163121/3e52e116-52ed-474c-8d11-7ff52a8ea6a5)

其次你的代码看起来并没有什么问题 你是怎么运行它的呢

**Comment by kawayi12318** [comment]
@songyang86 
另外你还需要在脚本中添加以下代码 
`os.environ["http_proxy"] = "http://127.0.0.1:9999"
os.environ["https_proxy"] = "http://127.0.0.1:9999"
os.environ["OPENCV_FFMPEG_READ_ATTEMPTS"] = '4096'`

9999对应的是你vpn的端口号

**Comment by kawayi12318** [comment]
@songyang86 
首先我的目录结构为：
![image](https://github.com/hpcaitech/Open-Sora/assets/107163121/99d340d1-28fc-4fff-801e-c55c6d356c7f)

在运行脚本对两个视频做处理后为：
![image](https://github.com/hpcaitech/Open-Sora/assets/107163121/fca4d323-1ab9-4ee6-9368-4b7df9407b0e)

download-videos目录下为合并完成的视频：
![image](https://github.com/hpcaitech/Open-Sora/assets/107163121/db49899b-b5c3-48b3-bf28-1941775938d2)

video-clips目录下为切分好后的视频片段：
![image](https://github.com/hpcaitech/Open-Sora/assets/107163121/a16e4e95-aa42-4ab3-ba5b-3e5a0b31bb3b)

**Comment by songyang86** [comment]
@kawayi12318 我知道问题了，我目前是在windows上用pycharm运行的，可以直接运行你的程序。昨天是在ubuntu上运行的，一直报错，后来发现要将shell设置为True才能正常运行。我看了，在ubuntu上是可以正常合成的，感谢

**Comment by songyang86** [comment]
@kawayi12318 windows上shell为False，可以正常下载，但无法合成
