### ISSUE TITLE
有关数据集和数据集csv文件的问题

### ISSUE THREAD

**Issue by WayneML** [hpcaitech/Open-Sora#278]
小白刚入门dl，上手的第一个项目，rz问题勿喷。看文档不是很明白。
如果我想直接用生成的视频或者网络上的一些短视频来用作训练的数据，我该怎么做csv文件，是否要把视频先拆成一帧一帧，然后对应的编写csv文档。
另外，那个csv文件的格式，是一个视频拆成十几个帧，每帧对应一个image1 ，image2 ，image3 这样吗？ 然后 caption 对于一个视频的所有image都是一样的吗，还是每个image都有不同的caption？后面的nums of frames. 是对应的这个帧是第几帧吗， 还是这个视频的总帧数？
应该是很入门的问题，大佬勿喷。感谢有人回答。

**Comment by WayneML** [comment]
如果是一个视频拆成十几帧的话，是不是必须按照顺序来，不能打乱？

**Comment by WayneML** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/114311625/f16d0f8f-8624-4e5b-b8c1-65070466e5b2)
疑惑点来源

**Comment by zhengzangw** [comment]
抱歉文档不全给你带来的困扰。在下一个版本中，我们会带来更全的数据处理流程和文档。

你对数据的 csv 文件可能有一定的误解。在数据的 csv 文件中，一行代表的就是一个样本。如果你训练的是图片模型，那么就可以是一个 .jpg 路径（如你的截图所示）。目前看你训练的是短视频，那路径只需要是到你每个视频文件的路径（/path/to/your/video.mp4）。和拆帧没有关系。

**Comment by songyang86** [comment]
@zhengzangw 请问如何根据metafile文件中的json文件下载HD-VG-130M数据集

**Comment by zhengzangw** [comment]
可以参考 HD-VG-130M 的官方 repo: https://github.com/daooshee/HD-VG-130M
