### ISSUE TITLE
A new high-quality video-text dataset 新的高质量视频文本数据集

### ISSUE THREAD

**Issue by mutonix** [hpcaitech/Open-Sora#281]
We recently open-sourced a new fine-grained video-text dataset with 12K annotated high-resolution videos (~400k clips), called [Vript](https://github.com/mutonix/Vript), which may contribute to improving the open-sora models.

<p align="center">
<img src="https://github.com/mutonix/Vript/blob/main/assets/Vript-overview_00.png?raw=true" width="600">
</p>

GitHub link: https://github.com/mutonix/Vript

**Comment by zhengzangw** [comment]
received with thanks. We will try to use it in our next release.
