### ISSUE TITLE
Loss question

### ISSUE THREAD

**Issue by nankepan** [hpcaitech/Open-Sora#286]
![image](https://github.com/hpcaitech/Open-Sora/assets/82510548/f4af888f-879c-4831-96aa-9b32dc6c93d9)
Hi, 
I've noticed that for most of your training time,  loss doesn't decrease. Why continue training when the loss no longer decreases？Does this help improve the model's performance? Would it be possible to achieve similar performance with less training time/iteration?

**Comment by zhengzangw** [comment]
For DDPM, the loss is almost the same. This is widely observed for image generation tasks. However, the model keeps improving as the training continues.
