### ISSUE TITLE
Frame数量对训练有哪些影响呢？

### ISSUE THREAD

**Issue by AlphaNext** [hpcaitech/Open-Sora#287]
感谢你的工作，请问Frame数量对训练有哪些影响呢？看load视频部分的代码，训练的视频不管多少帧都采样成16帧，另外如果想生成稍微长点的视频（比如：10s），除了资源问题是首要问题，还有哪些需要注意的地方呢？

**Comment by Zeldalina** [comment]
同问

**Comment by TheMattBin** [comment]
I guess it might affect the results as basically it provides more sampling for training

**Comment by zhengzangw** [comment]
主要是资源。训练长的视频意味着需要更大的内存，相同时间过的视频数量也少了。
