### ISSUE TITLE
python gradio/app.py --port 8001 --host 0.0.0.0 --enable-optimization --model-type v1-HQ-16x512x512  一直报torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by yangjianchun** [hpcaitech/Open-Sora#288]
显卡A100 40G
python gradio/app.py --port 8001 --host 0.0.0.0 --enable-optimization --model-type v1-HQ-16x512x512 执行后出现torch.cuda.OutOfMemoryError: CUDA out of memory，

但是在命令行下执行CUDA_VISIBLE_DEVICES=1 torchrun --standalone --nproc_per_node 1 scripts/inference.py configs/opensora/inference/16x512x512.py  又没问题，python gradio/app.py  是哪里配置问题吗

**Comment by JThh** [comment]
You may try replacing the Boolean values from [this line](https://github.com/hpcaitech/Open-Sora/blob/81982f60c42fa9e864dce669ea9d97552820125b/gradio/app.py#L104) and [this line](https://github.com/hpcaitech/Open-Sora/blob/81982f60c42fa9e864dce669ea9d97552820125b/gradio/app.py#L105) with `args.enable_optimization`.

**Comment by yangjianchun** [comment]
> the
还是一样，还是显示显存溢出，有没还有其他优化方式？
