### ISSUE TITLE
[Bug Report] in the captioning code annotated with Llava.

### ISSUE THREAD

**Issue by Phoenix1327** [hpcaitech/Open-Sora#289]
In line 260 of the code https://github.com/hpcaitech/Open-Sora/blob/main/tools/caption/caption_llava.py, only one < image > token is added to the prompt, which will result in only one replacement when making LLM input, using only the first frame of multiple frames to replace the < image > token.
For details, please refer to line 117.
<img width="557" alt="image" src="https://github.com/hpcaitech/Open-Sora/assets/13741561/3a486553-979b-4d34-a2df-924064de92d4">
It can be seen that if there is only one < image > token in the prompt, num images = 1.
Then, in line 142~ line 156, only one image feature replacement is performed, and only the first frame data is used.
<img width="577" alt="image" src="https://github.com/hpcaitech/Open-Sora/assets/13741561/f5032fba-56b8-437b-80fa-52a5fcff74b8">

In addition, the `image_aspect_ratio` parameter in the` model_config` is recommended to be set to "None". The default "asynres" is to be compatible with frames of different resolutions. But the frames are extracted from the same video, and the resolutions are the same. Setting it to "None" will avoid additional padding operations and reduce the length of the input prompt.

**Comment by valencebond** [comment]
have the same problem

**Comment by zhengzangw** [comment]
We have fixed this bug:
