### ISSUE TITLE
Access to huggingface vqvae

### ISSUE THREAD

**Issue by quantumiracle** [hpcaitech/Open-Sora#29]
Thanks for open-sourcing this incredible repo!

I found that if specifying 'vqvae' for --compressor argument in `train.py`, it requires access to the pretrained model on Huggingface. Could you please provide the access to that model?

Best

**Comment by binmakeswell** [comment]
Hi @quantumiracle We've opened it. Thanks. 
https://huggingface.co/hpcai-tech/vqvae
