### ISSUE TITLE
Can this model predict the next frame of the video?

### ISSUE THREAD

**Issue by freshcoffee22** [hpcaitech/Open-Sora#290]

**Comment by xuhyun11** [comment]
Can open-sora model be utilized to predict or generate the next frame of a video based on preceding frames?
If so, could you please provide guidance on how to implement this in programming?
If direct prediction and generation of the subsequent video frame are not feasible, I would like to know how to craft cue words or prompts to assist in predicting and generating the next frame of the video.

**Comment by zhengzangw** [comment]
We do not focus on predicting the next frame as we can generate all frames in one time. However, you can use the video extending method in OpenSora V1.1 to exdent the video.

**Comment by zhengzangw** [comment]
Just use a mask that only adds noise to the last frame.
