### ISSUE TITLE
运行演示数据集的问题

### ISSUE THREAD

**Issue by akira822** [hpcaitech/Open-Sora#291]
当我运行UCF101数据集的时候，是下载完数据集运行
`python -m tools.datasets.convert_dataset ucf101 UCF101_FOLDER --split videos`
但是它运行完显示0样例处理，生成的CSV文件也是空的，我想问一下是需要的下载后的数据集进行预处理吗？

**Comment by akira822** [comment]
UCF101它的字幕是需要按照流程生成吗？

**Comment by akira822** [comment]
![屏幕截图 2024-04-21 173357](https://github.com/hpcaitech/Open-Sora/assets/167678125/309e52a2-926a-4cbf-8e72-f975f10ec9de)

这个CSV文件的格式的意思一行是路径，描述，帧数

**Comment by zhengzangw** [comment]
Please try with the latest `datautil.py`. You can just use `video` arguments instead of `ucf101`.
