### ISSUE TITLE
caption_llava.py to caption videos. Only use 1 frame?

### ISSUE THREAD

**Issue by QiaoZhennn** [hpcaitech/Open-Sora#303]
1. In readme it says it will use 3 frames to run caption.  
2. But the example cmd in readme uses num_frames = 1 and prompt = image_3ex, which means using 1 frame per video?
3. About default args in main function, it uses prompt = video_1f_3ex, which means also using 1 frame per video?

**Comment by yumlevi** [comment]
How are you hoping to generate a caption that describes the spatial and temporal features of a clip using 1 frame?

**Comment by zhengzangw** [comment]
For datasets already with captions (e.g., Panda-70M), we directly use it. 1 frame caption can achieve good results for short videos.
