### ISSUE TITLE
Could you please provide the information about the source of the image data?

### ISSUE THREAD

**Issue by suilin0432** [hpcaitech/Open-Sora#312]
Hi~, thank you for your great work. I'd like to try reproducing your method, but I noticed that you used 2.6M+1.6M images during the training process. I've read through the documentation you provided, but I couldn't find the source of the images. Therefore, I'd like to ask about the source of the training images you used. If it's convenient for you, I'd appreciate it if you could clarify this for me. Thanks!

**Comment by zhengzangw** [comment]
updated here. https://github.com/hpcaitech/Open-Sora/blob/main/docs/datasets.md

**Comment by suilin0432** [comment]
Thanks a lot~
