### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by fuchao01** [hpcaitech/Open-Sora#317]
720p 16s,9:16,在A100 80G显存跑报OOM，这个尺寸需要多显卡推理吗？

**Comment by fuchao01** [comment]
补充下，我使用拉fash attn但没有用apex

**Comment by zhengzangw** [comment]
Cannot do 720p 16s on 80G GPU. Try 2s 720p, or 16s 240p

**Comment by fuchao01** [comment]
用什么方法能跑下720,16s的视频？

**Comment by zhengzangw** [comment]
代码暂时不支持 sp，所以暂时没法跑。

**Comment by canqin001** [comment]
Hi @zhengzangw ，请问720p支持的最长frames是多少？我在80G GPU上试了16 frames，720x1280，会OOM
