### ISSUE TITLE
我运行python scripts/inference.py configs/opensora-v1-1/inference/sample-ref.py    --ckpt-path OpenSora-STDiT-v2-stage2/model.safetensors --prompt-path assets/texts/t2i_samples.txt --num-frames 1 --image-size 1024 1024

### ISSUE THREAD

**Issue by huluMessi** [hpcaitech/Open-Sora#320]
非常给力的工作。
我运行python scripts/inference.py configs/opensora-v1-1/inference/sample.py    --ckpt-path OpenSora-STDiT-v2-stage2/model.safetensors --prompt-path assets/texts/t2i_samples.txt --num-frames 1 --image-size 1024 1024 
发现一个错误
ValueError: Invalid checkpoint path: OpenSora-STDiT-v2-stage2/model.safetensors
我需要怎么配置运行 --ckpt-path呢？
python scripts/inference.py configs/opensora-v1-1/inference/sample.py --ckpt-path /workspace/i2v/Open-Sora/OpenSora-STDiT-v2-stage3/model.safetensors --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854
运行这个也是一样

**Comment by zhengzangw** [comment]
目前已经支持自动下载了。
