### ISSUE TITLE
Multiple model log paths

### ISSUE THREAD

**Issue by COST-97** [hpcaitech/Open-Sora#321]
Hello:
When training on several GPUs, it seems that one model will generate multiple model log paths. `booster` doesn't support generating only one model log now?

**Comment by zhengzangw** [comment]
Do multiple model log paths mean creating multiple log dirs? If that is the case, you can add `dist.barrier()` at the following place as a workaround. A patch will be given in the next release.

https://github.com/hpcaitech/Open-Sora/blob/c6cc021d612456455addc1b3164c1d43eeb33b97/opensora/utils/config_utils.py#L155
