### ISSUE TITLE
opensora/utils/ckpt_utils.py does not have OpenSora 1.1 in pretrained_models

### ISSUE THREAD

**Issue by boringlee24** [hpcaitech/Open-Sora#322]
How do we specify the --ckpt-path argument to run the inference script for opensora 1.1?

**Comment by FangGet** [comment]
for all who want to load opensora 1.1 model, please just add the following lines into https://github.com/hpcaitech/Open-Sora/blob/e836befc0810c627413fdb8abd400e10b00c9eac/opensora/utils/ckpt_utils.py#L264

    elif ckpt_path.endswith(".safetensors"):
        from safetensors.torch import load_file
        state_dict = load_file(ckpt_path)
        missing_keys, unexpected_keys = model.load_state_dict(state_dict, strict=False)
        print(f"Missing keys: {missing_keys}")
        print(f"Unexpected keys: {unexpected_keys}")

**Comment by boringlee24** [comment]
> for all who want to load opensora 1.1 model, please just add the following lines into
> 
> https://github.com/hpcaitech/Open-Sora/blob/e836befc0810c627413fdb8abd400e10b00c9eac/opensora/utils/ckpt_utils.py#L264
> 
> ```
> elif ckpt_path.endswith(".safetensors"):
>     from safetensors.torch import load_file
>     state_dict = load_file(ckpt_path)
>     missing_keys, unexpected_keys = model.load_state_dict(state_dict, strict=False)
>     print(f"Missing keys: {missing_keys}")
>     print(f"Unexpected keys: {unexpected_keys}")
> ```

Thank you, works now

**Comment by zhengzangw** [comment]
We have added now.
