### ISSUE TITLE
使用从头训练的模型生成的视频画面一致性较差

### ISSUE THREAD

**Issue by kawayi12318** [hpcaitech/Open-Sora#323]
https://github.com/hpcaitech/Open-Sora/assets/107163121/4e0a321d-4afc-416f-b3c1-2d125472df8a

使用数据集：HD-VG-130M
step：136500
batch_size：1

请问这是什么原因？

**Comment by lanson07** [comment]
Hi~
Which model did you use for inference？

**Comment by kawayi12318** [comment]
> Hi~ Which model did you use for inference？

I trained the model

**Comment by zhengzangw** [comment]
你用单卡训练，global batch size 是 1 吗？这样的话过的数据还是太少了，而且 batch size 太小，最后模型的效果也可能不够理想。
