### ISSUE TITLE
the generation speed of opensora-1.1 is much slower than 1.0 version with similar quatlity

### ISSUE THREAD

**Issue by ThisisBillhe** [hpcaitech/Open-Sora#328]
I tested on V100 32G, without flashattention. For 1.0, the generation speed can reach 3.4 it/s. For 1.1 version, it's 1.5 it/s. What operation slow down that speed?

**Comment by zhengzangw** [comment]
The generation speed should be similar. Did you generate a longer video or a higher resolution?
