### ISSUE TITLE
RuntimeError: "layer_norm_cuda_kernel" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by lanson07** [hpcaitech/Open-Sora#329]
When i run inference with A100 GPUs, i encountered following bug：RuntimeError: "layer_norm_cuda_kernel" not implemented for 'BFloat16'

I'm looking forward to your reply

**Comment by zhengzangw** [comment]
I think this is because the apex is not correctly installed. I think you can turn off the `enable_fused_layernorm` in the config file.
