### ISSUE TITLE
可以在Windows上或者在没有GPU的Linux上使用吗？

### ISSUE THREAD

**Issue by shengrihui** [hpcaitech/Open-Sora#330]
我想在自己的 Windows 设备上运行，这可以吗？

如果不可以，那不使用 GPU （也就是没有 GPU 的 Linux 设备）上可以吗？

**Comment by nieyankai** [comment]
windows上编译报错，我搞了一天终于在wsl Ubuntu上整通过了，过程中还有别的问题，编译Apex时候记得export MAX_JOBS=4

**Comment by zhengzangw** [comment]
目前暂时没有支持 Windows。如果是没有 GPU 的设备，可能要手动调整一下依赖。
