### ISSUE TITLE
the text2video result of 1.1 is  worse than 1.0 

### ISSUE THREAD

**Issue by seeyourcell** [hpcaitech/Open-Sora#332]
【1.1 version】
I use the gradio/app.py  
prompt:     # prompt_text = "A bustling city street at night, filled with the glow of car headlights and the ambient light of streetlights. The scene is a blur of motion, with cars speeding by and pedestrians navigating the crosswalks. The cityscape is a mix of towering buildings and illuminated signs, creating a vibrant and dynamic atmosphere. The perspective of the video is from a high angle, providing a bird's eye view of the street and its surroundings. The overall style of the video is dynamic and energetic, capturing the essence of urban life at night."

I use the same prompt ，with version 1.0 , I find 1.1 is worse than 1.0 
=========
    length = "8s"
    mode = "Text2Video"
    aspect_ratio = "9:16"
    sampling_steps =100
    cfg_scale = 7.0

**Comment by zhengzangw** [comment]
We identify the issue. The problem is that we apply qk-norm before applying position encoding. Thus, when we generate longer video (more than 2s), the image quality deteriorates. We will fix this in the next release.

**Comment by Mr-Harry** [comment]
> 我们发现了这个问题。问题在于我们在应用位置编码之前应用了 qk-norm。因此，当我们生成较长的视频（超过 2 秒）时，图像质量会下降。我们将在下一个版本中修复此问题。

这个修复了吗
