### ISSUE TITLE
DiT 在 1.1 版本推理出错

### ISSUE THREAD

**Issue by songh11** [hpcaitech/Open-Sora#333]
报错信息：
RuntimeError: Error(s) in loading state_dict for DiT:
        size mismatch for x_embedder.proj.weight: copying a param with shape torch.Size([1152, 4, 2, 2]) from checkpoint, the shape in current model is torch.Size([1152, 4, 1, 2, 2]).

**Comment by zhengzangw** [comment]
We do not reproduce this error. You should use automatic downloading for DiT weight. Otherwise, you need manually do something like:

https://github.com/hpcaitech/Open-Sora/blob/c6cc021d612456455addc1b3164c1d43eeb33b97/opensora/utils/ckpt_utils.py#L39
