### ISSUE TITLE
error~麻烦看一下

### ISSUE THREAD

**Issue by findlyhl** [hpcaitech/Open-Sora#34]
FileNotFoundError: [Errno 2] No such file or directory: '/root/miniconda3/lib/python3.10/site-packages/colossalai/kernel/extensions/csrc/cuda/cpu_adam.cpp'

这是服务器的信息：Linux  #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

找不到这个模块:ModuleNotFoundError: No module named 'colossalai._C.cpu_adam_x86'

**Comment by allenxcp** [comment]
Requirements:

    PyTorch >= 1.11 and PyTorch <= 2.1
    Python >= 3.7
    CUDA >= 11.0
    [NVIDIA GPU Compute Capability](https://developer.nvidia.com/cuda-gpus) >= 7.0 (V100/RTX20 and higher)
    Linux OS

git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI

# install colossalai
BUILD_EXT=1 pip install .

**Comment by ver217** [comment]
I've update requirements. Can you try the latest code?

**Comment by allenxcp** [comment]
最好把 requirements 中每个具体版本写清楚吧，搞环境太累了，只能猜和试

**Comment by zhengzangw** [comment]
We have updated our installation [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#installation).
