### ISSUE TITLE
生成的视频出现可疑的水印。

### ISSUE THREAD

**Issue by edentliang** [hpcaitech/Open-Sora#345]
https://github.com/hpcaitech/Open-Sora/assets/23467766/a5bf2a6a-0db9-4485-803b-f6f98bffbca5

使用的prompt 是： generates a video of a beautiful parrot at close range. it has blue feathers and red breasts. its top is made of fine flower feathers, and its eyes are amazing red. 左上角出现水印

**Comment by zhengzangw** [comment]
We also notice this issue. I think this is because some of our video data contains a watermark. Continue fine-tuning can be a potential fix for this problem.
