### ISSUE TITLE
https://huggingface.co/spaces/hpcai-tech/open-sora 无法加载和运行

### ISSUE THREAD

**Issue by LinQianhe02grey** [hpcaitech/Open-Sora#346]
作者您好，很感谢您的工作。我想询问一下为什么挂载的demo运行不了，他这里显示仅有cpu.
![Uploading 40b39865eab911c76b54681aea48e8c4.png…]()

**Comment by LinQianhe02grey** [comment]
<img width="733" alt="40b39865eab911c76b54681aea48e8c4" src="https://github.com/hpcaitech/Open-Sora/assets/165568597/6e1ef659-f390-4e4b-96a5-fd440baa95a9">

**Comment by zhengzangw** [comment]
The GPU will be allocated when you do the inference. The huggingface demo is down for a while and is now repaired.
