### ISSUE TITLE
How can I run the project without using Apex?

### ISSUE THREAD

**Issue by JamesTensor** [hpcaitech/Open-Sora#349]
The Git homepage mentions that the project can be run without using Apex.

#set enable_layernorm_kernel=False in config to avoid using Apex

What is the specific command for this?

I added --enable_layernorm_kernel=False after the inference command, but it reported an error that the parameter was unrecognized.
I also modified the 'enable_layernorm_kernel': False under the script opensora/configs/opensora/inference/16x256x256.py, but it still doesn't work.

**Comment by jiayueru** [comment]
Hi, you need to navigate to the file "configs/opensora-v1-1/train/stage2.py" and make the following modifications:
model = dict(
    type="STDiT2-XL/2",
    from_pretrained=None,
    input_sq_size=512,  # Note: the pretrained model is trained on 512x512
    qk_norm=True,
    enable_flashattn=True,
    enable_layernorm_kernel=False,
)

**Comment by zhengzangw** [comment]
That's correct. You need to manually modify the config file.

**Comment by KLL535** [comment]
> That's correct. You need to manually modify the config file.

What files? You could at least write.

vi ~/Open-Sora/configs/opensora-v1-1/train/stage1.py
vi ~/Open-Sora/configs/opensora-v1-1/train/stage2.py
vi ~/Open-Sora/configs/opensora-v1-1/train/stage3.py
vi ~/Open-Sora/configs/opensora-v1-2/train/stage1.py
vi ~/Open-Sora/configs/opensora-v1-2/train/stage2.py
vi ~/Open-Sora/configs/opensora-v1-2/train/stage3.py

enable_layernorm_kernel=False,

It doesn't do anything

python gradio/app.py
```
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
```

**Comment by KLL535** [comment]
> Hi, you need to navigate to the file "configs/opensora-v1-1/train/stage2.py" and make the following modifications: model = dict( type="STDiT2-XL/2", from_pretrained=None, input_sq_size=512, # Note: the pretrained model is trained on 512x512 qk_norm=True, enable_flashattn=True, enable_layernorm_kernel=False, )

Its not work!
