### ISSUE TITLE
为什么魔改DiT？

### ISSUE THREAD

**Issue by qiuyang163** [hpcaitech/Open-Sora#35]
![image](https://github.com/hpcaitech/Open-Sora/assets/8520472/6dded50d-7184-4f45-ab8b-4c5c031b09ff)
DiT原文结构采用了AdaLN，condition内的class label不包含sequence维度，因此需要加入cross attention才能处理复杂文本序列和patch序列的关系。但是本项目的实现魔改了这个结构，把patch的self attention直接修改为patch序列和text condition的cross attention，忽略了patch序列的self attention，这样做的目的是？
忽略patch的self attention，不会有帧生成的质量问题吗？

**Comment by qiuyang163** [comment]
@binmakeswell

**Comment by af-74413592** [comment]
没懂，patch的self attention不是做了吗。

**Comment by af-74413592** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/863c7d79-03d2-4093-8336-6e74d881a9b3)
和原版dit一模一样的写法啊

**Comment by af-74413592** [comment]
> ![image](https://private-user-images.githubusercontent.com/74224119/310485260-863c7d79-03d2-4093-8336-6e74d881a9b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjcwNzEsIm5iZiI6MTcwOTcyNjc3MSwicGF0aCI6Ii83NDIyNDExOS8zMTA0ODUyNjAtODYzYzdkNzktMDNkMi00MDkzLTgzMzYtNmU3NGQ4ODFhOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyMDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Nzg3ZTZlMmZlMTQ3MTIxOGNkZTU1ZTQwYjU1NjQ3ZmQ2NzkyYmEwOThlMzc5N2MwNmJiZTRiYjYyZTZjZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XCsr7m0qgr_8cNFhglm17Jk562BOtiRCwrDD3HMNu6k) 和原版dit一模一样的写法啊

还真是不一样。。。
![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/ae6b199a-c523-4c1f-b12b-ec77ca5b9516)

**Comment by af-74413592** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/052c30b2-efb8-44ef-9420-d3a696e23a24)
确实都改掉了。。。不做self attn，光有cross attn 不太行吧

**Comment by af-74413592** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/b77778b4-3366-4304-acba-57c68ed873e5)
原版其实就是t+y 作为c,做一下shift和scale，然后self attn

**Comment by qiuyang163** [comment]
是的，我这里也是有点疑问，希望作者给解答吧

**Comment by af-74413592** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/41fa9294-cac5-4608-bfcd-9986d089e351)
opensora plan那边的实现

**Comment by qiuyang163** [comment]
https://github.com/neonsecret/DiTFusion?tab=readme-ov-file

**Comment by af-74413592** [comment]
> 是的，我这里也是有点疑问，希望作者给解答吧

![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/f67dd6f6-80c5-49c5-a991-0ec0dbe5385d)
最大的可能性因为是text latent, kvcache会变得很小，只有Q很大，但是这样硬压复杂度估计效果不会好的。

**Comment by af-74413592** [comment]
> https://github.com/neonsecret/DiTFusion?tab=readme-ov-file 这个代码库拥有cross attention的实现，附带256 分辨率的DiT预训练权重

![image](https://github.com/hpcaitech/Open-Sora/assets/74224119/ee7d49d2-c039-4f55-94ad-f6a3818f5b10)
不是的他是先做了self,在做的cross。

**Comment by qiuyang163** [comment]
> > https://github.com/neonsecret/DiTFusion?tab=readme-ov-file 这个代码库拥有cross attention的实现，附带256 分辨率的DiT预训练权重
> 
> ![image](https://private-user-images.githubusercontent.com/74224119/310506743-ee7d49d2-c039-4f55-94ad-f6a3818f5b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzA0NjEsIm5iZiI6MTcwOTczMDE2MSwicGF0aCI6Ii83NDIyNDExOS8zMTA1MDY3NDMtZWU3ZDQ5ZDItYzAzOS00ZjU1LTk0YWQtZjZhMzgxOGY1YjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzMDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZWU0NzliMDcyNzVmOTc2OTA3NDVhNTEzZTBjNzA3NWMwNzY4ZDUwMTExYTZkYjExNTMwYzI1MTYwYWFkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qzbJBIf644FZZC117wmJP6YB0HMpptDxEDI0e7oXVQc) 不是的他是先做了self,在做的cross。

是的，这个应该DiT 带有cross attention的标准实现，先self atten，再 cross attn

**Comment by af-74413592** [comment]
光有cross 3d图像块本身的特征几乎就没有学习了。但是也不会说完全不能训，掉点估计会很严重吧。

**Comment by quantumiracle** [comment]
the PIXART-alpha's structure should be the right one

**Comment by ver217** [comment]
We support both these two methods. Just set `use_cross_attn=False`, then it will use in-context conditioning (token concat). If using adaLN-zero, we cannot use sequential text features, instead, we can only use pooled text features. We may implement this if we find it useful.

**Comment by ver217** [comment]
I've updated training script, you can choose model arch by using `-x` option

**Comment by quantumiracle** [comment]
I guess people are looking to:
```
        if self.add_self_atten:
            shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = (
                self.adaLN_modulation(t).chunk(6, dim=1)
            )
            # multi-head self-attention
            x = x + gate_msa.unsqueeze(1) * self.attn_self(
                modulate(self.norm0(x), shift_msa, scale_msa), attention_mask
            )
            # multi-head cross-attention
            x = x + self.attn(self.norm1(x), context, attention_mask
            )
            # feed-forward
            x = x + gate_mlp.unsqueeze(1) * self.mlp(
                modulate(self.norm2(x), shift_mlp, scale_mlp)
            )
```
in DitBlock.forward() when -x='cross-attn'

**Comment by quantumiracle** [comment]
> I guess people are looking for (in this thread):
> 
> ```
>         if self.add_self_atten:
>             shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = (
>                 self.adaLN_modulation(t).chunk(6, dim=1)
>             )
>             # multi-head self-attention
>             x = x + gate_msa.unsqueeze(1) * self.attn_self(
>                 modulate(self.norm0(x), shift_msa, scale_msa), context=None, mask=self_attention_mask
>             )
>             # multi-head cross-attention
>             x = x + self.attn(self.norm1(x), context, attention_mask
>             )
>             # feed-forward
>             x = x + gate_mlp.unsqueeze(1) * self.mlp(
>                 modulate(self.norm2(x), shift_mlp, scale_mlp)
>             )
> ```
> 
> in DitBlock.forward() when -x='cross-attn'

Actually found this will require huge memory (~10^3 GB VRAM) in `expand_mask_4d()` function for creating self_attention_mask. Another finding is with argument `-x='cross-attn'` it will also requires huge VRAM thus not feasible, any idea on how to solve this?

**Comment by howardgriffin** [comment]
Any update? 

Even though the code was updated last week, I still see that the ‘cross-attn’ structure is incorrect which lacks 'self-attn' before 'cross-attn'

**Comment by zhengzangw** [comment]
We have updated our code. Now we use a PixArt-based DiT structure, with inserted temporal attention.
