### ISSUE TITLE
最终训练数据CSV文件

### ISSUE THREAD

**Issue by fshipy** [hpcaitech/Open-Sora#351]
请问可以分享一下Data Processing之后最终的训练数据集的CSV文件吗。
并且我们怎么样可以知道每个Training Stage用了哪些Data呢？谢谢！

**Comment by aiPenguin** [comment]
我也想问一下你们有计划发布训练时的csv文件么？尤其是Inter4K本身是没有标题的，以及你们用了哪些pexels的视频和对应的标题。
感谢！

**Comment by zhengzangw** [comment]
虽然可以发布我们的 csv，但是我们在处理的过程中，没有记录视频剪切的对应时间戳。这样即使发布了可能大家也没法用，所以暂时先不打算发布了。

**Comment by SystemErrorWang** [comment]
> 虽然可以发布我们的 csv，但是我们在处理的过程中，没有记录视频剪切的对应时间戳。这样即使发布了可能大家也没法用，所以暂时先不打算发布了。

同求一个pixels的视屏链接，没有对应时间戳也可以自己下载清洗一下
