### ISSUE TITLE
Can you explain the details about you filter configuration when you process the dataset for fine-tune

### ISSUE THREAD

**Issue by tianzhaohaha** [hpcaitech/Open-Sora#353]
Could you please share the final Data Processing Meta CSV? I would like to know which videos were used in each training stage or how did you get the 500k HQ videos. Thank you!

**Comment by zhengzangw** [comment]
As we mentioned in the report, we have no enough disk IO for filtering. Thus, we typically use all videos from pexels, and a subset of videos with an aesthetic score higher than 5, and an optical flow larger than 3.
