### ISSUE TITLE
How to load Open-Sora 1.1 checkpoint weights

### ISSUE THREAD

**Issue by simonfei123** [hpcaitech/Open-Sora#360]
I know it can be downloaded from https://huggingface.co/hpcai-tech/OpenSora-STDiT-v2-stage2/tree/main but before there was only a .pth file and I can just save the file to ./pretrained_models. But now saving the model.safetensors doesn't work.

**Comment by hadipash** [comment]
#322

**Comment by zhengzangw** [comment]
Now we have added automatical checkpoint loading.
