### ISSUE TITLE
Image and video inference returns static

### ISSUE THREAD

**Issue by tcarlton2000** [hpcaitech/Open-Sora#363]
When running the sample command:

```
python scripts/inference.py configs/opensora-v1-1/inference/sample.py \
    --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854
```

it outputs a video file that looks like static.

https://github.com/hpcaitech/Open-Sora/assets/2098918/c0f11219-3ba8-499a-8bb4-a9df59a85421

I see similar results when generating images or using different a `ckpt-path`. They all look like this.

**Comment by zhengzangw** [comment]
Try pull the latest code. We have added automatic checkpoint loading. In your case, you do not load a pretrained model.
