### ISSUE TITLE
训练130k之后loss曲线没怎么下降

### ISSUE THREAD

**Issue by oceanogeology** [hpcaitech/Open-Sora#365]
![image](https://github.com/hpcaitech/Open-Sora/assets/38741650/3bb6c031-422f-4f52-a49b-0700bde601e2)
loss曲线如上图，基于预训练模型，在512x512的2w左右2s的视频切分上，训练130k，loss曲线没怎么下降，后面的视频生成效果和原始训练视频差距很大，请教有哪些优化手段。

**Comment by soon-yau** [comment]
Same observation, loss doesn't change a lot despite the model improves.

**Comment by zhengzangw** [comment]
As observed in our experiments, the loss will not decrease as the model improves. This is due to the DDPM training objectives. The loss of training DDPM does not mean much. You should other evaluation (such as human evaluation) to measure the performance.
