### ISSUE TITLE
Mismatch in last layers during inference

### ISSUE THREAD

**Issue by Trinita21typeset** [hpcaitech/Open-Sora#37]
I am running the inference and this is what I am getting. 
The command that I ran:` python sample.py -m "DiT-XL/2" --text "a person is walking on the street" --ckpt /home/nlp/open_sora/Open-Sora/pretrained_models/DiT-XL-2-256x256.pt --height 256 --width 256 --fps 10 --sec 5 --disable-cfg`
I downloaded the checkpoints using download.py in the given repo.

![image](https://github.com/hpcaitech/Open-Sora/assets/107546335/8697079b-1351-4c77-b391-01f2e3e79658)

**Comment by Trinita21typeset** [comment]
Then can you let me know how to load the weights or where do I download the weights so that I can run the model locally?

**Comment by zhengzangw** [comment]
We have updated our code and inference. Please see [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference) for more instructions.
