### ISSUE TITLE
 How can I determine that the number given for the mask_strategy parameter is the best? Are there any methods for this?

### ISSUE THREAD

**Issue by White-Friday** [hpcaitech/Open-Sora#373]

**Comment by zhengzangw** [comment]
This is only for training. You can see the report for some preliminary results.

**Comment by zhengzangw** [comment]
If you want to finetune an image-based model from an already trained one, I would suggest 0.5 for not masking, and 0.5 for the rest. If you want to train from scratch, 0.1/0.2 is enough.
