### ISSUE TITLE
The generated pictures are all garbled

### ISSUE THREAD

**Issue by JamesTensor** [hpcaitech/Open-Sora#378]
GOOD JOB！You are working on a great cause！Thank you for your contribution to open source.
But when I use different prompt words to generate images, they are all garbled. May I ask what went wrong?

@zhengzangw @JThh Thank you both very much for your time

https://github.com/hpcaitech/Open-Sora/assets/45690898/fea0320a-d92a-4236-b350-d5695b513f88

![屏幕截图 2024-05-07 194608](https://github.com/hpcaitech/Open-Sora/assets/45690898/1b4550da-b763-4c11-a6ff-23a50c1a97f0)

**Comment by JamesTensor** [comment]
@zhengzangw @JThh Thank you both very much for your time

**Comment by zhengzangw** [comment]
This is not expected as we can successfully generate the correct image and video. Could you please provide the command you are using?

**Comment by JamesTensor** [comment]
The problem has been solved, thank you for your attention.
The reason is that the code does not load the model correctly
