### ISSUE TITLE
我想从头开始训练模型，不加入预训练模型，但是推理的效果不好

### ISSUE THREAD

**Issue by kawayi12318** [hpcaitech/Open-Sora#384]
我使用训练的模型进行推理时，不加入预训练模型的效果如下：

https://github.com/hpcaitech/Open-Sora/assets/107163121/50383039-7dc0-4e66-9afb-9cca734615e9

效果不好的原因是什么呢？

**Comment by zhengzangw** [comment]
你是指你从头训练了一个模型吗？那可能是你训练的量太小了。

**Comment by kawayi12318** [comment]
> 你是指你从头训练了一个模型吗？那可能是你训练的量太小了。

是的，我从头训练了一个模型，我设置了from_pretrained=None
model = dict(
    type="STDiT-XL/2",
    space_scale=0.5,
    time_scale=1.0,
    from_pretrained=None,
    enable_flashattn=True,
    enable_layernorm_kernel=True,
)
但是效果不好

**Comment by zhengzangw** [comment]
如果是从头训练的话，68k 还是很小的。而且你没有用 image diffusion model 权重做初始化的话，学起来就更慢了。

**Comment by kawayi12318** [comment]
> 如果是从头训练的话，68k 还是很小的。而且你没有用 image diffusion model 权重做初始化的话，学起来就更慢了。

好的，我会继续训练观察效果，感谢你的回复

**Comment by AlphaNext** [comment]
> 如果是从头训练的话，68k 还是很小的。而且你没有用 image diffusion model 权重做初始化的话，学起来就更慢了。

@zhengzangw 请问从代码的哪块导入image diffusion model的权重呢？
