### ISSUE TITLE
Error inference 'colossalai.moe'

### ISSUE THREAD

**Issue by eduardocarnunes** [hpcaitech/Open-Sora#39]
-----------------
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
----------------
nvidia-smi
NVIDIA GeForce GTX 1660 Ti     Off | 00000000:01:00.0  On |                  N/A |
| N/A   54C    P8               9W /  80W |     54MiB /  6144MiB |     29%      Default 
---------------
pip freeze show
pip freeze show
absl-py==2.1.0
aiohttp==3.9.3
aiosignal==1.3.1
attrs==23.2.0
av==11.0.0
bcrypt==4.1.2
certifi==2024.2.2
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
colossalai==0.3.3
contexttimer==0.3.3
cryptography==42.0.5
datasets==2.18.0
decorator==5.1.1
Deprecated==1.2.14
dill==0.3.8
distlib==0.3.8
einops==0.7.0
fabric==3.2.2
filelock==3.13.1
frozenlist==1.4.1
fsspec==2024.2.0
grpcio==1.62.0
huggingface-hub==0.21.4
identify==2.5.35
idna==3.6
invoke==2.2.0
Jinja2==3.1.3
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
networkx==3.2.1
ninja==1.11.1.1
nodeenv==1.8.0
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
packaging==23.2
pandas==2.2.1
paramiko==3.4.0
pillow==10.2.0
platformdirs==4.2.0
pre-commit==3.6.2
protobuf==4.25.3
psutil==5.9.8
pyarrow==15.0.0
pyarrow-hotfix==0.6
pycparser==2.21
Pygments==2.17.2
PyNaCl==1.5.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
rich==13.7.1
safetensors==0.4.2
setuptools==68.2.2
six==1.16.0
sympy==1.12
tensorboard==2.16.2
tensorboard-data-server==0.7.2
timm==0.9.16
tokenizers==0.15.2
torch==2.2.1
torchvision==0.17.1
tqdm==4.66.2
transformers==4.38.2
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
virtualenv==20.25.1
Werkzeug==3.0.1
wheel==0.41.2
wrapt==1.16.0
xxhash==3.4.1
yarl==1.9.4
------------------------
coomand: python sample.py -m "DiT/XL-2" --text "a person is walking on the street" --ckpt /path/to/checkpoint --height 256 --width 256 --fps 10 --sec 5 --disable-cfg

ERROR:
(open312) eduardo@eduardo-Creator-15M-A9SD:~/Documents/Open-Sora$ python sample.py -m "DiT/XL-2" --text "a person is walking on the street" --ckpt /path/to/checkpoint --height 256 --width 256 --fps 10 --sec 5 --disable-cfg
Traceback (most recent call last):
  File "/home/eduardo/Documents/Open-Sora/sample.py", line 21, in <module>
    from open_sora.modeling import DiT_models
  File "/home/eduardo/Documents/Open-Sora/open_sora/modeling/__init__.py", line 1, in <module>
    from .dit import DiT, DiT_models
  File "/home/eduardo/Documents/Open-Sora/open_sora/modeling/dit/__init__.py", line 1, in <module>
    from .dit import SUPPORTED_SEQ_PARALLEL_MODES, DiT, DiT_models
  File "/home/eduardo/Documents/Open-Sora/open_sora/modeling/dit/dit.py", line 22, in <module>
    from open_sora.utils.comm import gather_seq, split_seq
  File "/home/eduardo/Documents/Open-Sora/open_sora/utils/comm.py", line 6, in <module>
    from colossalai.moe._operation import MoeInGradScaler, MoeOutGradScaler
ModuleNotFoundError: No module named 'colossalai.moe'

**Comment by ver217** [comment]
Hi, I've updated requirements in #42 . Could you try the latest code?

**Comment by ver217** [comment]
> python version needs to be <3.9, otherwise, you'll have problems installing colossalai

Could you tell me what is the problem? We tested with python==3.10

**Comment by zhengzangw** [comment]
We have updated our code and provide a better instruction on installation [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#installation).
