### ISSUE TITLE
How can I load opensora 1.1 model with huggingfacetoken

### ISSUE THREAD

**Issue by JamesTensor** [hpcaitech/Open-Sora#391]
Amazing project, thank you for your hard work！I have deployed open Sora 1.1 and can generate video by following command:
python scripts/inference.py configs/opensora-v1-1/inference/sample.py --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854

When I run orther Inference command, it prompts that a huggingface token is required to download the model.

I try Inference command: python scripts/inference.py configs/opensora-v1-1/inference/sample.py \
    --ckpt-path CKPT_PATH --prompt "A beautiful sunset over the city" --num-frames 16 --image-size 480 854 

And the error is reported as follows:
401 Client Error: Unauthorized for url: https://huggingface.co/CKPT_PATH/resolve/main/config.json
Repository Not Found for url: https://huggingface.co/CKPT_PATH/resolve/main/config.json.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
CKPT_PATH is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

And I try to add arguments: --token myhuggingfacetoken,but I get : unrecognized arguments: --token myhuggingfacetoken. In addition, Huggingface-cli login is also useless.

How can I load opensora 1.1 model?Thank you very much for your help

**Comment by JamesTensor** [comment]
Does anyone have the same problem and can help me? Thank you so much

**Comment by TWTWTWTWTWTWTWTW** [comment]
Same...I also checked out the tutorial on the repo page, which is on Bilibili. The video tells you to sign up on their official cloud platform (which is really cheap btw, 6 rmb/hour for H800 GPU 80G), however there are nevertheless problems, they seem to have forgotten to put the corresponding pretrained models in the folder.
