### ISSUE TITLE
data process for pre-training and fine-tuning

### ISSUE THREAD

**Issue by liuheng0111** [hpcaitech/Open-Sora#393]
![image](https://github.com/hpcaitech/Open-Sora/assets/18352727/83f1490a-0397-4730-b342-759d943e9c48)

Here you said prepare a 10M dataset. What is it composed of, panda-10m and HD-VG-130M? How much of the HD-VG dataset has been used? The pre-training has 9.7M videos. Does this mean that the processing pipeline only filtered out 3% of the videos? What processing steps were involved in the pre-training, and what processing steps were involved in the fine-tuning? What filtering thresholds were used for each?

**Comment by handsomeZhuang** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/139242546/6352c52e-c488-4b47-845f-8c57cbf3f344)数据处理跟训练同时进行吗？为什么不提前进行离线预处理数据呢？
