### ISSUE TITLE
about the usage of computational power from colossal cloud

### ISSUE THREAD

**Issue by reich208github** [hpcaitech/Open-Sora#395]
hi, guys

where can i find the command lines related with the video as follows:

五分钟部署开源AIGC文生视频大模型Open Sora
https://www.bilibili.com/video/BV141421R7Ag/?vd_source=9d16204c480eb7211a5570c2cc4e6c46

i have found that the command lines mentioned above cannot be found in the github.

**Comment by lanran2001** [comment]
You can see the command lines and the full tutorials for running Open-Sora on the cloud platform here:https://mp.weixin.qq.com/s/HWtaa3pNty6HF8ShLsuOWA

**Comment by reich208github** [comment]
> Hi. You can see the command lines and the full tutorials for running Open-Sora on the cloud platform here: https://mp.weixin.qq.com/s/HWtaa3pNty6HF8ShLsuOWA

i found that this tutorial is for opensora1.0, where can i find a tutorial for opensora1.1?
