### ISSUE TITLE
my colossal cloud account cannot sign in!

### ISSUE THREAD

**Issue by reich208github** [hpcaitech/Open-Sora#396]
hi guys,

i have found that my colossal cloud account cannot sign in. And this account is just signed up few days ago!

both username+password and phone number cannot work!

if use the username+password to sign in, the prompt will be:

**Username or password not correct**

if use the phone number  to sign in, the prompt will be:

**Failed to request OTP, error: Mobile number not found**

it seems like my account has been canceled yet!

**Comment by ofey404** [comment]
@reich208github Hello, please provide your username, we will put this problem in the highest priority.

And, please join the Wechat Group and our developers would contact you directly, as soon as possible.

<img width="300" alt="潞晨云-Colossal Cloud用户群" src="https://github.com/hpcaitech/Open-Sora/assets/35857538/d55ab6bc-25ee-4d67-a6dc-1da60a612d49">

**Comment by reich208github** [comment]
> @reich208github Hello, sorry for the inconvenience, I am the oncall engineer of colossal cloud.
> 
> Please provide your username, we will put this problem in the highest priority.
> 
> And, please join the Wechat Group and our developers would contact you directly, as soon as possible.
> <img alt="潞晨云-Colossal Cloud用户群" width="300" src="https://private-user-images.githubusercontent.com/35857538/330014946-d55ab6bc-25ee-4d67-a6dc-1da60a612d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTQwMDAsIm5iZiI6MTcxNjU1MzcwMCwicGF0aCI6Ii8zNTg1NzUzOC8zMzAwMTQ5NDYtZDU1YWI2YmMtMjVlZS00ZDY3LWE2ZGMtMWRhNjBhNjEyZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEyMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZTQyYTk4MmQwNTU3YTNkODJmN2UzZmRkNjMyYjUyYzI2MWQwMGVlMzUxOTQyOTU1ZTVmNDQwZjU4MTJlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xjAt11RxvJh851pOkLEOMUwJU7lAcIJhFyoLN7WfbzE">

some other engineers in your team has helped me to solve this problem, thanks
