### ISSUE TITLE
Caption problem with frame 3

### ISSUE THREAD

**Issue by ZuhaoLiu** [hpcaitech/Open-Sora#424]
Hello, I read your answer from https://github.com/hpcaitech/Open-Sora/issues/303, 
but I want to explore the caption effect with 3 frames.

However, I found the generated results are weird. 

![Screenshot 2024-06-03 095348](https://github.com/hpcaitech/Open-Sora/assets/48410302/30395d45-f05a-4497-984c-d49aa10234d1)

It seems that the generated captions are all incomplete fragments. However, when I use 1 frame, the result is completely normal (several full sentences). Is there a bug here or do I need to adjust other parameters?

**Comment by zhengzangw** [comment]
LLaVA is bad at handling multiple frames. Please try the PLLaVA we used in OpenSora 1.2 as documented [here](https://github.com/hpcaitech/Open-Sora/blob/main/tools/caption/README.md#pllava-captioning).
