### ISSUE TITLE
is the text/vae frozen?

### ISSUE THREAD

**Issue by bio-mlhui** [hpcaitech/Open-Sora#425]
I see that the ckpt only provides DiT weights. Does this mean the text/vae are frozen during training? Are you preparing to release a fully-trained model?

**Comment by JThh** [comment]
Can @zhengzangw please take a look?

**Comment by zhengzangw** [comment]
During training, the text & vae is frozen as they are only tokenizers.

For Open-Sora 1.2, we release a trained VAE.
