### ISSUE TITLE
有微信交流群吗 

### ISSUE THREAD

**Issue by zhangfan-algo** [hpcaitech/Open-Sora#426]
可以加一个群吗 对项目比较感兴趣

**Comment by JThh** [comment]
Can @Sze-qq please help?

**Comment by JThh** [comment]
Please ask here if you have questions or ideas! @zhangfan-algo

**Comment by zhengzangw** [comment]
<img width="783" alt="Screenshot 2024-06-22 at 12 42 46" src="https://github.com/hpcaitech/Open-Sora/assets/30647653/bdabaf40-9990-42ee-8adb-0cd763d0fb42">

1. You can join the Discord to ask questions.
2. You can join the WeChat above and questions reaches me too.
3. Email me to schedule a discussion.
