### ISSUE TITLE
模型下载报错，无法直接连接到huggingface

### ISSUE THREAD

**Issue by jiyuwangbupt** [hpcaitech/Open-Sora#427]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
[rank0]:     sock = connection.create_connection(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
[rank0]:     raise err
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
[rank0]:     sock.connect(sa)
[rank0]: OSError: [Errno 101] Network is unreachable

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
[rank0]:     response = self._make_request(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
[rank0]:     raise new_e
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
[rank0]:     self._validate_conn(conn)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
[rank0]:     conn.connect()
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
[rank0]:     self.sock = sock = self._new_conn()
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
[rank0]:     raise NewConnectionError(
[rank0]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc0acd90220>: Failed to establish a new connection: [Errno 101] Network is unreachable

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
[rank0]:     resp = conn.urlopen(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
[rank0]:     retries = retries.increment(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
[rank0]:     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
[rank0]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/sd-vae-ft-ema/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0acd90220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
[rank0]:     metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
[rank0]:     r = _request_wrapper(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
[rank0]:     response = _request_wrapper(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
[rank0]:     response = get_session().request(method=method, url=url, **params)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[rank0]:     resp = self.send(prep, **send_kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[rank0]:     r = adapter.send(request, **kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
[rank0]:     return super().send(request, *args, **kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
[rank0]:     raise ConnectionError(e, request=request)
[rank0]: requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/sd-vae-ft-ema/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0acd90220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: bc1f25b6-1393-4459-b803-e7f872cd2250)')

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 383, in load_config
[rank0]:     config_file = hf_hub_download(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
[rank0]:     return _hf_hub_download_to_cache_dir(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
[rank0]:     _raise_on_head_call_error(head_call_error, force_download, local_files_only)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
[rank0]:     raise LocalEntryNotFoundError(
[rank0]: huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/disk2/youxiao/Open-Sora/scripts/inference.py", line 174, in <module>
[rank0]:     main()
[rank0]:   File "/disk2/youxiao/Open-Sora/scripts/inference.py", line 55, in main
[rank0]:     vae = build_module(cfg.vae, MODELS)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/registry.py", line 22, in build_module
[rank0]:     return builder.build(cfg)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank0]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank0]:     obj = obj_cls(**args)  # type: ignore
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/vae/vae.py", line 13, in __init__
[rank0]:     self.module = AutoencoderKL.from_pretrained(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 549, in from_pretrained
[rank0]:     config, unused_kwargs, commit_hash = cls.load_config(
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 411, in load_config
[rank0]:     raise EnvironmentError(
[rank0]: OSError: stabilityai/sd-vae-ft-ema does not appear to have a file named config.json.
E0604 14:51:16.042000 140228275307008 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 30472) of binary: /home/youxiao/anaconda3/envs/opensora/bin/python
Traceback (most recent call last):
  File "/home/youxiao/anaconda3/envs/opensora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/youxiao/anaconda3/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/inference.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-04_14:51:16
  host      : nv3090a
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 30472)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

你好，我使用HuggingFace-Download-Accelerator脚本下载了models--stabilityai--sd-vae-ft-ema/，请问我该把它放在哪个路径下，这样避免自动下载导致连接问题。
![stab](https://github.com/hpcaitech/Open-Sora/assets/37127150/82ed5706-b921-4f98-a3c4-e9ec0ec9b0c0)

**Comment by sculmh** [comment]
模型不大，可以换个huggingface镜像站下，export HF_ENDPOINT=https://hf-mirror.com

**Comment by sculmh** [comment]
模型不大，可以换个huggingface镜像站下，输命令export HF_ENDPOINT=https://hf-mirror.com/，然后应该就会自动从镜像站下

**Comment by JThh** [comment]
You may set `HF_HOME=/your-model-path` to avoid repeated downloads from huggingface.

**Comment by InitialDestination** [comment]
hi, same problem, is it solved?

**Comment by InitialDestination** [comment]
> hi, same problem, is it solved?

export HF_ENDPOINT=https://hf-mirror.com
