### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/aesthetic.pth'

### ISSUE THREAD

**Issue by fenghe12** [hpcaitech/Open-Sora#428]
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/aesthetic.pth'

**Comment by tonney007** [comment]
下载一下改个名字就好，参考下https://github.com/hpcaitech/Open-Sora/blob/main/tools/scoring/README.md

**Comment by fenghe12** [comment]
> 下载一下改个名字就好，参考下https://github.com/hpcaitech/Open-Sora/blob/main/tools/scoring/README.md

请问您可以训练起来吗

**Comment by fenghe12** [comment]
我有8张80GB的卡 stage1里面的配置文件都改成很小才能跑起来 并且只能同时分布在4张卡 要不然就会报错

**Comment by fenghe12** [comment]
很奇怪
