### ISSUE TITLE
Stage 1 trained from scratch?

### ISSUE THREAD

**Issue by rob-hen** [hpcaitech/Open-Sora#430]
Hi, 

thanks for all the great work and open-sourcing all steps.

When looking at the config files for OpenSora v.1.1 I see they are not using any pre-trained model (see for instance https://github.com/hpcaitech/Open-Sora/blob/4eaaa6cf68fc934aa65fe89b8933db658c7f48c7/configs/opensora-v1-1/train/stage1.py#L41).

Why you do not start from PixArt-alpha weights? They are not compatible?

**Comment by JThh** [comment]
Can @zhengzangw take a look?

**Comment by zhengzangw** [comment]
We start from `PixArt-alpha` and they are compatible. We pass the checkpoint through `--ckpt-path` in the command line.
