### ISSUE TITLE
请问，v1.1推理分辨率，为什么智能用240，426，其他推出来的都是噪音？

### ISSUE THREAD

**Issue by FDInSky** [hpcaitech/Open-Sora#434]

**Comment by TYang92677626** [comment]
I encounter the same problem. When I use this inference command：
`python scripts/inference.py configs/opensora-v1-1/inference/sample.py --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854 `
The video I got is:
![1718097184945](https://github.com/hpcaitech/Open-Sora/assets/152258345/5595354d-2a06-4863-9471-b91c2093bbfe)

**Comment by JThh** [comment]
It is presumably due to the fact that we train only using such sizes, i.e. it cannot generalize to other sizes for now.

**Comment by TYang92677626** [comment]
（1）Today I retested it, running the command:
`python scripts/inference.py configs/opensora-v1-1/inference/sample.py --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854 `
The video I got is:
![1718260517779](https://github.com/hpcaitech/Open-Sora/assets/152258345/7e458395-80e4-42fd-ade6-4ba72887398e)

（2）However, when I tested this command:
`python scripts/inference-long.py configs/opensora-v1-1/inference/sample.py --num-frames 64 --image-size 480 848 --sample-name image-cond --prompt 'A car driving on the ocean.'`
The video I got was a pretty bad scene:
![1718260736878](https://github.com/hpcaitech/Open-Sora/assets/152258345/30a082ef-7bc3-492e-94ac-64297306cc70)

（3）What I don't understand is that in the Open-Sora v1.1 report sample script, there is a `{"reference_path": "https://cdn.openai.com/tmp/s/interp/d0.mp4", "mask_strategy": "0,0,0,0,16"}`, what does this mean, is it the source video that needs to be referenced when generating the video? I executed this command and got:
`python scripts/inference-long.py configs/opensora-v1-1/inference/sample.py 
  --num-frames 32 --image-size 240 426 --loop 16 --condition-frame-length 8 --sample-name long 
  --prompt '|0|a white jeep equipped with a roof rack driving on a dirt road in a coniferous forest.|2|a white jeep equipped with a roof rack driving on a dirt road in the desert.|4|a white jeep equipped with a roof rack driving on a dirt road in a mountain.|6|A white jeep equipped with a roof rack driving on a dirt road in a city.|8|a white jeep equipped with a roof rack driving on a dirt road on the surface of a river.|10|a white jeep equipped with a roof rack driving on a dirt road under the lake.|12|a white jeep equipped with a roof rack flying into the sky.|14|a white jeep equipped with a roof rack driving in the universe. Earth is the background.{"reference_path": "https://cdn.openai.com/tmp/s/interp/d0.mp4", "mask_strategy": "0,0,0,0,16"}'`
The video I got is:
![1718260981777](https://github.com/hpcaitech/Open-Sora/assets/152258345/3a9cf9f8-356b-4e2a-80d0-1fc4da069a26)

（4）Without the reference_path parameter, I get something like the second video. {"reference_path": "https://cdn.openai.com/tmp/s/interp/d0.mp4", "mask_strategy": "0,0,0,0,16"} What does this mean?

**Comment by FDInSky** [comment]
@TYang92677626 你好，你第一次和第二次推理，有什么不同吗？

**Comment by TYang92677626** [comment]
> @TYang92677626 你好，你第一次和第二次推理，有什么不同吗？

Last week I just updated the code, nothing else changed. This week the 1.2 version was released, but I haven't tested it yet.
```
cd Open-Sora
git pull
pip install -e .
```

**Comment by zhengzangw** [comment]
> （1）Today I retested it, running the command: `python scripts/inference.py configs/opensora-v1-1/inference/sample.py --prompt "A beautiful sunset over the city" --num-frames 32 --image-size 480 854 ` The video I got is: ![1718260517779](https://private-user-images.githubusercontent.com/152258345/339239386-7e458395-80e4-42fd-ade6-4ba72887398e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzIzMjksIm5iZiI6MTcxOTAzMjAyOSwicGF0aCI6Ii8xNTIyNTgzNDUvMzM5MjM5Mzg2LTdlNDU4Mzk1LTgwZTQtNDJmZC1hZGU2LTRiYTcyODg3Mzk4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNDUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzBhYzA4ODkxNDI4MzhiOGMwNWUyODZjMWI1ZjM2MDE3ODU3OWI5ZjBhYmRkNTkyNmY1MGQ2M2YxYjZjOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kWY3kutNARgqH4bsb5XOgxoPUUpc1ntFEfOYPvgSVC8)
> 
> （2）However, when I tested this command: `python scripts/inference-long.py configs/opensora-v1-1/inference/sample.py --num-frames 64 --image-size 480 848 --sample-name image-cond --prompt 'A car driving on the ocean.'` The video I got was a pretty bad scene: ![1718260736878](https://private-user-images.githubusercontent.com/152258345/339240371-30a082ef-7bc3-492e-94ac-64297306cc70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzIzMjksIm5iZiI6MTcxOTAzMjAyOSwicGF0aCI6Ii8xNTIyNTgzNDUvMzM5MjQwMzcxLTMwYTA4MmVmLTdiYzMtNDkyZS05NGFjLTY0Mjk3MzA2Y2M3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNDUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTQ2Y2I2ZGZmMDE0MjgwY2U0ZWQxYTM3YmZhN2U3ODAyNzdjODdlMTcxN2RjMDE2MDgzYWVjZTNkMzljZDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MHNXN-qGF5bP-rTBfutU_VJKCdPKBCpGM0WGzCCKPrs)
> 
> （3）What I don't understand is that in the Open-Sora v1.1 report sample script, there is a `{"reference_path": "https://cdn.openai.com/tmp/s/interp/d0.mp4", "mask_strategy": "0,0,0,0,16"}`, what does this mean, is it the source video that needs to be referenced when generating the video? I executed this command and got: `python scripts/inference-long.py configs/opensora-v1-1/inference/sample.py --num-frames 32 --image-size 240 426 --loop 16 --condition-frame-length 8 --sample-name long --prompt '|0|a white jeep equipped with a roof rack driving on a dirt road in a coniferous forest.|2|a white jeep equipped with a roof rack driving on a dirt road in the desert.|4|a white jeep equipped with a roof rack driving on a dirt road in a mountain.|6|A white jeep equipped with a roof rack driving on a dirt road in a city.|8|a white jeep equipped with a roof rack driving on a dirt road on the surface of a river.|10|a white jeep equipped with a roof rack driving on a dirt road under the lake.|12|a white jeep equipped with a roof rack flying into the sky.|14|a white jeep equipped with a roof rack driving in the universe. Earth is the background.{"reference_path": "https://cdn.openai.com/tmp/s/interp/d0.mp4", "mask_strategy": "0,0,0,0,16"}'` The video I got is: ![1718260981777](https://private-user-images.githubusercontent.com/152258345/339241537-3a9cf9f8-356b-4e2a-80d0-1fc4da069a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzIzMjksIm5iZiI6MTcxOTAzMjAyOSwicGF0aCI6Ii8xNTIyNTgzNDUvMzM5MjQxNTM3LTNhOWNmOWY4LTM1NmItNGUyYS04MGQwLTFmYzRkYTA2OWEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNDUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmYxYTNlNzBlZTI3MDZiYWZlNTBmMjZhN2U1ODdiNjk4NWUxYTU5NDIxMTg1NjNmNGU4ODQxYWFjZDE5M2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P_eVgS90k2YXqeq55xALz1qxAqIS-3L-JqMWKfgPGeQ)
> 
> （4）Without the reference_path parameter, I get something like the second video. {"reference_path": "https://cdn.openai.com/tmp/s/interp/d0.mp4", "mask_strategy": "0,0,0,0,16"} What does this mean?

(2) The reason may be that the result is just not good.
(3) Please check [OpenSora v1.1 report](https://github.com/hpcaitech/Open-Sora/blob/main/docs/report_02.md#masked-dit-as-imagevideo-to-video-model) and [usage](https://github.com/hpcaitech/Open-Sora/blob/main/docs/config.md#advanced-inference-config)
(4) Seems something broken for v1.1. Please try OpenSora 1.2.
