### ISSUE TITLE
[Bug Report] In training process, when enable enable_sequence_parallelism, process panic with RuntimeError

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [hpcaitech/Open-Sora#439]
In training process, when i enable enable_sequence_parallelism, process will panic with errors like:
File "/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/layers/blocks.py", line 371, in forward
    kv = self.kv_linear(cond).view(B, -1, 2, self.num_heads, self.head_dim)
RuntimeError: shape '[24, -1, 2, 16, 72]' is invalid for input of size 6301440

In stdit.py y = y.squeeze(1).masked_select(mask.unsqueeze(-1) != 0).view(1, -1, x.shape[-1]) will not view to shape [24, -1, 2, 16, 72]

**Comment by JThh** [comment]
@wangxiaoyang-dev would you please share your command?

**Comment by wangxiaoyang-dev** [comment]
@JThh 
command: torchrun --nnodes=1 --nproc_per_node=2 scripts/train.py configs/opensora/train/16x256x256.py --data-path video_caption_part0_cleaned.csv
params: 
enable_sequence_parallelism=True
sp_size = 2
text_encoder model_max_length=120

when my video_caption length is less than 120, like this:
![image](https://github.com/hpcaitech/Open-Sora/assets/96978491/123c4792-1333-4331-b854-28ff915c2007)
it will panic with above RuntimeError.

**Comment by zhengzangw** [comment]
For OpenSora 1.1 & 1.2, sequence parallelism for training is not supported.

**Comment by kaixinbear** [comment]
Is there any plan to support sequence parallelism for training ?
