### ISSUE TITLE
Inference time and Training time on 3090?

### ISSUE THREAD

**Issue by DiamondGlassDrill** [hpcaitech/Open-Sora#440]
Amazing and very good work.

Before starting into it and enhancing, could you give some figures for GPU inference and training times?
E.g. consumer graphics card 3090? in both cases.

Thanks in advance.

**Comment by JThh** [comment]
We have yet had the timing for these consumer cards, but for reference: https://github.com/hpcaitech/Open-Sora/blob/main/docs/acceleration.md. 

You may also check out issues like #132, #104, etc.
