### ISSUE TITLE
running error , Gradio demo for Open-Sora 

### ISSUE THREAD

**Issue by varyuan** [hpcaitech/Open-Sora#442]
running error , Gradio demo for Open-Sora

**Comment by JThh** [comment]
Can you elaborate on the error?

**Comment by edwinzeng2005** [comment]
I got an error in the HF space.
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by edwinzeng2005** [comment]
I checked the console log again and this time it gave:
Incorrect use of <label for=FORM_ELEMENT>

**Comment by edwinzeng2005** [comment]
Ok I tried the gradio demo again.
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Failed to fetch Space status via SSE: BodyStreamBuffer was aborted
