### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by aulaywang** [hpcaitech/Open-Sora#445]
[rank0]: Traceback (most recent call last):                                                                                                                                                  
[rank0]:   File "/data/code/Open-Sora/scripts/inference.py", line 175, in <module>                                                               
[rank0]:     main()
[rank0]:   File "/data/code/Open-Sora/scripts/inference.py", line 149, in main
[rank0]:     samples = scheduler.sample(
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/__init__.py", line 75, in sample
[rank0]:     samples = self.p_sample_loop(
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/gaussian_diffusion.py", line 481, in p_sample_loop
[rank0]:     for sample in self.p_sample_loop_progressive(
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/gaussian_diffusion.py", line 534, in p_sample_loop_progressive
[rank0]:     out = self.p_sample(
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/gaussian_diffusion.py", line 429, in p_sample
[rank0]:     out = self.p_mean_variance(
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/respace.py", line 95, in p_mean_variance
[rank0]:     return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/gaussian_diffusion.py", line 286, in p_mean_variance
[rank0]:     model_output = model(x, t, **model_kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/respace.py", line 127, in __call__
[rank0]:     return self.model(x, new_ts, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/schedulers/iddpm/__init__.py", line 96, in forward_with_cfg
[rank0]:     model_out = model.forward(combined, timestep, y, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/stdit/stdit.py", line 276, in forward
[rank0]:     x = self.x_embedder(x)  # [B, N, C]
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/opensora/models/layers/blocks.py", line 121, in forward[rank0]:     x = self.proj(x)  # (B C T H W)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 610, in forward
[rank0]:     return self._conv_forward(input, self.weight, self.bias)
[rank0]:   File "/root/miniconda3/envs/opensora/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 605, in _conv_forward
[rank0]:     return F.conv3d(
[rank0]: RuntimeError: GET was unable to find an engine to execute this computation

**Comment by zhengzangw** [comment]
Could @ver217 have a look?

**Comment by aulaywang** [comment]
Sorry, I have solved it. Thank you.

**Comment by aulaywang** [comment]
> I meet the same problem. Could you please tell us how to solve this problem? Thanks

Actually I solved this problem after I updated the pytorch (there maybe some other bugs but not this bug). I did not totally understand the principle of this problem. You can follow the version like me: `torch=2.3.0` `torchaudio=2.1.2` `torchvision=0.18.0`

**Comment by ty625911724** [comment]
This is an interesting problem, especially when I utilize conda to install the cudatoolkit. 

I solve this issue by change the LD_LIBRARY_PATH, like:
export LD_LIBRARY_PATH=/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib

Similar issue has been discussed in https://github.com/pytorch/pytorch/issues/102535. 

Hope this solution can help others.
