### ISSUE TITLE
Issues during inference

### ISSUE THREAD

**Issue by abdullah1772** [hpcaitech/Open-Sora#45]
`python sample.py -m "DiT/XL-2" --text "a person is walking on the street" --ckpt /path/to/checkpoint --height 256 --width 256 --fps 10 --sec 5 --disable-cfg` 
What is the path to the checkpoint? Can you provide the weights or tell what weights to use?

**Comment by zhengzangw** [comment]
We have provided the model weights [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#model-weights). You can refer to [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#inference) for inference.
