### ISSUE TITLE
How to use image-to-video with v1.2?

### ISSUE THREAD

**Issue by FiineLee** [hpcaitech/Open-Sora#455]

**Comment by zhengzangw** [comment]
For gradio, please see the [readme](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#getting-started).

For command line, we have merged `infernece-long.py` into `inference.py`. The command line arguments is compatible with v1.1.

**Comment by zhengzangw** [comment]
> There is not scripts/inference-long.py as v1.1?, If I want to inference a list of images with prompt to generate videos, whether support?

Also supported. Same commands as v1.1 [here](https://github.com/hpcaitech/Open-Sora/blob/main/docs/config.md#advanced-inference-config).
