### ISSUE TITLE
有人训练出结果吗

### ISSUE THREAD

**Issue by howardgriffin** [hpcaitech/Open-Sora#46]
我用默认的设置，8卡训了两三天了，5w视频数据左右，但是现在一点视频的感觉都没有，都是patch状的拼接，是训练的不够吗，还是哪里出错了？

**Comment by jeffchy** [comment]
我跑的 "DiT-S/8"，用的默认训练脚本，训练了2/3个epoch的时候，sample的结果基本是随机

**Comment by xinyuxiao** [comment]
可以show下你们的结果吗

**Comment by jeffchy** [comment]
比较random 没啥意义，不过之前毕竟用了最小的模型，也只训练以一个epoch情有可原吧。
我试试更大的模型以及其他参数再看吧。

**Comment by howardgriffin** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/23454942/f924829c-68eb-4453-ba85-ee8b3931d2ba)
网络问题，不能上传大于100k的文件，直接从原视频里截了张图。实际的视频样子就是类似这种块状的无规则拼接

**Comment by jeffchy** [comment]
@howardgriffin 你好 能问问你的训练设置 以及看看你的训练曲线吗

**Comment by yhyu13** [comment]
openai 五原则

大数据
大算力
大模型
伸缩定律
蒸馏

**Comment by baixiaolu** [comment]
> openai 五原则
> 
> 
> 
> 大数据
> 
> 大算力
> 
> 大模型
> 
> 伸缩定律
> 
> 蒸馏

伸缩定律、蒸馏怎么理解(๑•̌.•̑๑)ˀ̣ˀ̣

**Comment by zhengzangw** [comment]
We have updated our model weights [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#model-weights).
