### ISSUE TITLE
undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType

### ISSUE THREAD

**Issue by Zane0227** [hpcaitech/Open-Sora#460]
拉取最新代码v1.2版本后，推理能力正常，但微调报错undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType。

[rank0]:   File "/data/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/stdit/stdit3.py", line 136, in forward
[rank0]:     x = x + self.cross_attn(x, y, mask)
[rank0]: RuntimeError: r.nvmlDeviceGetNvLinkRemoteDeviceType_ INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":27, please report a bug to PyTorch. Can't find nvmlDeviceGetNvLinkRemoteDeviceType: /lib64/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType

**Comment by Zane0227** [comment]
> 拉取最新代码v1.2版本后，推理能力正常，但微调报错undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType。
> 
> [rank0]: File "/data/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/data/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data/miniconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/stdit/stdit3.py", line 136, in forward [rank0]: x = x + self.cross_attn(x, y, mask) [rank0]: RuntimeError: r.nvmlDeviceGetNvLinkRemoteDeviceType_ INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":27, please report a bug to PyTorch. Can't find nvmlDeviceGetNvLinkRemoteDeviceType: /lib64/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType

CUDA版本12.1

**Comment by zhengzangw** [comment]
I did not run into this problem. According to your error, since it happens in cross_attn, I guess you have installed a wrong xformers version? Could @ver217 have a look?

**Comment by Zane0227** [comment]
> I did not run into this problem. According to your error, since it happens in cross_attn, I guess you have installed a wrong xformers version? Could @ver217 have a look?

thanks for replay，my xformer version is **_0.0.26.post1_**，which version should I use?

**Comment by Zane0227** [comment]
Use torch version 2.1.0, xformer 0.0.22.post4.
Problem solved.
Driver Version: 450.80.02 is too low for torch 2.3.0

**Comment by SiyangJ** [comment]
> Use torch version 2.1.0, xformer 0.0.22.post4. Problem solved. Driver Version: 450.80.02 is too low for torch 2.3.0

Hi I have recently encountered the same problem. I'm tempted to agree that the low driver version is causing the problem. But I can't upgrade the driver version in my case. Have you tried other ways to solve it? Do you think there are other ways to get around it?

**Comment by fcchit** [comment]
> > Use torch version 2.1.0, xformer 0.0.22.post4. Problem solved. Driver Version: 450.80.02 is too low for torch 2.3.0
> 
> Hi I have recently encountered the same problem. I'm tempted to agree that the low driver version is causing the problem. But I can't upgrade the driver version in my case. Have you tried other ways to solve it? Do you think there are other ways to get around it?

You can find the proper version of xformer in this website. [https://anaconda.org/xformers/xformers](url)
