### ISSUE TITLE
GPU splitting

### ISSUE THREAD

**Issue by Ph0rk0z** [hpcaitech/Open-Sora#461]
Any plans to support multi-gpu? I have enough vram but each GPU tops out at 24g. LLMs can be split this way so why not this? You already appear to use accelerate.

**Comment by zhengzangw** [comment]
For inference, we have supported and the documentation is [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#sequence-parallelism-inference). For training, we are working on this.

**Comment by Ph0rk0z** [comment]
Thank you, I didn't see. Does it run tensor parallel where it has to be an even number of GPUs?

**Comment by zhengzangw** [comment]
I think for now we cannot since we only support the case when dimension is dividable.

**Comment by Ph0rk0z** [comment]
It would have to be pipeline parallel otherwise, which is what other engines do.

**Comment by zhengzangw** [comment]
Yes, pipeline parallel & tensor parallel will solve your problem. But we will not go to implement them at this time as model training is our focus. You can try yourself or ask 3rd party for this.
