### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by dangweili** [hpcaitech/Open-Sora#467]
I see the midjourney dataset is invalid, such as wanng/midjourney-v5-202304-clean. Is there anyway to download the dataset?

**Comment by zhengzangw** [comment]
As Discord changes its policy, it is very difficult to get this unless you have downloaded them before. Thus, I suggest use the two following image datasets:
- JDB: https://journeydb.github.io/
- midjourney-v6: https://huggingface.co/Kvikontent/midjourney-v6
