### ISSUE TITLE
gradio demo bug

### ISSUE THREAD

**Issue by MontaEllis** [hpcaitech/Open-Sora#470]
I modify the local model fold

![image](https://github.com/hpcaitech/Open-Sora/assets/37856372/6ea7e525-54cb-4a58-bd0d-ad5bcc85e11c)

but got 
![image](https://github.com/hpcaitech/Open-Sora/assets/37856372/34908d42-6923-4f21-a3ff-a2894421058d)

**Comment by zhengzangw** [comment]
I add a `force_huggingface` in the model config and thus you can use locally download hugging face checkpoint.

**Comment by zhengzangw** [comment]
An update: now we support loading both the diffusion model and vae from your local path. Otherwise, if you want to load saved checkpoints from training (the previously default behaviour), set

```python
model = dict(
  ...
  force_huggingface = False,
)
```
