### ISSUE TITLE
Can provide a CKPT for a test

### ISSUE THREAD

**Issue by kingljl** [hpcaitech/Open-Sora#48]
Mainly, training requires GPU cards and time.. Can you provide a stable version of CKPT for us to run demo examples on a daily basis. Now I just don't know the effect, so I need to train the data first and then look at it.. The time is too long.

**Comment by jeffchy** [comment]
I tried different configurations but always failed to output meaningful results, wondering if I made some mistake or code was not ready.

**Comment by CacacaLalala** [comment]
> I tried different configurations but always failed to output meaningful results, wondering if I made some mistake or code was not ready.

Have you tried vae for video compress?  I change ae to vae and get the OOM issue.  But vqvae works fine.

**Comment by zhengzangw** [comment]
We have provided model weights [here](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#model-weights).
