### ISSUE TITLE
cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object

### ISSUE THREAD

**Issue by xinyuxiao** [hpcaitech/Open-Sora#49]
<img width="720" alt="image" src="https://github.com/hpcaitech/Open-Sora/assets/19719974/d0172a84-8d9e-4075-95fc-62e8698ab70c">

how to solve this problem, thanks

**Comment by ver217** [comment]
We solved this problem, see https://github.com/hpcaitech/Open-Sora/blob/main/train.py#L122
Could you try the latest version?
