### ISSUE TITLE
how to load opensorav1.2 model weights?

### ISSUE THREAD

**Issue by Lexarymade** [hpcaitech/Open-Sora#496]
I've already downloaded the vae and the stdit3 model weight from huggingface to my device. How can I load the downloaded model in the code instead of downloading from huggingface hpcaitech/Open-Sora? 

I can load the T5, but fail to load the vae and the stdit3

**Comment by catsled** [comment]
![image](https://github.com/hpcaitech/Open-Sora/assets/18079717/92b3930e-71ca-4e57-a24b-55eb55de5f5d)

modify tge from_pretrained in inference/sample.py

**Comment by zhengzangw** [comment]
Yes, try pull the latest code and replace the path in the from_pretrained in `configs/opensora-v1-2/inference/sample.py`.

**Comment by Lexarymade** [comment]
> commented

i will try, thx!

**Comment by liuxi0099** [comment]
> Yes, try pull the latest code and replace the path in the from_pretrained in `configs/opensora-v1-2/inference/sample.py`.

Do you mean line 18, 26, 33?
![屏幕截图 2024-06-20 222308](https://github.com/hpcaitech/Open-Sora/assets/6071480/94aef35f-de49-4122-a329-f5d372156c20)

**Comment by zhengzangw** [comment]
Yes.

**Comment by Lexarymade** [comment]
now I face following error：
OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json.
how to fix this ?

**Comment by zhengzangw** [comment]
See #525
