### ISSUE TITLE
the generated video quality different with the samples shown in gallery

### ISSUE THREAD

**Issue by runzeer** [hpcaitech/Open-Sora#504]
the generated video quality different with the samples shown in gallery. Could your share the relevant inference parameters for the gallery sample results?

https://github.com/hpcaitech/Open-Sora/assets/14292495/3b48b0e5-f175-4de2-98f3-04b96414eb65

**Comment by zhengzangw** [comment]
Could @Sze-qq have a look on this?

**Comment by Sze-qq** [comment]
Sure. Here are the parameters we used to generate the video:

Resolution: 720p
Sampling Steps: 100
Aesthetic Score: 7
Refine Prompt with GPT-4: Unchecked
Other settings: Default
Prompt:
A Japanese tram glides through the snowy streets of a city, its sleek design cutting through the falling snowflakes with grace. The tram's illuminated windows cast a warm glow onto the snowy surroundings, creating a cozy atmosphere inside. Snowflakes dance in the air, swirling around the tram as it moves along its tracks. Outside, the city is blanketed in a layer of snow, transforming familiar streets into a winter wonderland. Cherry blossom trees, now bare, stand quietly along the tram tracks, their branches dusted with snow. People hurry along the sidewalks, bundled up against the cold, while the tram's bell rings softly, announcing its arrival at each stop.

**Comment by runzeer** [comment]
Here is my inference configuration. I did the modification according to what you said.
[2024-06-21 02:58:22] Inference configuration:
 {'aes': 7.0,
 'align': 5,
 'aspect_ratio': '9:16',
 'batch_size': 1,
 'condition_frame_length': 5,
 'config': 'configs/opensora-v1-2/inference/sample.py',
 'dtype': 'bf16',
 'flow': None,
 'fps': 24,
 'frame_interval': 1,
 'model': {'enable_flash_attn': True,
           'enable_layernorm_kernel': True,
           'from_pretrained': 'hpcai-tech/OpenSora-STDiT-v3',
           'qk_norm': True,
           'type': 'STDiT3-XL/2'},
 'multi_resolution': 'STDiT2',
 'num_frames': '102',
 'prompt': ['A Japanese tram glides through the snowy streets of a city, its '
            'sleek design cutting through the falling snowflakes with grace. '
            "The tram's illuminated windows cast a warm glow onto the snowy "
            'surroundings, creating a cozy atmosphere inside. Snowflakes dance '
            'in the air, swirling around the tram as it moves along its '
            'tracks. Outside, the city is blanketed in a layer of snow, '
            'transforming familiar streets into a winter wonderland. Cherry '
            'blossom trees, now bare, stand quietly along the tram tracks, '
            'their branches dusted with snow. People hurry along the '
            "sidewalks, bundled up against the cold, while the tram's bell "
            'rings softly, announcing its arrival at each stop.'],
 'prompt_as_path': False,
 'resolution': '720p',
 'save_dir': './samples/debug',
 'save_fps': 24,
 'scheduler': {'cfg_scale': 7.0,
               'num_sampling_steps': 100,
               'type': 'rflow',
               'use_timestep_transform': True},
 'seed': 1024,
 'text_encoder': {'from_pretrained': 'DeepFloyd/t5-v1_1-xxl',
                  'model_max_length': 300,
                  'type': 't5'},
 'vae': {'from_pretrained': 'hpcai-tech/OpenSora-VAE-v1.2',
         'micro_batch_size': 4,
         'micro_frame_size': 17,
         'type': 'OpenSoraVAE_V1_2'}}
         
But the generated video is still blurry like below. Can you help me check whether there still exist incorrect parameters? Thanks a lot!


https://github.com/hpcaitech/Open-Sora/assets/14292495/0d0f9bf1-7d98-4e87-8363-5af857692df6

**Comment by runzeer** [comment]
@Sze-qq  Could you help me with the issues above? Thanks a lot!

**Comment by Sze-qq** [comment]
Hi @runzeer . I generated the image first and then clicked "Generate Video" on Gradio. Hope this helps.

**Comment by runzeer** [comment]
@Sze-qq. Thanks a lot for your explanation. But I found the generated image style, like the image below,  is different with the gallery videos. So You used the  hpcai-tech/OpenSora-STDiT-v3 checkpoint or the original Pixart-sigma checkpoint for the first text-to-image task? Or I should add some prompts.
![2_480p_cond](https://github.com/hpcaitech/Open-Sora/assets/14292495/ec5c86f7-d23b-4df7-95b8-84014795013c)
 for the generated style?

**Comment by zhengzangw** [comment]
We use the hpcai-tech/OpenSora-STDiT-v3 checkpoint. I tested that I can also reproduce @Sze-qq 's result.

**Comment by runzeer** [comment]
> We use the hpcai-tech/OpenSora-STDiT-v3 checkpoint. I tested that I can also reproduce @Sze-qq 's result.
@zhengzangw Thanks a lot. Did you share your seed for generating @Sze-qq 's result? I want to reproduce the video completely.

**Comment by crystallee-ai** [comment]
> Hi @runzeer . I generated the image first and then clicked "Generate Video" on Gradio. Hope this helps.

Thanks for your reply, but in the galary page, it denotes " text to video"

**Comment by zhengzangw** [comment]
> > Hi @runzeer . I generated the image first and then clicked "Generate Video" on Gradio. Hope this helps.
> 
> Thanks for your reply, but in the galary page, it denotes " text to video"

Sorry for the confuse, as several people contribute to the gallery. As the image is also generated with the same model, I think it can be viewed as "text to video" as well.

**Comment by ImmNaruto** [comment]
Hi @runzeer ，Could you share some videos of the gallery reproduction and how to use the image checkpoint? I’m currently confused about this issue because directly using the open-sora command-line inference with num_frame=1 doesn’t work, but I’ve tried other methods and still can’t get the image results. 
Additionally, in the newly updated 1.3 version, using the first frame of a given reference image also doesn’t achieve a smooth transition. It seems like the first frame has no effect on the video content; the first frame flashes briefly, and then the video jumps to its own content. If you have time, could you @Sze-qq @zhengzangw both help take a look? I’d really appreciate it. Thanks a lot!
