### ISSUE TITLE
ImportError: cannot import name 'get_image_size' from 'opensora.datasets.aspect' (/opt/conda/envs/pytorch/lib/python3.9/site-packages/opensora/datasets/aspect.py)

### ISSUE THREAD

**Issue by haisheng666** [hpcaitech/Open-Sora#512]
I am using Luchen Cloud. Please update the image so that we can use it directly。ImportError: cannot import name 'get_image_size' from 'opensora.datasets.aspect' (/opt/conda/envs/pytorch/lib/python3.9/site-packages/opensora/datasets/aspect.py)

**Comment by zhengzangw** [comment]
Just updated OpenSora 1.2 image on Luchen Cloud：[[Luchen Cloud](https://cloud.luchentech.com/)|[OpenSora Image](https://cloud.luchentech.com/doc/docs/image/open-sora/)|[Video Tutorial](https://www.bilibili.com/video/BV1ow4m1e7PX/?vd_source=c6b752764cd36ff0e535a768e35d98d2)]

**Comment by haisheng666** [comment]
Thank you, I'll try it, thanks for the open source project
