### ISSUE TITLE
demo can't work in huggingface space

### ISSUE THREAD

**Issue by johnniev5** [hpcaitech/Open-Sora#513]
it can't load 
https://huggingface.co/spaces/hpcai-tech/open-sora

**Comment by zhengzangw** [comment]
So sorry that it seems too many people are trying our model. There are not enough resources in the huggingface space.

**Comment by johnniev5** [comment]
ok, how to resolve it, do you have any plans.

**Comment by zhengzangw** [comment]
We are working on it. For now the demo will be temporarily down as we are testing our repair.

**Comment by zhengzangw** [comment]
Currently, it is up. Here are two updates:

1. The huggingface gradio cannot support flash-attn & apex, thus using larger memory and the generation speed is slower. Try not to generate 720p and too long video.
2. Thanks to HF they increase our number of replicas to 3, and thus have a better load balance.
