### ISSUE TITLE
Please update the code, a lot of deprecated packages

### ISSUE THREAD

**Issue by haisheng666** [hpcaitech/Open-Sora#514]
(pytorch) root@notebook-a3137185-ee3c-4098-8555-8a0300b9b6ab-0:~/Open-Sora# python scripts/inference.py configs/opensora-v1-2/inference/sample.py   --num-frames 16s --resolution 720p --aspect-ratio 9:16   --prompt "a beautiful waterfall"
/opt/conda/envs/pytorch/lib/python3.9/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/conda/envs/pytorch/lib/python3.9/site-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/root/.local/lib/python3.9/site-packages/torch/utils/_pytree.py:300: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
/opt/conda/envs/pytorch/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/conda/envs/pytorch/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/root/Open-Sora/scripts/inference.py", line 14, in <module>
    from opensora.datasets.aspect import get_image_size, get_num_frames
ImportError: cannot import name 'get_image_size' from 'opensora.datasets.aspect' (/opt/conda/envs/pytorch/lib/python3.9/site-packages/opensora/datasets/aspect.py)

**Comment by zhengzangw** [comment]
The deprecated packages are introduced by us. This is because `transformers` library cannot perfectly suit the latest PyTorch: https://github.com/huggingface/transformers/issues/27684

As these are just deprecated warnings, we will not fix this.
