### ISSUE TITLE
what the param <input_sq_size> stands for?

### ISSUE THREAD

**Issue by leonardodora** [hpcaitech/Open-Sora#519]
And how should we use it in training and sampling?
Thanks!

**Comment by zhengzangw** [comment]
`input_sq_size` is used to align the positional embedding. For training and sampling, just keep it fixed.

The reason we introduced this is that our weights are initialized from Pixart-Sigma, where the base image size is 512x512. Thus, to map all positional embedding to the same size, we set `input_sq_size` (means original model's input image resolution's square root) to 512.
