### ISSUE TITLE
生成结果与输入的提示内容偏离的比较大

### ISSUE THREAD

**Issue by mnewgithub** [hpcaitech/Open-Sora#522]
我在HuggingFace上测试的。
![屏幕截图 2024-06-21 152405](https://github.com/hpcaitech/Open-Sora/assets/44330906/22e87c95-77cd-4daf-95cb-81f38558bd9a)
这个时我输入的prompt
![output_1718954323 425854](https://github.com/hpcaitech/Open-Sora/assets/44330906/495611d8-b34a-41ad-b2cc-6e0052160858)
这个时生成的图片。
这个是啥原因呀？

**Comment by mnewgithub** [comment]
![output_1718955206 151818](https://github.com/hpcaitech/Open-Sora/assets/44330906/1b963212-6c1c-456d-a823-5863578e502e)
同样的prompt试了几遍，其中1此输出是个这。？？？

**Comment by mnewgithub** [comment]
![bfde7a30162c77b2f09ece0d36a94e09](https://github.com/hpcaitech/Open-Sora/assets/44330906/f27ab1e4-753a-4727-aefd-20fcd54da460)


![538390f7f7584a3b08c1ee1ed4083765](https://github.com/hpcaitech/Open-Sora/assets/44330906/3e0fcc7e-1797-40a5-a35d-4f608f9eef1c)
![e6d02f309004244e19a6604ca52e6e9a](https://github.com/hpcaitech/Open-Sora/assets/44330906/2a49e4a0-e66e-4a67-a6d1-af21efa51da5)
![d0e558405a056393b8e89d95c6bb77ee](https://github.com/hpcaitech/Open-Sora/assets/44330906/879ec106-553d-43a1-b910-086cc8bea469)
在可灵模型上可以输出正常的。内容
https://kolors.kuaishou.com/creation

**Comment by zhengzangw** [comment]
> 我在HuggingFace上测试的。 ![屏幕截图 2024-06-21 152405](https://private-user-images.githubusercontent.com/44330906/341679208-22e87c95-77cd-4daf-95cb-81f38558bd9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDc1MzksIm5iZiI6MTcxOTA0NzIzOSwicGF0aCI6Ii80NDMzMDkwNi8zNDE2NzkyMDgtMjJlODdjOTUtNzdjZC00ZGFmLTk1Y2ItODFmMzg1NThiZDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA5MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MTZhZGJhYjMzZjc2MzEwZTA1YTU1N2UyOWEwMGQxYWQ4ZGJjYTg1ZGQ5Njc2MWFjMmRjMjlhN2UzNjQ5NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiPvAL6BzazjL2Wn_CsQyOiCMH11nVJsJqslQYkj_6I) 这个时我输入的prompt ![output_1718954323 425854](https://private-user-images.githubusercontent.com/44330906/341679279-495611d8-b34a-41ad-b2cc-6e0052160858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDc1MzksIm5iZiI6MTcxOTA0NzIzOSwicGF0aCI6Ii80NDMzMDkwNi8zNDE2NzkyNzktNDk1NjExZDgtYjM0YS00MWFkLWIyY2MtNmUwMDUyMTYwODU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA5MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOWY0ZGQ1ZjcxZjRjZTBlNTYxOTkwZTU2MmMwNzZlMTU3YWYzMzQ2ODBmOTY1ODA5ODlkNDhlY2Q4MjFhMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vnYnuL9-joUKb8q44IUkEwOhSoZzQJvcgJ32zfqZMs4) 这个时生成的图片。 这个是啥原因呀？

你的输入得到这个结果是正常的。因为你使用了中文输入，但没有启用 GPT-4o 修改。我们的模型暂时只支持英文输入（所以生成了一团浆糊）。如果要使用中文，我们会通过 GPT-4o 对你的输入进行润色后输出。具体配置参考[此处](https://github.com/hpcaitech/Open-Sora?tab=readme-ov-file#gpt-4o-prompt-refinement)。需要配置一个 OPENAI_API_KEY 然后勾选 Refine with GPT4o
