### ISSUE TITLE
使用vqvae之后loss下降的非常缓慢，请问有参考的loss曲线吗？

### ISSUE THREAD

**Issue by jeffchy** [hpcaitech/Open-Sora#53]

**Comment by jeffchy** [comment]
OK, 那我等等

**Comment by zhengzangw** [comment]
We also find this and report [here](https://github.com/hpcaitech/Open-Sora/blob/main/docs/report_v1.md#efficiency-in-choosing-the-architecture). As a result, we choose a VAE from stability-ai to train our current models.
