### ISSUE TITLE
how to determine the num_frames given the time length?

### ISSUE THREAD

**Issue by Edwardmark** [hpcaitech/Open-Sora#536]
how to determine the num_frames given the time length?
I want to use the config num_frames to generate video, how to calculate the num_frames when given time length t and fps?
It seems pretty complex in the code. Could you please give me a simple equation? Thanks.

**Comment by Edwardmark** [comment]
Specifically, when I set num_frames to 68, the t in stdit_block is 20, I cannot understand why is that. Could you please explain a bit?Thanks.

**Comment by henbucuoshanghai** [comment]
do u find why?

**Comment by Edwardmark** [comment]
> do u find why?

no, it is so strange to set to 17.

**Comment by Edwardmark** [comment]
@sarroutbi @vjandrea @mahone3297 @duguyixiaono1 could you explain a bit? Thanks.

**Comment by Edwardmark** [comment]
@zhengzangw 
could you give me a hint why we set vae micro-batch to 17? When I change it to 16, the video generated  is really strange with sudden change.

**Comment by henbucuoshanghai** [comment]
When I change it to 16, or 18 bigger?or None?

**Comment by Edwardmark** [comment]
> When I change it to 16, or 18 bigger?or None?

When I change it to 16, the video generated will change suddenly with low consistency.

**Comment by zhengzangw** [comment]
> @zhengzangw could you give me a hint why we set vae micro-batch to 17? When I change it to 16, the video generated is really strange with sudden change.

The reason is we use a casual VAE. It will compress 17 frames to 5 frames. 17=1+4+4+4+4, 5=1+4. You should not use 16 or 18.

**Comment by Edwardmark** [comment]
@zhengzangw Thanks for your kind reply. I finally got it.
