### ISSUE TITLE
fix the docker image

### ISSUE THREAD

**Issue by yuvraj108c** [hpcaitech/Open-Sora#541]
Hi, the docker image is not usable at all.

There are issues with `fused_layer_norm_cuda` during inference etc. Please create a working version with all the optimisations working!

Thanks

**Comment by JThh** [comment]
Sure. Before we get to this, could you please let us know if the detail on the error you met and the dockerfile you used?

**Comment by KLL535** [comment]
Same issue
How do i make this thing work?
