### ISSUE TITLE
Can this be used to train image to video models? Is there any guide on how to prepare dataset for that task? 

### ISSUE THREAD

**Issue by i-amgeek** [hpcaitech/Open-Sora#55]

**Comment by ver217** [comment]
This is just for text-to-video now. We may implement this feature in the future.

**Comment by zhengzangw** [comment]
Now our code can train on both images and videos. Please see [instructions](https://github.com/hpcaitech/Open-Sora/blob/main/docs/commands.md) to launch experiments.
