### ISSUE TITLE
bad inference result

### ISSUE THREAD

**Issue by jinqinn** [hpcaitech/Open-Sora#553]
prompt:
a close-up shot of a woman standing in a dimly lit room. she is wearing a traditional chinese outfit, which includes a red and gold dress with intricate designs and a matching headpiece. the woman has her hair styled in an updo, adorned with a gold accessory. her makeup is done in a way that accentuates her features, with red lipstick and dark eyeshadow. she is looking directly at the camera with a neutral expression. the room has a rustic feel, with wooden beams and a stone wall visible in the background. the lighting in the room is soft and warm, creating a contrast with the woman's vibrant attire. there are no texts or other objects in the video. the style of the video is a portrait, focusing on the woman and her attire.

ref image:
![IMG_1664](https://github.com/hpcaitech/Open-Sora/assets/19588395/bc37ff22-6a39-47dd-8574-744bffc51099)

inference result:

https://github.com/hpcaitech/Open-Sora/assets/19588395/a7887fe1-b7b4-47da-a6e6-04022f8de0a2

**Comment by JThh** [comment]
#550
