### ISSUE TITLE
[Feature] MLX backend

### ISSUE THREAD

**Issue by awni** [hpcaitech/Open-Sora#555]
Any interest in doing an MLX back-end so we can run this efficiently on Apple silicon?

[MLX docs](https://ml-explore.github.io/mlx/)

**Comment by mark-lord** [comment]
Would be huge to see this, M2 Ultras would be great considering the huge amount of URAM

**Comment by Emasoft** [comment]
The M4 on my iPad is a monster. It would be great to leverage that power using an iPad M4 farm...

**Comment by lin72h** [comment]
Running on MLX is a very approachable for ML researcher, please consider support it

**Comment by ashran** [comment]
I'd love to see it happen. Apple Silicon's massive memory is extremely suitable for this kind of project.

**Comment by jsavva** [comment]
That would be terrific to see.  And I think it would really jumpstart usage of the model.  Please consider supporting!

**Comment by ivanfioravanti** [comment]
This would be incredible! 192GB on M2 Ultra makes Apple Silicon + MLX a real AI Powerhouse!

**Comment by FrankLeeeee** [comment]
Thanks for your issue. We are still working on further model performance improvement so I am afraid M2 ultra won't be supported in the near future. If you are interested in working on this, please feel free to send a PR to this repo. :)

**Comment by awni** [comment]
For reference I implemented this model in MLX. You can try it here: https://github.com/awni/mlx-examples/tree/open_sora/open_sora.

- On an M2 Ultra it can take anywhere from a minute to several minutes depending on the resolution and length of video
- The quality is hit-or-miss, hopefully that will improve with v1.2 or higher

**Comment by redpanda3** [comment]
> For reference I implemented this model in MLX. You can try it here: https://github.com/awni/mlx-examples/tree/open_sora/open_sora.
> 
> * On an M2 Ultra it can take anywhere from a minute to several minutes depending on the resolution and length of video
> * The quality is hit-or-miss, hopefully that will improve with v1.2 or higher

Hi, where is the model file located?

**Comment by redpanda3** [comment]
How to generate more seconds?

> For reference I implemented this model in MLX. You can try it here: https://github.com/awni/mlx-examples/tree/open_sora/open_sora.
> 
> * On an M2 Ultra it can take anywhere from a minute to several minutes depending on the resolution and length of video
> * The quality is hit-or-miss, hopefully that will improve with v1.2 or higher

**Comment by redpanda3** [comment]
> For reference I implemented this model in MLX. You can try it here: https://github.com/awni/mlx-examples/tree/open_sora/open_sora.
> 
> * On an M2 Ultra it can take anywhere from a minute to several minutes depending on the resolution and length of video
> * The quality is hit-or-miss, hopefully that will improve with v1.2 or higher

Feels great, Is there any possibility of integrating in Comfyui?
