### ISSUE TITLE
Not stable in WSL ubuntu with shared memory.

### ISSUE THREAD

**Issue by CQSim** [hpcaitech/Open-Sora#556]
Hello, I have install Opensora in WSL2 which can share memory with GPU. But it just work occasionally.   Most of the time, it comes with some error like below. Would anyone help me to solve this!

`  File "/home/tiy/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/home/tiy/miniconda3/envs/opensora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 915, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB. GPU`

**Comment by pbz134** [comment]
This indicates that your GPU doesn't have enough RAM (VRAM) to use the program. You need at least 27 GB for 360p generation, and 41 GB for 720p generation.

**Comment by CQSim** [comment]
> This indicates that your GPU doesn't have enough RAM (VRAM) to use the program. You need at least 27 GB for 360p generation, and 41 GB for 720p generation.

![Screenshot 2024-06-28 104743](https://github.com/hpcaitech/Open-Sora/assets/45313107/5b876c2c-ecbb-4835-a05d-daf7a88b3024)
That is the reasion I chosen WSL to run opensora. My Windows system have 64G memory and half of it could be shared to the GPU. 
Although my graphic card just have 11G memory, it can be load some times. Please see the picture. Most of the time, it come out with "CUDA out of memory".
