### ISSUE TITLE
training batch为 0，是因为我的训练数据集太少了吗？

### ISSUE THREAD

**Issue by xbyym** [hpcaitech/Open-Sora#561]
![image](https://github.com/hpcaitech/Open-Sora/assets/104976778/2662cbbf-2da1-4210-9699-62ea6547210a)
我的csv文件是：
![image](https://github.com/hpcaitech/Open-Sora/assets/104976778/d2ba4672-b05e-4279-800e-2dc3b3626a33)

**Comment by 281LinChenjian** [comment]
我也遇到了类似的问题，请问您已经找到问题所在了吗？
