### ISSUE TITLE
图像和视频联合比例的问题

### ISSUE THREAD

**Issue by lezasantaizi** [hpcaitech/Open-Sora#568]
你好，请教一下：
1.看到代码中dataset有对图像处理的代码，但是在训练的脚本中没有看到在任何地方输入图片csv，是不是图像和视频的csv文件是混合在一起成一个大的csv？
2. 如果是图像和视频联合训练的话，那么各个阶段图像和视频的比例分别是多少？

**Comment by Yanjia0** [comment]
1. 是的，在大规模训练的阶段我们有将图像和视频混训，此举有利于节约计算资源提高计算效率
2. 我们暂时没有公开的相关数据，您可以保持关注

**Comment by JThh** [comment]
I think this issue has been resolved by @Yanjia0 . Thanks!
