### ISSUE TITLE
The network architecture of Opensora 1.2 has changed

### ISSUE THREAD

**Issue by liang-jinli** [hpcaitech/Open-Sora#569]
First of all, we greatly appreciate such outstanding work. We are currently using OpenSora for some experiments but have encountered an issue：

The network architecture of Opensora 1.2 is significantly different from previous versions. According to the report for version 1.0, it used the STDiT (Sequential) structure. However, in version 1.2, it seems to have reverted to the Latte structure. Could you explain why this change was made? Do new experiments show that the Latte structure performs better?

**Comment by henbucuoshanghai** [comment]
u can change it as yourself?

**Comment by liang-jinli** [comment]
> u can change it as yourself?

Mainly want to know what is the specific reason for doing this?

**Comment by JThh** [comment]
I did not see many references to using Latte in our latest report. Can you kindly refer me to those? As mentioned in [report01.md](https://github.com/hpcaitech/Open-Sora/blob/ee909a7d6611bcc9c5cf1ac055a7e9cc74157e09/docs/report_01.md): `As shown in the figure, we insert a temporal attention right after each spatial attention in STDiT (ST stands for spatial-temporal). This is similar to variant 3 in Latte's paper. However, we do not control a similar number of parameters for these variants. While Latte's paper claims their variant is better than variant 3, our experiments on 16x256x256 videos show that with same number of iterations, the performance ranks as: DiT (full) > STDiT (Sequential) > STDiT (Parallel) ≈ Latte. Thus, we choose STDiT (Sequential) out of efficiency. Speed benchmark is provided [here](/docs/acceleration.md#efficient-stdit).`

**Comment by liang-jinli** [comment]
It's precisely because the report doesn't mention it that it seems even more strange. In the code implementation, OpenSora1.2 returns to using the structure of Latte's variant 3, but the report doesn't explain the reason for this decision.
And also, is there any experiment that can prove that the structure of OpenSora1.2 (i.e., Latte) is better?

**Comment by liang-jinli** [comment]
> I did not see many references to using Latte in our latest report. Can you kindly refer me to those? As mentioned in [report01.md](https://github.com/hpcaitech/Open-Sora/blob/ee909a7d6611bcc9c5cf1ac055a7e9cc74157e09/docs/report_01.md): `As shown in the figure, we insert a temporal attention right after each spatial attention in STDiT (ST stands for spatial-temporal). This is similar to variant 3 in Latte's paper. However, we do not control a similar number of parameters for these variants. While Latte's paper claims their variant is better than variant 3, our experiments on 16x256x256 videos show that with same number of iterations, the performance ranks as: DiT (full) > STDiT (Sequential) > STDiT (Parallel) ≈ Latte. Thus, we choose STDiT (Sequential) out of efficiency. Speed benchmark is provided [here](/docs/acceleration.md#efficient-stdit).`

**Comment by liang-jinli** [comment]
> I did not see many references to using Latte in our latest report. Can you kindly refer me to those? As mentioned in [report01.md](https://github.com/hpcaitech/Open-Sora/blob/ee909a7d6611bcc9c5cf1ac055a7e9cc74157e09/docs/report_01.md): `As shown in the figure, we insert a temporal attention right after each spatial attention in STDiT (ST stands for spatial-temporal). This is similar to variant 3 in Latte's paper. However, we do not control a similar number of parameters for these variants. While Latte's paper claims their variant is better than variant 3, our experiments on 16x256x256 videos show that with same number of iterations, the performance ranks as: DiT (full) > STDiT (Sequential) > STDiT (Parallel) ≈ Latte. Thus, we choose STDiT (Sequential) out of efficiency. Speed benchmark is provided [here](/docs/acceleration.md#efficient-stdit).`

It's precisely because the report doesn't mention it that it seems even more strange. In the code implementation, OpenSora1.2 returns to using the structure of Latte's variant 3, but the report doesn't explain the reason for this decision.
And also, is there any experiment that can prove that the structure of OpenSora1.2 (i.e., Latte) is better?

**Comment by henbucuoshanghai** [comment]
maybe this reason

**Comment by Edwardmark** [comment]
I also found that.
