### ISSUE TITLE
ViT architecture and dynamic resolution

### ISSUE THREAD

**Issue by JohnnyRacer** [hpcaitech/Open-Sora#57]
Hello, I was wondering why [NaViT](https://arxiv.org/pdf/2307.06304.pdf) or an architecture similar to it was not used as the vision transformer architecture. NaViT natively (hence native resolution) supports multi-resolution training as one of its defining features and a similar architecture was used for OpenAI's Sora to allow for good visual fidelity with differing resolutions. In the Latte paper [here](https://arxiv.org/pdf/2401.03048v1.pdf) section 4.1 it states that the model was trained only on square images/videos and would require resizing to process non-square images/videos.

**Comment by zhengzangw** [comment]
NaViT's structure without good system acceleration may lead to poor GPU utilization. For now, we focus on the video quality first, and thus delay the support for NaViT.
