### ISSUE TITLE
How could I load pretrained STDIT ckpt for stage3 training? 

### ISSUE THREAD

**Issue by CIntellifusion** [hpcaitech/Open-Sora#570]
在luchen cloud 上微调opensora的时候
请问如何指定--ckpt-path这个参数呢？ 无论是指定
--ckpt-path /root/commonData/OpenSora-STDiT-v3
--ckpt-path /root/commonData/OpenSora-STDiT-v3/model.safetensors
--ckpt-path xx/model.pth (safetensor转的pth)
都会报错

ckpt_utils.py也看了 完全封装起来了，没找到修改的地方 谢谢

**Comment by CIntellifusion** [comment]
torchrun --standalone --nproc_per_node 8 scripts/train.py \
    configs/opensora-v1-2/train/stage1.py --data-path YOUR_CSV_PATH --ckpt-path YOUR_PRETRAINED_CKPT
训练环境是luchen的官方环境，训练代码用的是这个

**Comment by CIntellifusion** [comment]
This issue has been solved by loading from huggingface checkpoint. However loading from Opensora mirror from luchen cloud is still not working.

**Comment by 281LinChenjian** [comment]
> This issue has been solved by loading from huggingface checkpoint. However loading from Opensora mirror from luchen cloud is still not working.

Can you explain in more detail how this parameter --ckpt-path is set? I don't know how to load from huggingface checkpoint.

**Comment by CIntellifusion** [comment]
> > This issue has been solved by loading from huggingface checkpoint. However loading from Opensora mirror from luchen cloud is still not working.
> 
> Can you explain in more detail how this parameter --ckpt-path is set? I don't know how to load from huggingface checkpoint.

--ckpt-path hpcai-tech/Open-Sora
if your machine has direct access to hugging face , it will download model automatically for you ;
otherwise you may need to export HF_ENDPOINT="https://hf-mirror.com or something else to download the model

**Comment by JonathanLi19** [comment]
请问为什么看上去--ckpt-path这个参数只在opensora/utils/config_utils.py这里出现了一次，感觉没用到啊？
感觉应该在config中用load参数？
