### ISSUE TITLE
推理时对z做concat的意义是什么？

### ISSUE THREAD

**Issue by forevergj** [hpcaitech/Open-Sora#571]
![image](https://github.com/hpcaitech/Open-Sora/assets/43092496/45b08938-1323-467e-9e8a-b4119b0f0913)
1.为什么这里对z进行concat，然后有对模型输出结果pred做chunk？
我的例子：
运行推理
`python3 scripts/inference.py configs/opensora-v1-2/inference/sample.py --num-frames 120 --image-size 640 640 --sample-name connect --prompt 'Generate a video of the motion of the meteorological radar precipitation field based on the given meteorological precipitation field map at a certain moment.{"reference_path": "./resized_image.png;./resized_image1.png","mask_strategy": "0;0,1,0,-1,1"}'`
2.模型的condition包括哪些内容，包括text，image，位置编码，fps？

**Comment by narrowsnap** [comment]
I think the comments have already been written addressing classifier-free guidance. One for text condition and another do uncondition.

**Comment by narrowsnap** [comment]
注释有写，这里是做classifier-free guidance，前一个z做有文本条件预测，后一个做无条件预测；对模型输出做chunk是因为输入z的shape是(2, 4, c, h, w)，输出为(2, 8, c, h, w)，只取前4个通道
<img width="1061" alt="Screenshot 2024-07-09 at 19 13 43" src="https://github.com/hpcaitech/Open-Sora/assets/17559987/bd932d0c-b732-431b-b2b0-e5859ff3be69">

**Comment by FrankLeeeee** [comment]
I will close this for now as @narrowsnap has answer the question well. 👏

**Comment by forevergj** [comment]
> 注释有写，这里是做classifier-free guidance，前一个z做有文本条件预测，后一个做无条件预测；对模型输出做chunk是因为输入z的shape是(2, 4, c, h, w)，输出为(2, 8, c, h, w)，只取前4个通道 

感谢您的回复，请问为什么只取前4个通道，后4个通道没有意义吗？

**Comment by hello-bluedog** [comment]
确实，后四个通道貌似没有意义

**Comment by hello-bluedog** [comment]
为什么不在模型结构中把它去掉呢

**Comment by narrowsnap** [comment]
> > 注释有写，这里是做classifier-free guidance，前一个z做有文本条件预测，后一个做无条件预测；对模型输出做chunk是因为输入z的shape是(2, 4, c, h, w)，输出为(2, 8, c, h, w)，只取前4个通道
> 
> 感谢您的回复，请问为什么只取前4个通道，后4个通道没有意义吗？

原始DiT训练的时候设置pred_sigma参数，输出8个通道，前4个为mean，后四个为variance，Open-Sora中pred_sigma默认为True，但是只取前四个通道作为预测noise，可能是训练时候没有修改吧
