### ISSUE TITLE
Problemas en linux mint: sistema deja de bootear

### ISSUE THREAD

**Issue by heraclitoprimo** [hpcaitech/Open-Sora#572]
Desde que instalé las librerías requeridas, mi sistema dejó de funcionar. Utilizo Linux Mint 20 Ulyana, con una Nvidia 1650. A alguien más le pasó? Gracias

**Comment by Yanjia0** [comment]
Pouvez-vous nous dire quelle bibliothèque vous rencontrez des difficultés pour installer ? 
De plus, nous vous recommandons d'utiliser une carte graphique à carte unique 80GA100 ou supérieure pour exécuter Open-Sora. Si les performances de votre carte graphique sont inférieures à nos recommandations, vous risquez de rencontrer des problèmes inconnus et de devoir utiliser plusieurs cartes pour l'exécuter.
（P.S. Cette réponse utilise Google Translate）

**Comment by heraclitoprimo** [comment]
Gracias por la respuesta. Luego de instalar los reuirements.txt al rebootear, no volvió a funcionar correctamente. De todas formas, haré un backup y reinstalaré el sistema. Sería genial ampliar la documentación para evitar estos malos momentos. De hecho, ni siquiera pude correr open sora...

**Comment by FrankLeeeee** [comment]
@heraclitoprimo 
¿Aún encuentras algún problema? No dudes en hacérmelo saber. (traducido a través del Traductor de Google)
