### ISSUE TITLE
The reason why crossatten views the batch dimension as 1

### ISSUE THREAD

**Issue by oceanogeology** [hpcaitech/Open-Sora#574]
Here's the MultiHeadCrossAttention code:
```python
q = self.q_linear(x).view(1, -1, self.num_heads, self.head_dim) 
kv = self.kv_linear(cond).view(1, -1, 2, self.num_heads, self.head_dim)
k, v = kv.unbind(2) 
attn_bias = None
if mask is not None:
    attn_bias = xformers.ops.fmha.BlockDiagonalMask.from_seqlens([N] * B, mask)
x = xformers.ops.memory_efficient_attention(q, k, v, p=self.attn_drop.p, attn_bias=attn_bias)
x = x.view(B, -1, C)
```
If the batch dimensions of q, k, and v are all placed in the second dimension, with the first dimension remaining unchanged at 1, won't this mess up the information of different videos and images within a batch? I see that the mask in attn_bias carries the batch dimension information. Is it that during efficient computation, the attn_bias parameter controls the computation for different batches? If so, how does it ensure that the information remains organized?

**Comment by oceanogeology** [comment]
mask:
[207, 104, 108, 102, 87, 84, 196, 82, 196, 216, 205, 182, 84, 215, 76, 99, 190, 32, 98, 129, 58, 95, 112, 97]

attn_bias:
BlockDiagonalMask(q_seqinfo=_SeqLenInfo(seqstart=tensor([    0,  3600,  7200, 10800, 14400, 18000, 21600, 25200, 28800, 32400,
        36000, 39600, 43200, 46800, 50400, 54000, 57600, 61200, 64800, 68400,
        72000, 75600, 79200, 82800, 86400], dtype=torch.int32), max_seqlen=3600, min_seqlen=3600, seqstart_py=[0, 3600, 7200, 10800, 14400, 18000, 21600, 25200, 28800, 32400, 36000, 39600, 43200, 46800, 50400, 54000, 57600, 61200, 64800, 68400, 72000, 75600, 79200, 82800, 86400]), k_seqinfo=_SeqLenInfo(seqstart=tensor([   0,  207,  311,  419,  521,  608,  692,  888,  970, 1166, 1382, 1587,
        1769, 1853, 2068, 2144, 2243, 2433, 2465, 2563, 2692, 2750, 2845, 2957,
        3054], dtype=torch.int32), max_seqlen=216, min_seqlen=32, seqstart_py=[0, 207, 311, 419, 521, 608, 692, 888, 970, 1166, 1382, 1587, 1769, 1853, 2068, 2144, 2243, 2433, 2465, 2563, 2692, 2750, 2845, 2957, 3054]), _batch_sizes=None)

**Comment by oceanogeology** [comment]
I compared the method of keeping B in the first dimension with the author's method:

xx = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=None)
xx = xx.view(B, -1, C)
suppose q.shape = torch.Size([5, 57600, 16, 72]) k.shape = torch.Size([5, 512, 16, 72]), v.shape =torch.Size([5, 512, 16, 72])
xx1 = xformers.ops.memory_efficient_attention(q, k, v, p=self.attn_drop.p, attn_bias=attn_bias)
xx1 = xx1.view(B, -1, C)
suppose q.shape = torch.Size([1, 288000, 16, 72]) k.shape = torch.Size([1, 2560, 16, 72]) v.shape = torch.Size([1, 2560, 16, 72])

Ultimately, the values at the same positions in xx and xx1 are different:
xx.shape
torch.Size([5, 57600, 1152])
xx[0][5:10][:,5:10]
tensor([[-6.5994e-04, -8.2397e-04,  9.2316e-04, -2.5330e-03, -6.0558e-05],
        [-6.6376e-04, -8.5068e-04,  9.4223e-04, -2.5330e-03, -5.1022e-05],
        [-6.6376e-04, -8.4686e-04,  9.4223e-04, -2.5330e-03, -5.6267e-05],
        [-6.6376e-04, -8.5449e-04,  9.3460e-04, -2.5330e-03, -4.9114e-05],
        [-6.8665e-04, -7.8964e-04,  9.0408e-04, -2.5482e-03, -7.8678e-05]],
       device='cuda:0', dtype=torch.bfloat16)
xx1[0][5:10][:,5:10]
tensor([[ 0.0010, -0.0002,  0.0002, -0.0016, -0.0016],
        [ 0.0010, -0.0002,  0.0002, -0.0016, -0.0016],
        [ 0.0010, -0.0002,  0.0002, -0.0016, -0.0016],
        [ 0.0010, -0.0002,  0.0002, -0.0016, -0.0016],
        [ 0.0010, -0.0002,  0.0002, -0.0016, -0.0016]], device='cuda:0',
       dtype=torch.bfloat16)

**Comment by JThh** [comment]
Thanks. I believe they are only the same when batch size equals one.

Could @zhengzangw please take confirm?

**Comment by kkahatapitiya** [comment]
Based on the explanation [here](https://facebookresearch.github.io/xformers/components/ops.html#xformers.ops.fmha.attn_bias.BlockDiagonalMask), I think this implementation computes the cross attention as intended (separately for each batch element, which is implemented as a large-but-masked attention matrix).

**Comment by zhengzangw** [comment]
This is intended, the cross attention is done via xformers:
- Given q of shape [B, N, C], where not each sample in the batch uses the full N tokens (there are paddings)
- reshape to [1, sum(n_i), C], where padding is removed
- give [n_1, n_2, ..., n_B] as mask, then xformers will handle accordingly.
