### ISSUE TITLE
t5 fp16 safetensor not work any help

### ISSUE THREAD

**Issue by al-swaiti** [hpcaitech/Open-Sora#576]
i wish if there any way to make t5 text encoder fp16 safetensor work !

**Comment by JThh** [comment]
I believe it is already been possible: https://github.com/hpcaitech/Open-Sora/blob/ee909a7d6611bcc9c5cf1ac055a7e9cc74157e09/opensora/models/text_encoder/t5.py#L44.

**Comment by al-swaiti** [comment]
thanks
