### ISSUE TITLE
How to control the FPS of the generated video using the command line options?

### ISSUE THREAD

**Issue by jiacxie** [hpcaitech/Open-Sora#577]
As title, or if we cannot use command line options but we can use config file, please let me know. Thanks.

**Comment by JThh** [comment]
Would [this](https://github.com/hpcaitech/Open-Sora/blob/ee909a7d6611bcc9c5cf1ac055a7e9cc74157e09/configs/opensora-v1-2/inference/sample.py#L4) be what you intend?

**Comment by jiacxie** [comment]
Thank you!
