### ISSUE TITLE
请问如果用pixart-sigma模型作为config，可以选择num_frames fps>1生成视频吗

### ISSUE THREAD

**Issue by foreverpiano** [hpcaitech/Open-Sora#579]
/workspace/Open-Sora/configs/pixart/inference/1x2048MS.py config在这里

**Comment by foreverpiano** [comment]
还是说当前框架仅支持这个模型生成图像？
@zhengzangw @Shen-Chenhui

**Comment by foreverpiano** [comment]
另外直接运行会报错 Traceback (most recent call last):
  File "/workspace/Open-Sora/scripts/inference.py", line 304, in <module>
    main()
  File "/workspace/Open-Sora/scripts/inference.py", line 266, in main
    samples = scheduler.sample(
  File "/workspace/Open-Sora/opensora/schedulers/dpms/__init__.py", line 27, in sample
    assert mask is None, "mask is not supported in dpm-solver"
AssertionError: mask is not supported in dpm-solver

**Comment by zhengzangw** [comment]
> 还是说当前框架仅支持这个模型生成图像？ @zhengzangw @Shen-Chenhui

pixart 这个模型仅支持生成图像。所以 num_frames 和 fps 都固定即可。除非你用这个模型自己训练了视频，才可以修改并生成。

**Comment by zhengzangw** [comment]
> 另外直接运行会报错 Traceback (most recent call last): File "/workspace/Open-Sora/scripts/inference.py", line 304, in main() File "/workspace/Open-Sora/scripts/inference.py", line 266, in main samples = scheduler.sample( File "/workspace/Open-Sora/opensora/schedulers/dpms/**init**.py", line 27, in sample assert mask is None, "mask is not supported in dpm-solver" AssertionError: mask is not supported in dpm-solver

该问题最新版已经修复。
