### ISSUE TITLE
A million-scale text-to-video prompt-gallery dataset

### ISSUE THREAD

**Issue by WangWenhao0716** [hpcaitech/Open-Sora#58]
Hi, 
We contribute the first dataset featuring 1.67 million unique text-to-video prompts and 6.69 million videos generated from 4 different state-of-the-art diffusion models. We hope it can help your Open-Sora plan.

Title：VidProM: A Million-scale Real Prompt-Gallery Dataset for Text-to-Video Diffusion Models

Arxiv：https://arxiv.org/abs/2403.06098

Project：https://github.com/WangWenhao0716/VidProM

Download：https://huggingface.co/datasets/WenhaoWang/VidProM

**Comment by binmakeswell** [comment]
Hi @WangWenhao0716 Thank you very much for your contribution!

**Comment by zhengzangw** [comment]
Thank you, we have added it to the watch list in [dataset.md](https://github.com/hpcaitech/Open-Sora/blob/main/docs/datasets.md).

**Comment by WangWenhao0716** [comment]
thanks
