### ISSUE TITLE
Dose detailed caption improve the performance?

### ISSUE THREAD

**Issue by g-jing** [hpcaitech/Open-Sora#582]
I have a few questions about the video caption.

1. I noticed that during the training, the caption in the video CSV is quiet short. Will the performance improve if we use a detailed caption during the test time?
2. If we also use detailed caption during the training time, will that improve the model performance?
3. The caption used now focuses more on the frame description rather than the video dynamics. Will that be improved with a capture describing the dynamics? If so, do you have any suggestions on generating that captions?

Thanks a lot!

**Comment by JThh** [comment]
I believe your concerns are all valid. For the first point, detailed prompt is more likely to help you get the desired video configurations that are not explicitly set in args. You may see how prompts are being refined: https://github.com/hpcaitech/Open-Sora/blob/main/scripts/inference.py#L232.

**Comment by JThh** [comment]
Maybe @zhengzangw can help on the other points regarding training.

**Comment by zhengzangw** [comment]
These are very open questions. For the second question, we are also not sure. But for the third one, I think it will.

**Comment by g-jing** [comment]
> These are very open questions. For the second question, we are also not sure. But for the third one, I think it will.

For the third one, do you mean using captions to describe the dynamics during **only inference time or during both training and test time**? Thanks

**Comment by FrankLeeeee** [comment]
> > These are very open questions. For the second question, we are also not sure. But for the third one, I think it will.
> 
> For the third one, do you mean using captions to describe the dynamics during **only inference time or during both training and test time**? Thanks

You need to describe the dynamics in the training prompts as well.

**Comment by g-jing** [comment]
> > > These are very open questions. For the second question, we are also not sure. But for the third one, I think it will.
> > 
> > 
> > For the third one, do you mean using captions to describe the dynamics during **only inference time or during both training and test time**? Thanks
> 
> You need to describe the dynamics in the training prompts as well.

Do you think there will be an improvement in using only the dynamics caption during the test time? Hard to get resources to re-train OpenSora. Could you share more insights/analysis about it? Thanks!

**Comment by FrankLeeeee** [comment]
We never tried it, I would say possible, but did not test it on our side. You may try. Anyway, our weights are trained on prompts with dynamics such as camera motion, you can use our weights directly.

**Comment by g-jing** [comment]
I noticed that OpenSora is using LLava-1.6 to provide the caption. Do you have any suggestions on models or methods for how to get a caption focusing on the dynamics of the video? For example, the moving direction of the object, the detailed shape variation, etc.

**Comment by FrankLeeeee** [comment]
> I noticed that OpenSora is using LLava-1.6 to provide the caption. Do you have any suggestions on models or methods for how to get a caption focusing on the dynamics of the video? For example, the moving direction of the object, the detailed shape variation, etc.

You might want to consider pllava for video captioning.
