### ISSUE TITLE
潞晨云启动报错

### ISSUE THREAD

**Issue by topshu** [hpcaitech/Open-Sora#585]
OSError: Incorrect path_or_model_id: '/root/commonData/OpenSora-VAE-v1.2'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

公共数据里面没有这个文件，我到目录下确认了

我用的是最新的opensora1.2镜像，创建实例时，也选择了加载公开数据，这是默认勾选的

**Comment by topshu** [comment]
我用的是最新的opensora1.2镜像

**Comment by topshu** [comment]
创建实例时，也选择了加载公开数据，这是默认勾选的

**Comment by JThh** [comment]
Can @zhengzangw please help confirm? Or @topshu you may ask in our cloud platform service group: https://wj.qq.com/s2/14488320/rlq7/.

**Comment by topshu** [comment]
> Can @zhengzangw please help confirm? Or @topshu you may ask in our cloud platform service group: https://wj.qq.com/s2/14488320/rlq7/.

OK

**Comment by FrankLeeeee** [comment]
@topshu are you able to solve your problem?

**Comment by topshu** [comment]
> @topshu are you able to solve your problem?
do you fix it?

**Comment by topshu** [comment]
bug still exists @FrankLeeeee @JThh

**Comment by CZYCW** [comment]
> bug still exists @FrankLeeeee @JThh

Do you mind sharing your notebook id？We can investigate it in our backend. Thanks!

**Comment by topshu** [comment]
> > bug still exists @FrankLeeeee @JThh
> 
> Do you mind sharing your notebook id？We can investigate it in our backend. Thanks!

The current issue is that the Open-Sora1.2 image you published on Lucent Cloud cannot be used. An error is reported as soon as it starts:
OSError: Incorrect path_or_model_id: '/root/commonData/OpenSora-VAE-v1.2'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

There is no such file in the public data, and I have confirmed this in the directory.

I am using the latest OpenSora1.2 image, and when creating an instance, I also selected to load public data, which is the default option.
