### ISSUE TITLE
镜像的Python是3.10 文档的Python是3.9

### ISSUE THREAD

**Issue by CIntellifusion** [hpcaitech/Open-Sora#589]
请问为什么luchen上的镜像和文档提供的环境描述不一样 
这会引起潜在的问题吗？ 我在A100上按照仓库里的环境进行搭建，在多卡训练的时候遇到了通讯问题

**Comment by JThh** [comment]
It should be okay since I can run on my machine with python version `3.10`; also, refer to https://github.com/hpcaitech/Open-Sora/blob/ee909a7d6611bcc9c5cf1ac055a7e9cc74157e09/docs/zh_CN/READMEv1.1.md?plain=1#L96.

**Comment by CIntellifusion** [comment]
Thanks, but I suspect this would be one potential reason of this warning  `CUD STATUS NOT SUPPORTED` ? 
![2f09095c0c40b42d8aeaa946eb434a9](https://github.com/hpcaitech/Open-Sora/assets/96377955/b3783557-49ea-45e8-bfc6-079c363689eb)

**Comment by FrankLeeeee** [comment]
This is a warning which you can safely ignore.

**Comment by CIntellifusion** [comment]
Thanks. Then I think the training bugs may have other reasons. [multi gpu training issue](https://github.com/hpcaitech/Open-Sora/issues/565)
