### ISSUE TITLE
H100 support?

### ISSUE THREAD

**Issue by sjtuzq** [hpcaitech/Open-Sora#59]
Hi, thanks for your great work! This is super useful, however, one minor issue is, it seems that this framework can only support A100 node, and get stuck on H100 node, I wonder whether the H100 support feature is undergoing or not?

**Comment by binmakeswell** [comment]
Hi @sjtuzq We are running well on a cluster NV H GPUs. 
Could you please provide more details about your issue? 
This helps us investigate and reproduce. Thanks.

**Comment by zhengzangw** [comment]
We run our experiments on NV H GPUs. Our code supports H100 training.

**Comment by zoelearner** [comment]
Does it the cuda version need to be 12.4? 
Cuda 12.1 cannot works with a problem of core dump.
