### ISSUE TITLE
OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by horrybe** [hpcaitech/Open-Sora#590]
/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
[rank0]:     conn = connection.create_connection(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
[rank0]:     raise err
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
[rank0]:     sock.connect(sa)
[rank0]: OSError: [Errno 113] No route to host

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
[rank0]:     httplib_response = self._make_request(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
[rank0]:     self._validate_conn(conn)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
[rank0]:     conn.connect()
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
[rank0]:     self.sock = conn = self._new_conn()
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
[rank0]:     raise NewConnectionError(
[rank0]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1fd6d67250>: Failed to establish a new connection: [Errno 113] No route to host

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
[rank0]:     resp = conn.urlopen(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/connectionpool.py", line 801, in urlopen
[rank0]:     retries = retries.increment(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/urllib3/util/retry.py", line 594, in increment
[rank0]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[rank0]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers/resolve/main/vae/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1fd6d67250>: Failed to establish a new connection: [Errno 113] No route to host'))

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
[rank0]:     metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
[rank0]:     r = _request_wrapper(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
[rank0]:     response = _request_wrapper(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
[rank0]:     response = get_session().request(method=method, url=url, **params)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
[rank0]:     resp = self.send(prep, **send_kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
[rank0]:     r = adapter.send(request, **kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
[rank0]:     return super().send(request, *args, **kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
[rank0]:     raise ConnectionError(e, request=request)
[rank0]: requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers/resolve/main/vae/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1fd6d67250>: Failed to establish a new connection: [Errno 113] No route to host'))"), '(Request ID: 77508ba0-d6d6-402a-8c5e-462118e02ea8)')

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 380, in load_config
[rank0]:     config_file = hf_hub_download(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
[rank0]:     return _hf_hub_download_to_cache_dir(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
[rank0]:     _raise_on_head_call_error(head_call_error, force_download, local_files_only)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
[rank0]:     raise LocalEntryNotFoundError(
[rank0]: huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/hbx/txt2vid/Open-Sora/scripts/train.py", line 409, in <module>
[rank0]:     main()
[rank0]:   File "/data/hbx/txt2vid/Open-Sora/scripts/train.py", line 127, in main
[rank0]:     vae = build_module(cfg.get("vae", None), MODELS)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/opensora/registry.py", line 24, in build_module
[rank0]:     return builder.build(cfg)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank0]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank0]:     obj = obj_cls(**args)  # type: ignore
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/opensora/models/vae/vae.py", line 284, in OpenSoraVAE_V1_2
[rank0]:     model = VideoAutoencoderPipeline(config)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/opensora/models/vae/vae.py", line 153, in __init__
[rank0]:     self.spatial_vae = build_module(config.vae_2d, MODELS)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/opensora/registry.py", line 24, in build_module
[rank0]:     return builder.build(cfg)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
[rank0]:     return self.build_func(cfg, *args, **kwargs, registry=self)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
[rank0]:     obj = obj_cls(**args)  # type: ignore
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/opensora/models/vae/vae.py", line 19, in __init__
[rank0]:     self.module = AutoencoderKL.from_pretrained(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 567, in from_pretrained
[rank0]:     config, unused_kwargs, commit_hash = cls.load_config(
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/data/hbx/envs/opensora/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 406, in load_config
[rank0]:     raise EnvironmentError(
[rank0]: OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json.
E0709 10:58:41.476000 139833254459200 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 1597631) of binary: /data/hbx/envs/opensora/bin/python
Traceback (most recent call last):
  File "/data/hbx/envs/opensora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/hbx/envs/opensora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/data/hbx/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/data/hbx/envs/opensora/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/data/hbx/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/hbx/envs/opensora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================

**Comment by timecoderr** [comment]
我也遇到了，一模一样，请问解决了吗？

**Comment by FrankLeeeee** [comment]
Hi, may I know which config file you are using?

You can check if you find any `local_files_only=False` in the config file, if so, you may remove them.
