### ISSUE TITLE
scripts/inference.py#推理时 len(prompts),是1？一个文本？

### ISSUE THREAD

**Issue by henbucuoshanghai** [hpcaitech/Open-Sora#594]
scripts/inference.py#L146C5-L146C64
 for i in progress_wrap(range(0, len(prompts), batch_size)):
此处是prompts的一个个单词一次只输进去一个？

   # == Iter over number of sampling for one prompt ==
        for k in range(num_sample):
一个单词生成结果，然后另一个单词继续？

**Comment by FrankLeeeee** [comment]
No, `prompts` is a list of prompts. For example:

```python
prompts = [
     "a boy is reading a book while sitting on cloud",
     "a car is running in the ocean behind some fish"
]
```
