### ISSUE TITLE
To long inference time

### ISSUE THREAD

**Issue by zhangshengjun2019** [hpcaitech/Open-Sora#595]
Hi! I wonder the normal inference time of this work. When I apply this work on a singel A6000 with 
`python scripts/inference.py configs/opensora-v1-2/inference/sample.py  --image-size 480 853`,
it shows that the total inference time is more than 20,000 hours. I wonder where is the bug?

**Comment by FrankLeeeee** [comment]
Hi, do you encounter the same issue if you lower the resolution?

**Comment by zhangshengjun2019** [comment]
Yes, if I lower the resolution from 480, 853 to 240, 427, the inference time decreases from 20,000 hours to 5,000 hours.

**Comment by FrankLeeeee** [comment]
Well, that is still strangely long... Do you find the training/inference speed normal for other models on your GPU?

**Comment by FrankLeeeee** [comment]
Or you can monitor the GPU utilisation on `nvidia-smi` while doing inference.

**Comment by zhangshengjun2019** [comment]
Yes, I conduct AnimateDiffusion also on this GPU, which only takes about 20s. During inference, it takes about 30GB.

**Comment by FrankLeeeee** [comment]
Ok, as we don't have A6000 on our side, it might be difficult to test it. Anyway, I will still run the repo from scratch to see if I can reproduce your problem.

**Comment by narrowsnap** [comment]
You must set prompt, otherwise the length of the prompt will set to 10000 by default.

**Comment by zhangshengjun2019** [comment]
Thanks. Actually, 20,000 hours is for 10,000 videos.
