### ISSUE TITLE
The video appears as a Mosaic

### ISSUE THREAD

**Issue by aoji0606** [hpcaitech/Open-Sora#599]
Why is this happening

https://github.com/hpcaitech/Open-Sora/assets/55875798/aa883dfc-dc2d-4608-b971-608af7c13222

**Comment by MikeAiJF** [comment]
你用的自己训练的模型吗

**Comment by aoji0606** [comment]
不是自己训的，用的OpenSora-VAE-v1.2、OpenSora-STDiT-v3、t5-v1_1-xxl这三个开源的

测试代码：
python scripts/inference.py configs/opensora-v1-2/inference/sample.py \
  --num-frames 4s --resolution 720p \
  --layernorm-kernel False --flash-attn False \
  --prompt "a beautiful waterfall"

**Comment by CIntellifusion** [comment]
你的机器和环境是什么样的呀

**Comment by aoji0606** [comment]
环境根据readme配置的，机器是a800，cuda12.1

**Comment by CIntellifusion** [comment]
你有没有尝试过用gradio/app.py在GUI里面生成一下，来检查你的ckpt是否正常；参考https://github.com/hpcaitech/Open-Sora/issues/477#issuecomment-2233732064

然后我试了我的机器上这条命令是没问题的python scripts/inference.py configs/opensora-v1-2/inference/sample.py --num-frames 2s --resolution 360p --layernorm-kernel False --flash-attn False --prompt "a beautiful waterfall" --save-dir ./outputs
