### ISSUE TITLE
Timestamp sample in rflow

### ISSUE THREAD

**Issue by jike5** [hpcaitech/Open-Sora#601]
Hello,

I encountered an issue while using your code for training. When the number of frames in a sample is greater than 1 but less than 17, num_frames becomes 0, causing ratio_time to be 0, which results in all new timestamps being 0. Could this lead to problems during training? All my training samples have 16 frames. Should I set use_timestep_transform to False?

https://github.com/hpcaitech/Open-Sora/blob/bf4d6673af9407650b2ce6250debc2453b82c572/opensora/schedulers/rf/rectified_flow.py#L31

**Comment by JThh** [comment]
No, I think any number of frames less than 17 should be considered one timestep. 

Can @zhengzangw please confirm this?

**Comment by zhengzangw** [comment]
Yes, directly using num_frames other than 17n frames leads to problems. Set `use_timestep_transform` to False is an easy solution. A better solution is that you can change the logic of calculating num_frames according to your frames, e.g.

```python
num_frames = model_kwargs["num_frames"] // 16 * 4
```

**Comment by jike5** [comment]
> Yes, directly using num_frames other than 17n frames leads to problems. Set `use_timestep_transform` to False is an easy solution. A better solution is that you can change the logic of calculating num_frames according to your frames, e.g.
> 
> ```python
> num_frames = model_kwargs["num_frames"] // 16 * 4
> ```

Got it. Thank you！
