### ISSUE TITLE
建议train脚本在保存模型权重时加save_total_limit功能，如果训练数据集、训练epoch较大，不对保存的权重数量加以限制，你的磁盘会很快被打满，除非磁盘容量很大，感谢你们的工作，但是代码仍需严谨和规范

### ISSUE THREAD

**Issue by FrankMinions** [hpcaitech/Open-Sora#603]

**Comment by FrankMinions** [comment]
我fork了你们的工作，并加入相关代码，如果需要快速使用的可以参考：[https://github.com/FrankMinions/Open-Sora/blob/bf4d6673af9407650b2ce6250debc2453b82c572/scripts/train.py](https://github.com/FrankMinions/Open-Sora/blob/bf4d6673af9407650b2ce6250debc2453b82c572/scripts/train.py)

**Comment by CIntellifusion** [comment]
I have encountered the same problem. Thanks for generously share your code.

**Comment by JThh** [comment]
Thanks. Can you help make a PR if you want?
