### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by HaoZhang990127** [hpcaitech/Open-Sora#613]
Hi,

Thank you for your nice work.

You used both video data and image data during training, what was your ratio of video to images at each stage? I am adding a lot of image data, specifically using 80k high-quality video data with aesthetics higher than 5.6 and 1.2 million image data with aesthetics higher than 5.6, but the image introduction didn't make the generation quality improve, may I ask how did you use the image data to improve the quality during the training process? What are your tips in introducing images for training?

Thank you so much.

**Comment by JThh** [comment]
Can @zhengzangw please take a look?

**Comment by zhengzangw** [comment]
In total, we use approximately 30M video data and 3M image data.

**Comment by leonardodora** [comment]
> In total, we use approximately 30M video data and 3M image data.

In your report, it said official panda 30m subset was used in stage2. But we couldn’t find any 30m subset in panda project. Could you please share the link of panda 30m?
