### ISSUE TITLE
OpenSora v1.2 only works `seed=42` on my local machine

### ISSUE THREAD

**Issue by spacegoing** [hpcaitech/Open-Sora#617]
Hi dev team,

Congrats on this awesome project!

I'm running opensora v1.2 on my local machine. It chimes when seed=42, resolution=1080p, sampling step=100!

However, if I change the inference seed to any other seed like 513 777 418 etc. The generated video is highly noised.

Any idea? Many tks!

**Comment by JThh** [comment]
This appears to be weird and I have not encountered similar issues in this community. 

Would you please share the highly noise samples with the commands to generate and random seeds you used? Would it be reproducible with any image or textual prompt you provide?

In the meanwhile, it'd be appreciated if @zhengzangw could provide their insights on this.

**Comment by zhengzangw** [comment]
I do not encounter this problem. Try delete this line:

https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/scripts/inference.py#L263

**Comment by spacegoing** [comment]
@JThh @zhengzangw 

Thanks for your reply. to reproduce u can use my docker image: spacegoing/opensora. It's basically official dockerfile plus sort out versions of conflicting deps.

the prompt I use is:

The camera moves smoothly, gliding over snow-capped peaks, dipping into deep valleys, and soaring past rocky cliffs with a clear blue sky above.

run it with seed=42, resolution=1080p, sampling step=100

the generated video is random noise

**Comment by spacegoing** [comment]
> I do not encounter this problem. Try delete this line:
> 
> https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/scripts/inference.py#L263

I'll try and let u know
