### ISSUE TITLE
Image2Video 图片生成视频的时候出现问题

### ISSUE THREAD

**Issue by tangdong1994** [hpcaitech/Open-Sora#618]
您好，非常感谢能够开源这个项目，我目前遇到一个问题就是使用图生视频的时候，出现视频生成有问题，全程基本上静止不动，我的配置参数完全按照你们的开源代码来设定的。有区别的地方是生成的图片的大小我改成了512x512；我是用的模型版本是v1.2的版本

https://github.com/user-attachments/assets/36f750d4-f716-44af-a3b2-261066511ed0

**Comment by MikeAiJF** [comment]
> 您好，非常感谢能够这个项目，我目前遇到的一个问题就是使用图生视频的时候，出现视频生成有问题，全程基本上不动，我的配置参数完全按照你们的开源代码来设置的。有区别的地方是生成的图片的大小我改成了512x512；我用的模型版本是v1.2的版本
> 
>  _side_A.breathtaking.sunrise.scene_yes_pose_0_0_0000.mp4

Their Tusheng videos are not perfect yet, and my Tusheng videos are even more outrageous.

**Comment by tangdong1994** [comment]
> > 您好，非常感谢能够这个项目，我目前遇到的一个问题就是使用图生视频的时候，出现视频生成有问题，全程基本上不动，我的配置参数完全按照你们的开源代码来设置的。有区别的地方是生成的图片的大小我改成了512x512；我用的模型版本是v1.2的版本
> > _side_A.breathtaking.sunrise.scene_yes_pose_0_0_0000.mp4
> 
> Their Tusheng videos are not perfect yet, and my Tusheng videos are even more outrageous.

Why can you understand the Chinese I send?  Okay, it seems I'm not the only one encountering this problem, so by the way, what's the situation with Tusheng Video here?

**Comment by henbucuoshanghai** [comment]
微信一下？我有些疑问可以互相交流。13052065916
