### ISSUE TITLE
Error in calculating the start index in the 'extract_feat' file

### ISSUE THREAD

**Issue by liyy96** [hpcaitech/Open-Sora#619]
> https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/scripts/misc/extract_feat.py#L118

`dataloader.batch_sampler.load_state_dict({"last_micro_batch_access_index": start_index})`

should be

`dataloader.batch_sampler.load_state_dict({"last_micro_batch_access_index": start_index * bin_size})`

**Comment by Space-Xun** [comment]
@liyy96 Hi, I think the problem you raised is what happens when feature extraction is unexpectedly interrupted. Looking forward to your reply.

**Comment by JThh** [comment]
Hi @liyy96, can you show your intuition why this change is necessary? Is `bin_size` not consistent with batch size?

If possible, you can make a pull request detailing your rationale!
