### ISSUE TITLE
timestep_transform中ratio_time 的计算

### ISSUE THREAD

**Issue by Taooooozi** [hpcaitech/Open-Sora#620]
在ratio_time的计算中有一步是num_frames = model_kwargs["num_frames"] // 17 * 5，我有两个疑问
(1) 为什么要使用整除，整除存在一定的风险，当帧数小于17时，会导致ratio变为0，t也变为0
(2)如果我要在自己的数据集微调模型，并且数据集中的视频都是帧数很少的（8帧），我应该如何修改ratio_time的计算公式比较合适。
以下是timestep_transform函数的完整代码
def timestep_transform(
    t,
    model_kwargs,
    base_resolution=512 * 512,
    base_num_frames=1,
    scale=1.0,
    num_timesteps=1,
):
    # Force fp16 input to fp32 to avoid nan output
    for key in ["height", "width", "num_frames"]:
        if model_kwargs[key].dtype == torch.float16:
            model_kwargs[key] = model_kwargs[key].float()

    t = t / num_timesteps
    resolution = model_kwargs["height"] * model_kwargs["width"]
    ratio_space = (resolution / base_resolution).sqrt()
    # NOTE: currently, we do not take fps into account
    # NOTE: temporal_reduction is hardcoded, this should be equal to the temporal reduction factor of the vae
    if model_kwargs["num_frames"][0] == 1:
        num_frames = torch.ones_like(model_kwargs["num_frames"])
    else:
        num_frames = model_kwargs["num_frames"] // 17 * 5
    ratio_time = (num_frames / base_num_frames).sqrt()

    ratio = ratio_space * ratio_time * scale
    new_t = ratio * t / (1 + (ratio - 1) * t)

    new_t = new_t * num_timesteps
    return new_t

**Comment by Polycoriander** [comment]
Hello,请问你解决这个问题了吗，我想生成16帧的视频
