### ISSUE TITLE
the dimensions of input video?

### ISSUE THREAD

**Issue by henbucuoshanghai** [hpcaitech/Open-Sora#622]
https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/opensora/models/stdit/stdit3.py#L364C8-L364C43
 T, H, W = self.get_dynamic_size(x)

        S = H * W
        base_size = round(S**0.5)
        resolution_sq = (height[0].item() * width[0].item()) ** 0.5
        scale = resolution_sq / self.input_sq_size
        pos_emb = self.pos_embed(x, H, W, scale=scale, base_size=base_size)

**Comment by henbucuoshanghai** [comment]
T, H, W = self.get_dynamic_size(x)
even in one batch, the input video embedding of T H W is different with each other?
every video has its own T W H?
so the input dimensions of STdit3.py is changee depend on  every video?

**Comment by henbucuoshanghai** [comment]
视频vae压缩后，维度一致？

**Comment by 3manifold** [comment]
> After video vae compression, are the dimensions consistent?

I also have the same question. What was the result for you?
