### ISSUE TITLE
Sequence parallel

### ISSUE THREAD

**Issue by Tianhao-Qi** [hpcaitech/Open-Sora#627]
Excuse me, when will open-sora support sequence parallel training?

**Comment by yjhong89** [comment]
Same question.
- Does OpenSora v1.2 supports sequence parallelism??

**Comment by ITerydh** [comment]
When using sequence parallelism, there is a problem where the sequence cannot be divided when sp>2. When will it be updated?

**Comment by JThh** [comment]
It is planned in the next release. Thanks!
