### ISSUE TITLE
loss of rectified_flow

### ISSUE THREAD

**Issue by henbucuoshanghai** [hpcaitech/Open-Sora#628]
add noise is timepoints * original_samples + (1 - timepoints) * noise？why？timepoints  is?
and (velocity_pred - (x_start - noise))?  why?
u write the ectified_flow code yourself?

**Comment by a5704607** [comment]
> add noise is timepoints * original_samples + (1 - timepoints) * noise？why？timepoints is? and (velocity_pred - (x_start - noise))? why? u write the ectified_flow code yourself?

timepoints * original_samples + (1 - timepoints) * noise  is based on SD3 Rectified Flow，but I cannot also understand velocity_pred - (x_start - noise), it seems not consistent with SD3.

**Comment by henbucuoshanghai** [comment]
and how to understand this code? three lines?why?
https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/opensora/schedulers/rf/__init__.py#L93

 dt = timesteps[i] - timesteps[i + 1] if i < len(timesteps) - 1 else timesteps[i]
            dt = dt / self.num_timesteps
            z = z + v_pred * dt[:, None, None, None, None]

**Comment by a5704607** [comment]
已收到，请放心。

**Comment by a5704607** [comment]
> and how to understand this code? three lines?why?
> 
> https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/opensora/schedulers/rf/__init__.py#L93
> 
> dt = timesteps[i] - timesteps[i + 1] if i < len(timesteps) - 1 else timesteps[i] dt = dt / self.num_timesteps z = z + v_pred * dt[:, None, None, None, None]

you can refer to SD3 FlowMatchEulerDiscreteScheduler

**Comment by henbucuoshanghai** [comment]
this pro copy the code form FlowMatchEulerDiscreteScheduler?
