### ISSUE TITLE
[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now

### ISSUE THREAD

**Issue by ZXMMD** [hpcaitech/Open-Sora#629]
When I run the training script, as shown in the screenshot, the code is stuck here and not progressing.
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/c3442f90-1e6c-4000-b9de-4154f6a3e075">

**Comment by narrowsnap** [comment]
This is usefull: https://github.com/hpcaitech/ColossalAI/issues/3496#issuecomment-1500436389

**Comment by ZXMMD** [comment]
I have executed the following command：
conda install -c conda-forge gcc=9.5.0 gxx=9.5.0
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
CUDA_EXT=1 pip install .
but the issue persists. Upon investigation, I found that the problem occurs when the code reaches the optimizer setup.
<img width="508" alt="image" src="https://github.com/user-attachments/assets/e5556852-d0e1-4da6-ac77-9b75949cb638">

**Comment by narrowsnap** [comment]
Are you uninstall colossalai first? Or try `rm -r  ~/.cache/colossalai/torch_extensions/`.

**Comment by ZXMMD** [comment]
> Are you uninstall colossalai first? Or try `rm -r ~/.cache/colossalai/torch_extensions/`.
Thank you very much, this solved my problem

**Comment by ZXMMD** [comment]
> Are you uninstall colossalai first? Or try `rm -r ~/.cache/colossalai/torch_extensions/`.

Thank you very much, this solved my problem
