### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by ZeWang95** [hpcaitech/Open-Sora#634]
Hi! 
Thanks for sharing the awesome work!
I'm trying the v1.2 training, and I noticed a very slow training speed. 
Could you please share some info on how the training speed was in your environment? 
Thanks!

**Comment by JThh** [comment]
Check this out: https://github.com/hpcaitech/Open-Sora/blob/476b6dc79720e5d9ddfb3cd589680b2308871926/docs/acceleration.md

**Comment by ZeWang95** [comment]
Thanks for sharing! One quick question: how to interpret the 'setting' in the second table? For example, what does '360x512 (370k)' mean here? Thank you!
