### ISSUE TITLE
Generating short videos with 1.2?

### ISSUE THREAD

**Issue by aweitz** [hpcaitech/Open-Sora#641]
Hi, I previously had success training models that could output a small number of frames (e.g. 16) with the OpenSora 1.1 architecture. However, when training with the new VAE and rectified flow, my model fails catastrophically on videos with 16 frames or less and simply outputs noise (example attached), even though it is being trained on videos of the same length. The model works fine on longer videos.

I noticed in the OpenSora 1.2 training configs that you moved to a minimum of 51 frames in the bucket configuration. Is there a reason why the new VAE and/or rectified flow should not work with short videos?

![00030](https://github.com/user-attachments/assets/1e828588-6734-406e-b4e8-99563c6db0b3)

**Comment by Space-Xun** [comment]
@aweitz Hello, I have encountered a similar problem. I tried to use the v1.2 model to train a 16-frame video, but the loss converged to about 1 and stopped decreasing, and the sampled video was also noisy. Have you tried to train a model with more frames on version 1.2? Will the effect be more normal? Looking forward to hearing from you soon.

**Comment by aweitz** [comment]
Yes at 32 frames and above, 1.2 was able to learn/generate videos correctly.
