### ISSUE TITLE
[HELP] In my train OpenSora1.0 process， I got zhe error ['LowLevelZeroOptimizer' object has no attribute '_param_store'], how to fix it？ 

### ISSUE THREAD

**Issue by pqhgit** [hpcaitech/Open-Sora#642]
Traceback (most recent call last):
  File "/xxx/OpenSora1.0/scripts/train.py", line 328, in <module>
    main()
  File "/xxx/OpenSora1.0/scripts/train.py", line 270, in main
    update_ema(ema, model.module, optimizer=optimizer)
  File "/usr/local/python-3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/xxx/OpenSora1.0/opensora/utils/train_utils.py", line 31, in update_ema
    master_param = optimizer._param_store.working_to_master_param[param_id]
AttributeError: 'LowLevelZeroOptimizer' object has no attribute '_param_store'

I can't find any class with 'LowLevelZeroOptimizer' or  '_param_store' in this project, how to fix it？

**Comment by narrowsnap** [comment]
In my experiments, I change it to `master_param = optimizer.working_to_master_param[param_id]`.

**Comment by pqhgit** [comment]
@narrowsnap this worked, thx

**Comment by pqhgit** [comment]
modify  /xxx/OpenSora1.0/opensora/utils/train_utils.py", line 31
-> master_param = optimizer.working_to_master_param[param_id]
solved.

**Comment by FlyHighest** [comment]
pip install colossalai==0.4.0

**Comment by narrowsnap** [comment]
> After changing it to `master_param = optimizer.working_to_master_param[param_id]`, I still have the `AttributeError: : 'LowLevelZeroOptimizer' object has no attribute 'working_to_master_param'`. Can anyone help?

What's your version of colossalai?
