### ISSUE TITLE
Every data pair has text guided during training?

### ISSUE THREAD

**Issue by hello-bluedog** [hpcaitech/Open-Sora#643]
It seems that only the text guidance model was trained during training, and there was no joint training of the non-text guided generation counter part。
Why is it possible to generate the part when the text is null during inference?

**Comment by hello-bluedog** [comment]
In Classifier Free Training process, text is dropped with a certain probability.
But I can't find this in opensora v1.2 training scripts
However, opensora uses CFG method for inference, which I cannot understand.

**Comment by FlyHighest** [comment]
It is implemented in `CaptionEmbedder`. Have a look at the method `token_drop`
