### ISSUE TITLE
function not implemented

### ISSUE THREAD

**Issue by NinoNeumann** [hpcaitech/Open-Sora#669]
It seems that the get_pad_layer function in opensora.models.vae.discriminator.py has not been implemented.

**Comment by FlyHighest** [comment]
don't worry. pad_off is always 0. therefore this function is never called.

**Comment by NinoNeumann** [comment]
As this function is never called, why include it?

**Comment by NinoNeumann** [comment]
> don't worry. pad_off is always 0. therefore this function is never called.
As this function is never called, why include it?

**Comment by NinoNeumann** [comment]
> don't worry. pad_off is always 0. therefore this function is never called.

As this function is never called, why include it?
