### ISSUE TITLE
修改`bucket_config`配置，可能会导致一些bug

### ISSUE THREAD

**Issue by JWargrave** [hpcaitech/Open-Sora#676]
改变`bucket_config`配置，有可能会导致一些莫名其妙的错误。

我用以下配置在我自己的视频数据集（大概7w多个视频）上训练，训了很久都很正常，没有报错。
```python
bucket_config = {
    "480p": {51: (1.0, 4), 102: (1.0, 2), 204: (1.0, 1)},
    "720p": {17:(1.0, 2), 34:(1.0, 1)},
    "1024": {17:(1.0, 2), 34:(1.0, 1)},
}
```

但是如果我把配置改成如下，训了大约2个epoch后就会异常退出，且没有任何有效的错误信息：
```python
bucket_config = {
    "480p": {34: (1.0, 4), 51: (1.0, 4), 102: (1.0, 2), 204: (1.0, 1)},
    "720p": {17:(1.0, 2), 34:(1.0, 1)}
}
```

<img width="688" alt="image" src="https://github.com/user-attachments/assets/c81a6909-5a85-442b-888a-7293d8893da4">

这个[issue](https://github.com/hpcaitech/Open-Sora/issues/612)中也指出，使用另一种不同的`bucket`配置，也会出现错误和上面不一样的错误。

**Comment by henbucuoshanghai** [comment]
几块什么卡？只有三种hw？

**Comment by JWargrave** [comment]
> 几块什么卡？只有三种hw？

8块H800；
是的，我只需要这三种hw，此外，我把get_bucket_id简化了一下，具体内容在[这](https://github.com/hpcaitech/Open-Sora/issues/612#issuecomment-2232146476)。有些hw的配置就跑的没问题（上面提到的3种hw的配置），有些就有问题（上面提到的2种hw的配置）。

**Comment by ITerydh** [comment]
我发现使用大的帧数或者大的num_worker读取 就会出现这个问题

**Comment by henbucuoshanghai** [comment]
会OOM?使用大的帧数？视频长度？

**Comment by JWargrave** [comment]
> 会OOM?使用大的帧数？视频长度？

是训练了一段时间后，会异常退出，且没有任何有效的错误信息
