### ISSUE TITLE
traing & testing gap

### ISSUE THREAD

**Issue by Limingxing00** [hpcaitech/Open-Sora#677]
Hi,

Thank you for the awesome work. I have some problems:
1. During training, the `cfg-scale` is set to 4 and `number of timestep` is set to 10. But when testing, the `cfg-scale` is set to 7 and `number of timestep` is set to 30. I could not understand what happened, would it be better to set `number of timestep` to 30 during training?
2. Why the training frame number is 51 for a 2s-long video, instead of 48?

Looking forward to your answer.

**Comment by henbucuoshanghai** [comment]
cfg 4VS 7？ maybe it is better?
