### ISSUE TITLE
only t

### ISSUE THREAD

**Issue by henbucuoshanghai** [hpcaitech/Open-Sora#682]
python scripts/inference.py

**Comment by henbucuoshanghai** [comment]
python scripts/inference.py     only  has    t2v？where is the i2v ?I didnt found it,
tks

**Comment by FlyHighest** [comment]
You can find the details in [commands.md](https://github.com/hpcaitech/Open-Sora/blob/main/docs/commands.md)

```
--prompt 'A breathtaking sunrise scene.{"reference_path": "assets/images/condition/wave.png","mask_strategy": "0"}'
```
This is i2v parameter. mask_strategy:0 means using the image as the first frame. Also search "mask_strategy" for more information.

**Comment by henbucuoshanghai** [comment]
kind answer,I will learn the code.
image condition,video extending, how to input the latent spaces?
