### ISSUE TITLE
BlockDiagonalMask import error

### ISSUE THREAD

**Issue by yja1** [hpcaitech/Open-Sora#684]
in block.py 476 line
module 'xformers.ops.fmha' has no attribute 'BlockDiagonalMask' 
use rocm/xformers

**Comment by tobiaswuerth** [comment]
I experienced the same issue. I think it had to do with the wrong version. I had torch+cu124 installed and xformers==0.0.28 something.

```
python.exe -m pip uninstall xformers torch torchvision torchaudio
python.exe -m pip install xformers torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

solved it for me
