### ISSUE TITLE
Details about normalizing each channel for rectified flow training.

### ISSUE THREAD

**Issue by EvePhil** [hpcaitech/Open-Sora#692]
I found that it's mentioned in [report_03](https://github.com/hpcaitech/Open-Sora/blob/main/docs/report_03.md) that
`
New VAE and fps conditioning: we replace the original VAE with ours and add fps conditioning to the timestep conditioning, we train for 25k steps. Note that normalizing each channel is important for rectified flow training.
`
I failed to find how you normalized each channel in details, maybe four 0.18215-like scale factors for four channels? Could any one lend a hand?

**Comment by henbucuoshanghai** [comment]
normalizing each channel?nn. Ln?
