### ISSUE TITLE
About edit_ratio

### ISSUE THREAD

**Issue by JonathanLi19** [hpcaitech/Open-Sora#695]
If edit_ratio is set to 1, then in the apply_mask_strategy funtion, the mask will be all set to 1. 
Then, in line 66-68 in opensora/schedulers/rf/__init__.py, noise_added will be set to all one.
So '~noise_added' will be all zero, and 'mask_add_noise' will also be all zero.
This seems not true, as we obviously want to add noise to the area since edit_ratio is set to 1 means full edit.
I want to ask why does this happen? Or Is my understanding wrong?

**Comment by henbucuoshanghai** [comment]
same qustion
