### ISSUE TITLE
Question about image2video quality

### ISSUE THREAD

**Issue by JonathanLi19** [hpcaitech/Open-Sora#696]
I run the following command to generate video from an image:
'python scripts/inference.py configs/opensora-v1-1/inference/sample.py --num-frames 32 --sample-name image-cond2_1.1  --prompt 'Two men surfing at the palace.{"reference_path": "assets/images/condition/wave.png","mask_strategy": "0"}''
And the result video is very poor (the following frames is not related to the image condition), is there something wrong?

https://github.com/user-attachments/assets/2b4d82b8-0d49-4f2a-9785-74de015b5fff

**Comment by JonathanLi19** [comment]
Also, when I try to generate video using the following command:
python scripts/inference.py configs/opensora-v1-2/inference/sample.py --num-frames 32 --sample-name image-cond2_1.2  --prompt 'Two men surfing at the palace.{"reference_path": "assets/images/condition/wave.png","mask_strategy": "0"}'
The result video nearly doesn't have movement. 
**(It seems that opensora1.1 can't support 4s video; while opensora1.2 can't support 32 frames video)**
https://github.com/user-attachments/assets/ffc0ee6d-d50c-4522-903a-660088785eb2

**Comment by henbucuoshanghai** [comment]
image2video quality？ why？

**Comment by JonathanLi19** [comment]
> image2video quality？ why？
I try to generate video from this image: assets/images/condition/wave.png

**Comment by henbucuoshanghai** [comment]
maybe this pro must be trained by yourself,the resout may be better?

**Comment by JonathanLi19** [comment]
It seems that Opensora-1.1 is trained on videos of length 1,16,32,96; Opensora-1.2 is trained on videos of length 1,51,102,204,408. Thus, this phenomenon is resonable.
