### ISSUE TITLE
Will opensora 1.3 be released recently?

### ISSUE THREAD

**Issue by SamitHuang** [hpcaitech/Open-Sora#712]

**Comment by powerspowers** [comment]
Interesting as we see open-sora, open-sora-plan and cogvideox all in play as open source next gen models but every one of these projects is so quiet on longer term support and plans that its hard to bet on any of them sticking around long enough to do something on top of them. 
Would love an open-sora 1.3 training baseline to better compete with Luma and similar mid-size commercial models. The promise here is that a well trained model like open-sora could be the Stable Diffusion 1.5 of the video AI world if it breaks through on a reasonable training set!

**Comment by henbucuoshanghai** [comment]
Will opensora 1.3 be released recently?

**Comment by henbucuoshanghai** [comment]
Will opensora 1.3 be released recently?。。

**Comment by binmakeswell** [comment]
Hi, welcome to try  https://company.hpc-ai.com/blog/unlock-creativity-with-video-oceans-video-magic-box-any-character-any-style first. Thanks.

**Comment by powerspowers** [comment]
This is interesting. I ran a couple videos and it looks to be the same as what I get from open-sora 1.2 text to video. Is the character to video option the new part? I am very curious about that work flow!

Will there be an open-sora 1.3 base model along with code soon?

**Comment by henbucuoshanghai** [comment]
> open-sora-plan has a new version. kling is awesome. cogvideox is making fast progress. Pyramid flow also making leaps.
> 
> i think the open-sora is being left behind and maybe Plan or Pyramid or CogvideoX will win the hearts of people committed to true open source?

right

**Comment by powerspowers** [comment]
Now Genmo released Mochi model (480p generation) under Apache 2.0. The battle for which model will claim the strongest title for open source is on.
Open-Sora team, we are still believing in you especially because you published all the tagging and training tools!
