### ISSUE TITLE
AttributeError: module 'torch.compiler' has no attribute 'is_compiling'

### ISSUE THREAD

**Issue by qqnr88** [hpcaitech/Open-Sora#741]
AttributeError: module 'torch.compiler' has no attribute 'is_compiling'

**Comment by Toroidal-meow** [comment]
Same problem here. Fixed by modifying the fused_layer_norm.py in Apex.

Change line 412 and 316 If statement as follows:

`if torch.jit.is_tracing() or torch.jit.is_scripting() or (hasattr(torch.compiler, 'is_compiling') and torch.compiler.is_compiling()) or not input.is_cuda:`

**Comment by Radioheading** [comment]
Replacing corresponding code in package apex into `if torch.jit.is_tracing() or torch.jit.is_scripting() or (hasattr(torch.compiler, 'is_compiling') and torch.compiler.is_compiling()) or not input.is_cuda:` works for me. A good way for fixing it is to search all the lines containing `torch.compiler.is_compiling()` into the aforementioned code

**Comment by KLL535** [comment]
> Replacing corresponding code in package apex into `if torch.jit.is_tracing() or torch.jit.is_scripting() or (hasattr(torch.compiler, 'is_compiling') and torch.compiler.is_compiling()) or not input.is_cuda:` works for me. A good way for fixing it is to search all the lines containing `torch.compiler.is_compiling()` into the aforementioned code

Can you tell me how to do this?
Apex module, where to find it source if it was installed via git+https?

**Comment by nahidalam** [comment]
@KLL535 for me in Apex 0.1 it was this file /opt/conda/envs/opensora/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py at line `798` and `894`
