### ISSUE TITLE
ModuleNotFoundError: No module named 'colossalai.utils.safetensors'

### ISSUE THREAD

**Issue by haixiao-stack** [hpcaitech/Open-Sora#763]
I follow the instruction
# create a virtual env and activate (conda as an example)
conda create -n opensora python=3.9
conda activate opensora

# install torch, torchvision and xformers
pip install -r requirements/requirements-cu121.txt

# download the repo
git clone https://github.com/hpcaitech/Open-Sora
cd Open-Sora

# the default installation is for inference only
pip install -v . # for development mode, `pip install -v -e .`

(Optional, recommended for fast speed, especially for training) To enable `layernorm_kernel` and `flash_attn`, you need to install `apex` and `flash-attn` with the following commands.

```bash
# install flash attention
# set enable_flash_attn=False in config to disable flash attention
pip install packaging ninja
pip install flash-attn --no-build-isolation

# install apex
# set enable_layernorm_kernel=False in config to disable apex
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" git+https://github.com/NVIDIA/apex.git
but 
![Uploading 微信截图_20241223172211.png…]()

**Comment by ImmNaruto** [comment]
遇到了相同的问题，切换至指定分支 @38de637重新尝试就可以了

**Comment by 2635522924** [comment]
> 遇到了相同的问题，切换至指定分支 @38de637重新尝试就可以了

请问怎么切换

**Comment by ImmNaruto** [comment]
> > 遇到了相同的问题，切换至指定分支 @38de637重新尝试就可以了
> 
> 请问怎么切换

在Open-Sora项目文件夹下，先git checkout 38de637，然后执行pip install -v . 安装即可

**Comment by 2635522924** [comment]
> > > 遇到了相同的问题，切换至指定分支 @38de637重新尝试就可以了
> > 
> > 
> > 请问怎么切换
> 
> 在Open-Sora项目文件夹下，先git checkout [38de637](https://github.com/hpcaitech/Open-Sora/commit/38de637cab331ca106d67467b63f66fc71678391)，然后执行pip install -v .安装即可

可以了！十分感谢！
