### ISSUE TITLE
Questions on the choice of VAE

### ISSUE THREAD

**Issue by Red-Fairy** [hpcaitech/Open-Sora#83]
Dear Authors,

Thanks for your great work! 

I've just read your report and come up with some questions regarding the choice of the VAE. You mentioned that VideoGPT yields poor performance, so you chose 2D VAE because 3D sota VAEs like MAGVIT-v1/v2 are not open-sourced. 

My question is have you ever tried using other 3D-VAE variants like TATS (Long Video Generation with Time-Agnostic VQGAN and Time-Sensitive Transformer)?

Thanks in advance!

**Comment by zhengzangw** [comment]
Not yet. We plan to train our 3D-VAE, and will update if we have any progress.

**Comment by Birdylx** [comment]
@Red-Fairy  I'v tried TATS, even worse results than VideoGPT.

**Comment by Red-Fairy** [comment]
> @Red-Fairy I'v tried TATS, even worse results than VideoGPT.

Thanks! It seems using 2D VAE and then sequentially concatenating the tokens is the best choice given the unavailability of MAGVITs. 

BTW, does anyone know the trade-off between using VQVAEs and VAEs?
