### ISSUE TITLE
Can we use t5-large text encoder model to use with the opensora pretrained weights?

### ISSUE THREAD

**Issue by sandeshrajbhandari** [hpcaitech/Open-Sora#95]
Edit: seems we can't use the smaller models, so it would be handy to have a way to load the xxl models in 8bit format for smaller vram GPUs. its doable for pixart image gen models using diffusers library.

I tried to use `google/t5-v1_1-large` model as text encoder instead of `DeepFloyd/t5-v1_1-xxl`, but encountered following error.
```
RuntimeError: Error(s) in loading state_dict for STDiT:
	size mismatch for y_embedder.y_embedding: copying a param with shape torch.Size([120, 4096]) from checkpoint, the shape in current model is torch.Size([120, 1024]).
	size mismatch for y_embedder.y_proj.fc1.weight: copying a param with shape torch.Size([1152, 4096]) from checkpoint, the shape in current model is torch.Size([1152, 1024]).
```
It seems the output embedding dimension for large model is 1024 and for xxl is 4096, and opensora weights only accept weights from xxl model i.e. 4096 dim weights. 

is there anyway we can use the t5-large model instead of the xxl model? I want to run inference in cloud gpus i.e. T4 in colab notebooks. 

here's my notebook as a gist i used to run on colab. 
https://gist.github.com/sandeshrajbhandari/ac3857cd2aaae5e3a9de0d7c219ac351

**Comment by kadirnar** [comment]
I am creating a demo for the HuggingFace platform and I cannot install the apex library. Is there a way to skip this? How can I add this code to req.txt file?

```bash
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "- -build-option=--cuda_ext" git+https://github.com/NVIDIA/apex.git
```

I am getting errors due to parameters.

<img width="1079" alt="image" src="https://github.com/hpcaitech/Open-Sora/assets/36204372/71a6c0c9-da98-4338-bde2-c7d05eb9bcbc">

**Comment by sandeshrajbhandari** [comment]
install the apex library. 
I installed the apex package by cloning the original repo and modifying the `check_cuda_torch_binary_vs_bare_metal(cuda_dir):` in setup.py to remove runtime error to compile apex. i replace `raise RuntimeError` with `print` function.
```
def check_cuda_torch_binary_vs_bare_metal(cuda_dir):
    raw_output, bare_metal_version = get_cuda_bare_metal_version(cuda_dir)
    torch_binary_version = parse(torch.version.cuda)

    print("\nCompiling cuda extensions with")
    print(raw_output + "from " + cuda_dir + "/bin\n")

    if (bare_metal_version != torch_binary_version):
        print(
            "Cuda extensions are being compiled with a version of Cuda that does "
            "not match the version used to compile Pytorch binaries.  "
            "Pytorch binaries were compiled with Cuda {}.\n".format(torch.version.cuda)
            + "In some cases, a minor-version mismatch will not cause later errors:  "
            "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
            "You can try commenting out this check (at your own risk)."
        )
```

let me know if this helps, im trying to run this in colab.

**Comment by kadirnar** [comment]
@sandeshrajbhandari 

I downloaded the Apex repo and updated the setup.py file. to req.txt file

-v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \" --build-option=--cuda_ext\" ./"

I added the code.

Error Message:
```bash
ERROR: Invalid requirement: -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \"--build-option=--cuda_ext\" ./"
Could not split options: -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \"--build-option=--cuda_ext\" ./"
```

Can you help?
Demo: https://huggingface.co/spaces/kadirnar/Open-Sora

**Comment by sandeshrajbhandari** [comment]
try adding this one line in the requirements.txt. it will point to the local folder to install apex from. I guess this is the issue. let me know if it helps.
`-e ./apex --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext"`

**Comment by kadirnar** [comment]
@sandeshrajbhandari ,

I cannot use the notebook feature on the HuggingFace platform. That's why I can't use the cd command. I git cloned the Apex repo. Then I updated the setup.py file.

```bash
ERROR: Invalid requirement: -e ./apex --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext"
pip: error: no such option: --disable-pip-version-check
```

Should I export the files in the apex folder?
![image](https://github.com/hpcaitech/Open-Sora/assets/36204372/8470e909-8d5c-4801-930c-8dbbb1963bf8)

**Comment by kabachuha** [comment]
XXL weights might be actually better, because as the research on story understanding shows, the larger the hidden dimension, the better it understands the plot and relationships between IRL objects https://arxiv.org/abs/2305.07759
